Qiskit/documentation

README.md
start

Closes https://github.com/Qiskit/docs/issues/1. Running `./start` will open up the One Docs app at localhost:3000 using content from the local repository.
Currently, you have to log into IBM Cloud and have the correct permissions. We will improve this with https://github.com/Qiskit/docs/issues/53.

Add local docs preview for IBM contributors

---

.github/workflows/preview-docs.yaml
Dockerfile
README.md
start

Closes https://github.com/Qiskit/docs/issues/3. We use the same open source workflow we use with qiskit.org and qiskit-sphinx-theme.
We only preview the docs for PRs built directly on this repository, not for forks. That is a security restriction due to how forks work.

PR builds include a live preview

---

package-lock.json
package.json
scripts/commands/updateApiDocs.ts
scripts/lib/GithubApiClient.ts
scripts/lib/WebCrawler.ts
scripts/lib/downloadImages.ts
scripts/lib/env.ts
scripts/lib/fs.ts
scripts/lib/zx.ts

Part 2 of https://github.com/Qiskit/documentation/issues/9.
The final part will run this script to generate the API docs. There are some things I want to tweak in the script like that the qiskit-ibm-runtime site has changed URLs, but I wanted to avoid making changes to the script in this PR so that it simply copies them over.
This PR simply copies over the API pipeline written by @axelhzf from closed source to open source. Its only modifications are adding copyright headers and removing unused code from utility files.
https://github.com/Qiskit/documentation/issues/63 tracks some ideas to simplify this pipeline in follow ups, such as not needing GitHub.

Migrate API pipeline script from closed source

---

docs/support.mdx

This was oversight. I didn't realize we needed to migrate this page too.
The page is simply copy-and-pasted.

Migrate support page from closed source

---

docs/run/_toc.json

We have move the errors page link to the _Api reference_ header menu in https://docs.quantum-computing.ibm.com/ to facilitate the access, so it won't be under run section anymore.

Remove errors page link from run toc

---

.github/ISSUE_TEMPLATE/new-content.yaml

fix yaml in issue template 

---

qiskit-docs/how_to/use_estimator.rst

For some reason, this wasn't brought in via https://github.com/Qiskit/documentation/pull/118. This uses `git cherry-pick` to bring in the relevant commit.

Migrate missing estimator how to from Qiskit (Qiskit/qiskit#9716)

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/new-content.yaml
.github/ISSUE_TEMPLATE/ui.yml

From @javabster -- improvements to issue templates:
```
```
add the links to the 1 line description of the issue

Edits to issue templates

---

docs/run/run-sessions.mdx
docs/run/sessions.mdx
docs/start/hello-world.ipynb
docs/start/index.mdx
docs/start/migrate-examples.mdx
docs/start/migrate.mdx
docs/start/runtime.mdx
docs/test/noise.mdx

Check for any links pointing to files that have moved or been removed.

Fix broken links after toc reorganization

---

Dockerfile
README.md
start

We started publishing a new Docker image to public Dockerhub without password protection. So, we can now have live local preview for every contributor! Closes https://github.com/Qiskit/documentation/issues/53.
However, the live preview has a worse UI due to security constraints. It doesn't have the top nav bar, nor the index page.
So, we will have _two_ Docker images: the public Docker image and the password-protected Docker image. We'll keep using the password-protected Docker image for PR previews and the staging website at https://qiskit-docs-preview-staging.1799mxdls7qz.us-south.codeengine.appdomain.cloud/, since it's a more useful preview.

Switch local preview to public Docker image

---

docs/start/hello-world.ipynb
docs/start/index.mdx

We've removed intro to Qiskit and intro to Qiskit Runtime temporarily, so need to remove links to these files on the Start/index page.

Remove broken links on Start page

---

scripts/lib/sphinx/sphinxHtmlToMarkdown.test.ts
scripts/lib/sphinx/sphinxHtmlToMarkdown.ts

Fixes one of the issues in https://github.com/Qiskit/documentation/issues/67, that we weren't removing the permalink in headers with qiskit-ibm-runtime:
This change is because of https://github.com/sphinx-doc/sphinx/commit/7e9a2066c2f31eda53d075f5a8b20a7430ca0c61. Sphinx 7.2 changed the title from "Permalink" to "Link".

Fix permalinks with API generation for Sphinx 7.2+

---

scripts/lib/sphinx/sphinxHtmlToMarkdown.test.ts
scripts/lib/sphinx/sphinxHtmlToMarkdown.ts

In Qiskit docs, which use an older version of Sphinx, the module ID is set with HTML like this:
```html
<span class="target" id="module-qiskit.circuit">
<span id="qiskit-circuit"></span>
</span>
```
But in Runtime with Sphinx 7.2, it is set like this, without the `.target` class:
```html
<span id="module-qiskit_ibm_runtime.options"></span>
```
So, we were failing to set metadata for modules, which caused those files to not have "front matter" (Markdown metadata) and to not show up in the TOC. See https://github.com/Qiskit/documentation/issues/67.
Note that we still look at `section` to determine the module metadata, too. There continue to be some pages in IBM Provider that set their module metadata that way.

Fix detection of module metadata with API generation

---

scripts/commands/checkLinks.ts

Turns out the script was not correctly extracting markdown from notebooks. We didn't notice because `markdown-link-extractor` seems to be able to find the links from the JSON source 99% of the time.
Despite this, `markdown-link-extractor` doesn't offically support notebooks, so I've fixed the code. This found one more broken link, which I've ignored:
```
❌ docs/build/pulse.ipynb: Could not find link 'pulse_modulation.png'
```

Fix link checker for notebooks

---

docs/api/migration-guides/qiskit-runtime-examples.mdx
docs/api/migration-guides/qiskit-runtime.mdx
docs/build/pulse.ipynb
docs/start/index.mdx
scripts/commands/checkLinks.ts

I accidentally broke this in https://github.com/Qiskit/documentation/pull/177.
This PR fixes the broken links and also a few others, such that our link checker now checks every non-API file 🎉 To fix some errors, it adds a `SYNTHETIC_FILES` list, which are files that only exist in closed source but not open source; so the links are valid, even though the files aren't present here.

Fix broken links for migration guides

---

docs/api/qiskit-ibm-runtime/_toc.json
docs/api/qiskit-ibm-runtime/options.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.Estimator.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.IBMBackend.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.ParameterNamespace.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.QiskitRuntimeService.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.RuntimeDecoder.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.RuntimeEncoder.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.RuntimeJob.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.RuntimeOptions.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.RuntimeProgram.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.Sampler.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.Session.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.EnvironmentOptions.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.ExecutionOptions.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.Options.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.ResilienceOptions.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.SimulatorOptions.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.options.TranspilationOptions.md
docs/api/qiskit-ibm-runtime/runtime_service.md

Now that we fixed https://github.com/Qiskit/documentation/issues/67, we can regenerate the API docs. The issues were due to changes with modern Sphinx 7.2.
There was one regression I noticed, but it's not enough of a show-stopper to block this PR: https://github.com/Qiskit/documentation/issues/224.

Update Runtime API docs to 0.13

---

docs/api/migration-guides/__migration-guide-algorithms.md.txt
docs/api/migration-guides/__migration-guide-opflow.md.txt
docs/api/migration-guides/__migration-guide-qi.md.txt

Part of https://github.com/Qiskit/documentation/issues/213. 
This doesn't finish converting all the cross references, but gets most of them.
My original attempt manually converted things, but I realized this wasn't scalable so I instead switched to writing this script. The cross-references have several different possible styles, like this:
```
:meth:`qiskit.my_module`
:meth:`~qiskit.my_module`
{meth}`qiskit.my_module`
{meth}`~qiskit.my_module`
```
The script looks for all these different variations, then replaces it with the markdown-style link. It also validates that the new reference actually exists.
```python
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
GUIDES = [
Path(f"docs/api/migration-guides/__migration-guide-{guide}.md.txt")
for …
```

Convert some Sphinx cross references to Markdown

---

docs/api/qiskit-ibm-provider/qiskit_ibm_provider.IBMBackend.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.IBMBackendService.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.job.IBMCircuitJob.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.job.IBMCompositeJob.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.least_busy.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.ALAPScheduleAnalysis.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.ASAPScheduleAnalysis.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.BlockBasePadder.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.DynamicCircuitInstructionDurations.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.PadDelay.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.PadDynamicalDecoupling.md
docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.md

I've done my best to fix up the links that were broken due to https://github.com/Qiskit/documentation/pull/202
There were some links that we just don't have ways to link to in onedocs, because we are missing anchor tags for methods within api ref pages. So for these links I just removed the link entirely

Attempted to fix broken API ref links

---

docs/api/migration-guides/__migration-guide-algorithms.md.txt
docs/api/migration-guides/__migration-guide-opflow.md.txt

Step 2 of #213 
Some references don't work even on the original page, so I just deleted them.
With this, https://github.com/Qiskit/documentation/pull/237 can be merged.

fix references in migration guides

---

docs/run/_toc.json

@javabster noted that the most important part of this title in the table of contents is cut off (until the toc truncation issue is fixed), so pushing through a temporary fix on just the toc and leaving the "better" title on the page itself -- changing to "Quantum Serverless workloads" until the truncation fix is in production. FYI @psschwei @jenglick

Shorten title temporarily until truncation in toc is fixed

---

docs/api/migration-guides/qiskit-opflow-module.mdx
docs/api/migration-guides/qiskit-quantum-instance.mdx

Part of https://github.com/Qiskit/documentation/issues/213.
I used the below script. Warning: it doesn't handle when the list item has multiple lines for the entry. Those were manually fixed in the second commit.
```python
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator
GUIDES = [
Path(f"docs/api/migration-guides/qiskit-{guide}.mdx")
for guide in ("algorithms-module", "opflow-module", "quantum-instance")
]
@dataclass
class Table:
header: list[str]
entries: list[list[str]]
@classmethod
def from_rst(cls, rst: str) -> Table:
parsed_rows: list[list[str]] = []
current_row: list[str] = []
for line in rst.splitlines():
line = line.strip()
if line.startswith("* -"):  # new row
if current_row:
parsed_rows.append(current_row) …
```

Convert list tables in migration guides to Markdown tables

---

docs/api/migration-guides/qiskit-algorithms-module.mdx
docs/api/migration-guides/qiskit-opflow-module.mdx
docs/api/migration-guides/qiskit-quantum-instance.mdx

Part of https://github.com/Qiskit/documentation/issues/213. 
There are still a couple dropdowns left, but they were more complex to migrate. So I'll do them in a follow up.
The code blocks are the same as before, only now using Markdown code block syntax. This PR also fixes the admonitions to use `type='caution'` rather than `warning`, which doesn't exist.

Convert code blocks in migration guides to Markdown

---

docs/api/migration-guides/qiskit-algorithms-module.mdx
docs/api/migration-guides/qiskit-opflow-module.mdx
docs/api/migration-guides/qiskit-quantum-instance.mdx
docs/api/migration-guides/qiskit-runtime-examples.mdx
docs/run/configure-error-mitigation.mdx
docs/run/instances.mdx
docs/verify/noisy-simulators.mdx
docs/verify/simulate-with-qiskit-primitives.mdx

First pass at https://github.com/Qiskit/documentation/issues/297. qiskit.org will be going away, per https://medium.com/qiskit/important-changes-to-qiskit-documentation-and-learning-resources-7f4e346b19ab. So these links need to be fixed.
Some of the tutorials were not ported over 1:1, such as the Learn materials and Algorithms tutorials (algorithms no longer are part of Qiskit). Because the links are for migration guides that need the exact examples, I instead used stable GitHub links to the original source files.

Replace most links to qiskit.org

---

docs/api/migration-guides/_toc.json
docs/api/migration-guides/index.mdx
docs/api/migration-guides/qiskit-algorithms-module.mdx
docs/api/migration-guides/qiskit-opflow-module.mdx
docs/api/migration-guides/qiskit-quantum-instance.mdx

Closes https://github.com/Qiskit/documentation/issues/213.
These changes are all manual. I looked over the rendered site and MDX files to see issues like `[My link]` without the corresponding `()` for the link itself.  But for tables, I used the script from https://github.com/Qiskit/documentation/pull/296.

Finish converting migration guides to MDX

---

docs/api/migration-guides/qiskit-algorithms-module.mdx
docs/api/migration-guides/qiskit-opflow-module.mdx
docs/api/migration-guides/qiskit-quantum-instance.mdx

We decided these weren't necessary since the right sidebar (page table of contents) already has this functionality.
Removing it makes the guides a little smaller, so easier to read.

Remove manual table of contents from migration guides

---

docs/api/qiskit-ibm-provider/_package.json
docs/api/qiskit-ibm-provider/_toc.json
docs/api/qiskit-ibm-runtime/_package.json
docs/api/qiskit-ibm-runtime/_toc.json
scripts/commands/updateApiDocs.ts
scripts/lib/sphinx/generateToc.test.ts
scripts/lib/sphinx/generateToc.ts

This switches API docs to the new scheme described in https://github.com/Qiskit/documentation/issues/8. 
Even though we don't yet have any historical versions for Provider and Runtime, we will want to add them moving forward. We can switch over to the new version selector now.
A follow up PR will regenerate Qiskit docs. The version changed, so I want a dedicated PR for closer review of those generated docs. A follow up PR will also add historical versions to Qiskit docs.

API docs use the new version selector mechanism

---

docs/build/_toc.json
docs/run/_toc.json
docs/start/_toc.json
docs/verify/_toc.json

Closes https://github.com/Qiskit/documentation/issues/328. We decided this is desirable from a UX perspective.

Collapse left side bars

---

docs/api/qiskit-ibm-runtime/_package.json
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.IBMBackend.md
docs/api/qiskit-ibm-runtime/qiskit_ibm_runtime.Session.md
docs/api/qiskit-ibm-runtime/release-notes.md

These changes are all auto-generated, including the new release notes.
Once we have https://github.com/Qiskit/documentation/issues/332, we can add back the 0.14 API docs by running it on this repository before we this PR was merged.

Generate Runtime 0.15 docs

---

.github/workflows/main.yml

See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

Enable CI to run on merge queue

---

docs/api/migration-guides/_toc.json
docs/api/migration-guides/index.mdx
docs/api/migration-guides/qiskit-runtime-from-provider.mdx

Brings over https://github.com/Qiskit/qiskit-ibm-runtime/pull/1214. I did this by:
1. Copying and pasting the RST file
2. Running `st2myst convert docs/api/migration-guides/qiskit-runtime-backend-run.rst`, which generated a MD file
3. Renaming the file to end in `.mdx` and adding "front matter" (metadata)
4. Manually tweaking any issues
5. Attributing the original author in the Git commit with `git log --pretty="%an <%ae>" -- docs/migrate/backend_run_migration_guide.rst | sort -u | awk '{print "Co-authored-by: " $0}'` run in the qiskit-ibm-runtime repo
I'll set up a redirect in https://github.com/Qiskit/documentation/issues/216 for Nov 29.

Port migration guide for Runtime 0.15

---

README.md
docs/api/migration-guides/qiskit-runtime.mdx
docs/support.mdx

This PR replaces any qiskit.org links with 1XP or github equivalents. Need to wait to merge until I can update the deprecation policy and maintainer guide links after https://github.com/Qiskit/qiskit/pull/11218/ merges.
This should partially resolve #297 , however for the api links we'll need to make updates for those directly in the repos where the API refs live (maybe this is beyond the scope of the original issue?)

Audited qiskit.org links

---

scripts/ibm-quantum-learning-uploader/src/learning_uploader/__init__.py
scripts/ibm-quantum-learning-uploader/src/learning_uploader/upload.py
scripts/ibm-quantum-learning-uploader/test/learning-platform.conf.yaml

Originally, every page in the learning database was a "lesson", but it now has distinct "tutorial" pages. This uploader needs to handle both, so this PR changes the `id...` field of the conf file to `url...` fields.

[Learning uploader] Switch to URLs rather than just IDs

---

docs/api/qiskit-ibm-provider/_package.json
docs/api/qiskit-ibm-runtime/_package.json
docs/api/qiskit/0.44/_package.json
docs/api/qiskit/_package.json
scripts/commands/updateApiDocs.ts

The PR changes the` _package.json` in every API to use only the minor version instead of the full version.
This is a temporary change to unblock the deployment of Qiskit 0.44, which, in the navigation menu, will only show the minor version without each patch following the directory structure created in https://github.com/Qiskit/documentation/pull/377.

Use the minor version in _package.json

---

docs/start/install.mdx

As part of Qiskit 1.0 we've increased the minimum requirements and platform support tiers (see #10902). This commit makes these updates to the hosted documentation so that the documented support tiers for each platform reflects the current state for Qiskit 1.0.0.

Update Qiskit platform support for Qiskit 1.0

---

docs/api/qiskit-ibm-provider/_package.json
docs/api/qiskit-ibm-runtime/_package.json
docs/api/qiskit/0.44/_package.json
docs/api/qiskit/_package.json
scripts/commands/updateApiDocs.ts

This PR reverts Qiskit/documentation#394. The change was a temporary solution until we had a different way of building the version URLs.

Revert "Use the minor version in _package.json"

---

scripts/commands/updateApiDocs.ts

This PR adds support for downloading versions of Qiskit previous to 0.44. The old version of Qiskit used https://qiskit.org/documentation/apidoc/terra.html instead of https://qiskit.org/documentation/apidoc/index.html

Add support for Qiskit versions previous to 0.44

---

docs/run/_toc.json
docs/run/configure-error-mitigation.mdx
docs/run/configure-runtime-compilation.mdx
docs/start/setup-channel.mdx

This PR updates the install and run sections to include note boxes about upcoming Q-CTRL features.
**View a preview of the install updates:** 
https://qiskit-docs-preview-pr-397.1799mxdls7qz.us-south.codeengine.appdomain.cloud/start/setup-channel#set-up-to-use-ibm-cloud (note box in step 3 and another note box in step 5)
**View a preview of the run updates:**
- https://qiskit-docs-preview-pr-397.1799mxdls7qz.us-south.codeengine.appdomain.cloud/run/configure-runtime-compilation (second notebox under the table)
- https://qiskit-docs-preview-pr-397.1799mxdls7qz.us-south.codeengine.appdomain.cloud/run/configure-error-mitigation (second note box under the table)
(at the same time I also reshuffled a few things for general improvements to install and run)
These changes should be merged and …

Add Q-CTRL info to install and run sections

---

scripts/lib/sphinx/sphinxHtmlToMarkdown.ts

In https://github.com/Qiskit/documentation/pull/418, we have some lines like this:
```
Qiskit Aer API Reference[¶](#qiskit-aer-api-reference "Permalink to this headline")
```
That's happening because Sphinx changed the word "headline" to "header" in later versions, and we weren't accounting for "headline".

Fix permalinks for old Qiskit API docs

---

docs/start/index.mdx

Once the transpile tab is live, this PR can be merged, which adds a brief description and pointer to the Transpile section alongside the other sections described there.

[merge AFTER transpile tab goes live] Add transpile to start/index page

---

scripts/commands/updateApiDocs.ts

This PR adds a method to create the historical folders of the historical version we try to generate in case this folder doesn't exist. Previously, the script failed without doing anything.
Closes #425

Fix API generation when the folder doesn't exist

---

docs/api/migration-guides/qiskit-algorithms-module.mdx
docs/api/migration-guides/qiskit-opflow-module.mdx
docs/api/migration-guides/qiskit-quantum-instance.mdx

Closes https://github.com/Qiskit/documentation/issues/301.
I didn't change the links for APIs that will still exist in Qiskit 1.0, like primitives. It seems useful to point to the newest documentation for those replacements.

Use stable links for migration guides

---

docs/run/processor-types.mdx
docs/run/run-jobs-in-session.mdx
docs/transpile/common-parameters.mdx
docs/transpile/defaults-and-configuration-options.mdx

Related to #453 
Find all remaining urls using the quantum-computing.ibm.com domain and change to quantum.ibm.com.
This does not remove from the api docs; those will need to be fixed in their home repos.

update straggler quantum-computing domain urls

---

docs/start/setup-channel.mdx

Closes #145. That issue also refers to `docs/api/qiskit-ibm-runtime/runtime_service.md` but we can't fix that as it's generated from the runtime repo (should be covered by https://github.com/Qiskit/qiskit-ibm-runtime/issues/1244).

Remove use of `qiskit.test`

---

docs/api/qiskit-ibm-runtime/0.16/_package.json
docs/api/qiskit-ibm-runtime/0.16/_toc.json
docs/api/qiskit-ibm-runtime/0.16/ibm-runtime.md
docs/api/qiskit-ibm-runtime/0.16/index.md
docs/api/qiskit-ibm-runtime/0.16/options.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.Estimator.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.IBMBackend.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.QiskitRuntimeService.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.RuntimeDecoder.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.RuntimeEncoder.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.RuntimeJob.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.RuntimeOptions.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.Sampler.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.Session.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.EnvironmentOptions.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.ExecutionOptions.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.Options.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.ResilienceOptions.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.SimulatorOptions.md
docs/api/qiskit-ibm-runtime/0.16/qiskit_ibm_runtime.options.TranspilationOptions.md
docs/api/qiskit-ibm-runtime/release-notes.md

This PR adds the API docs for qiskit-ibm-runtime 0.17.0 and converts version 0.16 into a historical one.
Commands used:
```
npm run make-historical -- -p qiskit-ibm-runtime
npm run gen-api -- -p qiskit-ibm-runtime -v 0.17.0 -a https://github.com/Qiskit/qiskit-ibm-runtime/suites/18863019852/artifacts/1100724937
```
The CI run used to build the current version: 
https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/7136304937

Generate qiskit-ibm-runtime 0.17.0 API docs

---

scripts/commands/checkMetadata.ts

Closes https://github.com/Qiskit/documentation/issues/200.
Note that we still want to improve this metadata checker to also start checking some quality things, like that it's <160 characters. But this is a good first pass. See https://github.com/Qiskit/documentation/issues/327.
```
Invalid Jupyter notebook metadata. Every .ipynb file needs to 
set 'title' and 'description' in the file metadata. You need to
manually add this metadata. 
For example, if using VSCode, open up the file with the "Open With..." option and then "Text Editor".
Once the file is open in text-mode, scroll down to the bottom of the file for the top-level key "metadata". Be careful that this is the metada for the entire file
and not a single code block. You should see in the "metadata" section other
entries like …
```

Improve instructions for fixing invalid metadata

---

.github/workflows/preview-docs.yml

I believe content changes are the only changes that should affect the preview. If so, it's a bit wasteful to create a preview for non-content changes, plus it clutters up the PR thread.

Suggestion: Do not create preview if no content changed

---

README.md

Closes https://github.com/Qiskit/documentation/issues/367.
@axelhzf had written an excellent guide for how to work with MDX in the closed source repository, but it wasn't copied over here when docs moved to open source.
This PR:
* Copies over Axel's guide with some small tweaks
* Adds guidance on adding a new page, including how to choose between MDX vs. Jupyter and how to name the file
* Mentions collapsible sections

Add a Markdown guide

---

docs/run/get-backend-information.ipynb
scripts/nb-tester/test-notebook.py

`ibm_lagos` is retired so switching to `ibm_kyoto`.
Also had to switch gate example from `cx` to `ecr` as kyoto doesn't support `cx`.

Fix `get-backend-information.ipynb`

---

scripts/lib/sphinx/renameUrls.ts

When generating docs for Terra before 0.44, the index page was called `terra.html`. We need it to be called `index`.

Rename terra.md to index.md

---

scripts/commands/updateApiDocs.ts

We weren't calling `await` on `startWebServer` and `mkdirp`. This could result in order-of-operation issues.
While fixing that, I realized that we can simplify the code. We only need to start the web server if we're downloading the artifact from CI. So, only have that code in the `else` block. We can reduce the amount of code by moving the server's start to inside `downloadApiSources`.

Fix some async errors in updateApiDocs.ts

---

scripts/commands/checkLinks.ts
scripts/lib/linkCheckerIgnores.ts

The config added too much noise to the file `checkLinks.ts`. That file should only have high-level logic. That allows us to more cleanly split out the list between `SHOULD_BE_FIXED` and `EXPECTED` so that we know what is a legit problem and we're only punting on it.
No changes were made to the actual list.

Extract link checker ignores to a dedicated file

---

scripts/lib/LinkChecker.test.ts
scripts/lib/LinkChecker.ts

Otherwise, we get a couple of duplicate error messages. This happens when the same file has the same bad link >1 times.

Deduplicate error messages in link checker for same link in same file

---

start

In https://github.com/Qiskit/documentation/pull/541, we're going to need to add semi-complex logic to our `./start` script to dynamically discover every subfolder we have in `translations/`, then tell Docker to mount the folder as a volume. I'd much rather write that logic in Python than Bash.
This PR is prework so that https://github.com/Qiskit/documentation/pull/541 is a smaller PR. It makes no logic changes and should be a 1:1 mapping.

Rewrite `./start` script to Python

---

scripts/commands/checkLinks.ts
scripts/lib/links/FileBatch.ts
scripts/lib/links/LinkChecker.test.ts
scripts/lib/links/LinkChecker.ts

In https://github.com/Qiskit/documentation/issues/495, we will start checking historical API docs. For performance, it's important that we don't load every single file in the project at once in memory. Instead, we want to operate in batches: e.g. check all of 0.44, then drop from memory and move on to 0.43.
This PR is a pre-factor to add a new `FileBatch` class. For now, we only have a single `FileBatch`, the same as before. This class still differentiates between files "to load" vs "to check", per https://github.com/Qiskit/documentation/pull/496.

Refactor link checker to use FileBatch class

---

README.md
scripts/commands/checkLinks.ts
scripts/lib/links/FileBatch.ts

This unblocks https://github.com/Qiskit/documentation/issues/495. We still have to actually fix the broken links, but we can at least now detect them.
To make the script more interactive, we now output a description of each file batch, like this:
```
Checking links for non-API docs
Checking links for qiskit-ibm-runtime v0.14
❌ docs/api/qiskit-ibm-runtime/0.14/ibm-runtime.md: Could not find link 'runtime_service' ❓ Did you mean '/api/qiskit-ibm-runtime/0.14/ibm-runtime'?
❌ docs/api/qiskit-ibm-runtime/0.14/qiskit_ibm_runtime.QiskitRuntimeService.md: Could not find link '/api/qiskit/providers_models'
Checking links for qiskit-ibm-runtime v0.15
❌ docs/api/qiskit-ibm-runtime/0.15/ibm-runtime.md: Could not find link 'runtime_service' ❓ Did you mean '/api/qiskit-ibm-runtime/0.15/ibm-runtime'?
❌ …
```

Allow checking historical APIs with link checker

---

.prettierignore
translations/placeholder.txt

We now have actual translations under the folder `translations/ja`.
Also fixes our Prettier (autoformatter) config to ignore translations.

Remove translations placeholder file

---

.github/workflows/external-link-checker.yml
.github/workflows/main.yml
README.md
scripts/commands/checkLinks.ts

Part of https://github.com/Qiskit/documentation/issues/495. We now will enforce in CI that historical API docs are valid for Runtime and Provider. To do this, this PR adds the `--skip-broken-historical` argument.
In a follow up, I want to try checking Qiskit docs, at least certain versions. But I'm waiting until we regenerate the docs with https://github.com/Qiskit/documentation/pull/552 applied because I suspect it will fix some issues.

Check Runtime historical API docs for broken links

---

docs/api/qiskit/release-notes/0.11.md
docs/api/qiskit/release-notes/0.18.md
docs/api/qiskit/release-notes/0.19.md
docs/api/qiskit/release-notes/0.20.md
docs/api/qiskit/release-notes/0.23.md
docs/api/qiskit/release-notes/0.24.md
docs/api/qiskit/release-notes/0.25.md
docs/api/qiskit/release-notes/0.26.md
docs/api/qiskit/release-notes/0.29.md
docs/api/qiskit/release-notes/0.30.md
docs/api/qiskit/release-notes/0.32.md
docs/api/qiskit/release-notes/0.33.md
docs/api/qiskit/release-notes/0.34.md
docs/api/qiskit/release-notes/0.36.md
docs/api/qiskit/release-notes/0.37.md
docs/api/qiskit/release-notes/0.39.md
docs/api/qiskit/release-notes/0.41.md
docs/api/qiskit/release-notes/0.42.md
docs/api/qiskit/release-notes/0.43.md
docs/api/qiskit/release-notes/0.44.md

This PR changes the release notes to have a chronological descending order.
To regenerate the release notes and fix the order of each version, I used the API generation script with some changes. We need to modify the writeSeparateReleaseNotes function from `releaseNotes.ts` and the `updateApiDocs.ts` script. 
The first step is to comment the `extractMarkdownReleaseNotesPatches` call in line 245, given that we don't want to write the latest release notes file. Also, we need to substitute the two arrays returned by that call for the release notes we want to regenerate and an empty dictionary. I did the regeneration in batches of 6 files:
```ts
//const [minorVersionsFound, markdownByPatchVersion] =
//  extractMarkdownReleaseNotesPatches(releaseNoteMarkdown);
const markdownByPatchVersion: { …
```

Fix release notes order

---

docs/api/migration-guides/_toc.json

This was an oversight. We want to always collapse the left sidebar.

Collapse migration guides left sidebar

---

.github/workflows/extended-checks.yml

As of https://github.com/Qiskit/documentation/pull/569 and https://github.com/Qiskit/documentation/pull/572, our extended check PR now checks more than simply external links. It also checks:
* that all pages render for translations and API docs
* the internal links for API docs
So, we should run these extended checks when we make changes to the API and translations folders.

Run extended checks on API updates

---

scripts/lib/sphinx/sphinxHtmlToMarkdown.ts

This PR is a follow-up from #584.
None of the logic is changed, only the control flow. This uses early returns to make it more clear how each distinct API type is handled. It also DRYs this code:
```typescript
const priorPythonApiType = meta.python_api_type;
if (!priorPythonApiType) {
meta.python_api_type = python_type;
meta.python_api_name = id;
}
```

Use early returns for sphinxHtmlToMarkdown member processing

---

scripts/lib/sphinx/sphinxHtmlToMarkdown.test.ts
scripts/lib/sphinx/sphinxHtmlToMarkdown.ts

Part of https://github.com/Qiskit/documentation/issues/223. There are still improvements we can make like better testing. 
This PR tries to avoid making code changes and only moves the code to helper functions.

Split sphinxHtmlToMarkdown into helper functions

---

scripts/lib/api/specialCaseResults.test.ts
scripts/lib/api/specialCaseResults.ts
scripts/lib/links/FileBatch.test.ts
scripts/lib/links/FileBatch.ts
scripts/lib/links/extractLinks.test.ts
scripts/lib/links/extractLinks.ts

This is prework for https://github.com/Qiskit/documentation/pull/522, which adds `sphinx.inv`. We want to check the links contained in `sphinx.inv`, but we don't expect anyone to have links pointing to `sphinx.inv`. 
Our original abstractions made it hard to model `objects.inv` correctly with the link checker. Now, `markdown.ts` is renamed to `extractLinks.ts` and it solely deals with parsing files. It no longer has a bad coupling to the complex `linksToOriginFiles` variable from `FileBatch.ts`. 
This should make it much more obvious how to handle `objects.inv`.

Make link extraction from markdown more explicit

---

scripts/commands/updateApiDocs.ts
scripts/lib/api/saveImages.ts
scripts/lib/sharedTypes.ts

Very minor refactor to move duplicated logic into its own function.
I added this to `sharedTypes.ts` to keep it next to the type it acts on. I considered making `Pkg` a class and having this as a method but it seemed to convolute the code a bit. Open to suggestions of neater ways to do this.

[Refactor] Move package path determination into own function

---

Dockerfile
README.md
scripts/commands/checkLinks.ts
scripts/lib/links/LinkChecker.ts
start

Turns out videos have always been supported! But we needed to:
1. Change our Docker images to load `public/videos`
2. Teach our link checker about videos
3. Document how to use them in the README
This unblocks https://github.com/Qiskit/documentation/pull/622. Example of that PR with this one applied:

Add support for videos

---

scripts/commands/updateApiDocs.ts
scripts/lib/api/HtmlToMdResult.ts
scripts/lib/api/htmlToMd.test.ts
scripts/lib/api/htmlToMd.ts
scripts/lib/api/processHtml.test.ts
scripts/lib/api/processHtml.ts
scripts/lib/api/saveImages.ts

We can simplify our image extraction code now that we copy images from the downloaded CI artifact rather than downloading it from a URL. Before, we stored `src` as a URL; now we just need the `fileName`.

Simplify image extraction code

---

scripts/commands/updateApiDocs.ts
scripts/lib/api/Pkg.ts
scripts/lib/api/addFrontMatter.test.ts
scripts/lib/api/generateToc.test.ts
scripts/lib/api/releaseNotes.ts
scripts/lib/api/saveImages.ts

To correctly generate source code links for Qiskit historical docs, we need complex logic to determine the `baseGithubUrl` because the versions between Qiskit and Qiskit Terra were different. Rather than putting that logic in `upsideApiDocs.ts`, it's cleaner to abstract it behind a method `Pkg.baseGithubUrl()`.
There are a few other methods that fit naturally on `Pkg`, rather than being free functions.
This also allows us to make the `Pkg` interface immutable. Before, we would build up the `Pkg` over time by modifying attributes. Now, every attribute is `readonly` and we set up everything in the constructor. That's useful because you no longer have to worry if you're dealing with a properly initialized `Pkg`; it will now always be properly initialized.

Refactor `Pkg` to be a class for API generation

---

scripts/commands/convertApiDocsToHistorical.ts

The API generation script is now able to work with `objects.inv` files thanks to @frankharkins at https://github.com/Qiskit/documentation/pull/522. This PR allows us to copy over the objects.file when we want to make a version historical running `npm run make-historical -- -p <projectName>`.

Extend make-historical script to use objects.inv

---

docs/api/qiskit/release-notes/0.43.md
scripts/lib/api/Pkg.ts
scripts/lib/links/ignores.ts

learn.qiskit.org recently stopped working so the redirects are failing, breaking CI on main.

Fix some broken learning links

---

scripts/commands/convertApiDocsToHistorical.ts
scripts/commands/updateApiDocs.ts
scripts/lib/api/Pkg.ts
scripts/lib/api/updateLinks.ts

This is meant to unblock regenerating the Qiskit API docs. But more generally, I think it's not a necessary feature to support for now. 
1. I've never seen a project's conf.py not point to latest
2. I'm not confident it even works with pointing to the correct subfoler. (That's ignorance - it might work!)
3. We can add this mechanism in the future whenever we want

Disable objects.inv for historical API docs

---

scripts/lib/api/Pkg.ts

This PR fixes the following link 'https://github.com/qiskit/qiskit-ibmq-provider/tree/stable/0.20/qiskit/providers/ibmq.py' found in the regeneration of Qiskit v0.42 at https://github.com/Qiskit/documentation/pull/658

Fix broken GitHub source link

---

scripts/lib/api/processHtml.ts

The `processHtml.ts` script assumes that we always have an `src` attribute in the `img` tags, and even though this is true for the latest API versions, for Qiskit historical versions, we can find cases like the following example:
**Qiskit v0.41 release_notes.html line 23360**
```html
<div class="animation">
<div class="anim-controls">
<input id="_anim_slidera6548212aea7457ca5d2f940fabeaea3" type="range" class="anim-slider"
```
This PR adds an early return to the `loadImage` function to skip the images without a `src` attribute given that we can't find the image in the `_images` folder of the GitHub artifact.

API generation script - Fix loadImages function

---

scripts/lib/api/Pkg.test.ts
scripts/lib/api/Pkg.ts

This PR extends the generation script to handle GitHub source links for the API docs starting with` qiskit/chemistry`, `qiskit/finance`, `qiskit/ml`, and `qiskit/optimization` as part of qiskit-aqua.
Regeneration tested at https://github.com/Qiskit/documentation/pull/684

Fix qiskit-aqua GitHub source links

---

scripts/lib/api/Pkg.ts

We can't access the file `qiskit/optimization/converters/quadratic_program_to_negative_value_oracle` using the `stable/0.7` branch because the file was removed at patch 0.7.4. Instead, we need a special case to access the file using the tag 0.7.3

GitHub source link by tag: special case

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/user-feedback.yml

Adding the  "content 📄" label to the bug and user-feedback issue templates so that they will be included in a sort of all content-related issues.

Add content label to bug and user-feedback templates

---

docs/api/qiskit/algorithms.md
docs/api/qiskit/circuit.md
docs/api/qiskit/dagcircuit.md
docs/api/qiskit/exceptions.md
docs/api/qiskit/extensions.md
docs/api/qiskit/opflow.md
docs/api/qiskit/passmanager.md
docs/api/qiskit/providers.md
docs/api/qiskit/pulse.md
docs/api/qiskit/qasm2.md
docs/api/qiskit/qasm3.md
docs/api/qiskit/qpy.md
docs/api/qiskit/transpiler.md
docs/api/qiskit/visualization.md
scripts/lib/api/processHtml.test.ts
scripts/lib/api/processHtml.ts

Quick fix to use the same logic for functions and exceptions. Closes #712.
A known problem with this implementation is that some headings should not be `h3`, but it depends on the page. See https://github.com/Qiskit/documentation/issues/714.

Add headers for exceptions

---

docs/start/install.mdx

Thanks @javabster for calling out the broken show/hide section for Release Schedule on the start/install page. Restoring the content here.

Restore missing content from install page show/hide section

---

scripts/lib/api/htmlToMd.test.ts
scripts/lib/api/htmlToMd.ts

This PR changes how we handle pipes inside math expressions when we convert sphinx HTML into markdown. Some math expressions use pipes to define quantum states using the Dirac notation, and we need to escape those characters to avoid breaking the page when the pipe characters are used inside a markdown table.
One solution could only handle the `|` characters used inside a table, but given that the math expressions could be used in nested tags (e.g `<td> <p> <span class="math"> SOME_EXPRESSION </span></p></td>`), and would need to make the script more complex without ensuring we fix all the cases where we could make the page to fail to render, I decided to handle that character differently in all math expressions.
The PR replaces the `|` character with `\vert ` which will represent the …

Improve the API script to handle `|` characters

---

docs/start/install.mdx

This commit updates the isntall guide to point to a more permenant location on where to find the supported python versions for a release. Previously the guide pointed people to setup.py on github. This was problematic for two reasons, first the supported version information isn't present there anymore as we moved to using the pyproject.toml file to contain all the static metadata about the project, second the data on main refers to the next release not the current one. Instead this commit points people to project page on PyPI which is where the metadata from the previous location gets hosted for each release. This is the cannonical source for which python versions are supported of any given Qiskit release (or the corresponding metadata in the package file itself).

Update details on finding the supported Python versions

---

scripts/nb-tester/test-notebook.py

The `transpiler-stages` notebook is broken, but will be tested in CI any time someone edits it (even if just changing copy etc.). This breaks PRs that are perfectly fine.
This PR ignores excluded files completely. I also took the opportunity to:
- improve the code readability somewhat (i.e. less `path for path in paths if path`),
- print a message when notebooks are skipped, otherwise someone running `tox` locally might believe their notebook was fine even though it never ran.

Improve file filtering in CI

---

docs/api/migration-guides/qiskit-1.0.mdx

This fixes a missing space in the title metadata, and copies the tip about the `qiskit-terra` constraints file down to the bottom of the page as well as the top. It's a good tip (thanks to Will!), and some of Qiskit's error messages link directly to the bottom of the page.
I pushed this branch to the Qiskit remote this time, since that seems to be what everyone else does, and the preview site seemed to need it.

Fix title and final section of Qiskit 1.0 packaging migration

---

scripts/nb-tester/test-notebook.py

Was reporting warnings as `<class 'str'>`, which wasn't very helpful.
See https://github.com/Qiskit/documentation/actions/runs/7745198894/job/21120640259 for an example.

Fix bug in notebook tester

---

scripts/commands/updateApiDocs.ts

Some historical versions don't have the `_images` folder in the artifact store in Box (https://ibm.ent.box.com/folder/246867452622), and we don't want the script to fail when trying to save them, especially in the automatic regeneration.

API generating script: historical images

---

scripts/lib/api/processHtml.ts

Old releases of Qiskit used "Methods Defined Here" instead of "Methods" as a title for the methods section. We need to check for the former in order to inline correctly the methods when generating the API docs.

Fix inlining methods for qiskit historical versions

---

docs/api/qiskit/0.24/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.24/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.25/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.25/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.25/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.26/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.26/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.26/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.27/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.27/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.27/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.28/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.29/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.30/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.31/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.32/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.33/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.35/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.35/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.36/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.36/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.37/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.38/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/0.39/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
docs/api/qiskit/release-notes/0.45.md

This PR fixes bad latex expressions for all Qiskit API docs versions thanks to @kevinsung's fix
Part of https://github.com/Qiskit/documentation/issues/673.

Fix bad Latex for all Qiskit API docs versions

---

scripts/commands/checkPagesRender.ts

It's nice that we eagerly load failures while the script is still running because it can be really slow to run so that gets you feedback sooner. But right now it's too hard to get the final list of failures at the end.

Make output more useful for pages failing to render

---

docs/api/qiskit/0.19/qiskit.aqua.QuantumInstance.md

This PR regenerates the qiskit 0.19 API docs.
QuantumInstance had two HTML for some properties where a file in ALL_CAPS defined the property itself and another file in lowercase was the getter. Our script, when run on case-insensitive operating systems like macOS, wasn't able to download both files, and we ended up losing the getters.
The artifact stored on Box (https://ibm.ent.box.com/folder/246867920686) was modified to preserve all the getters and remove the properties.
Closes #769

Regenerate Qiskit 0.19 QuantumInstance

---

.github/workflows/extended-checks.yml

Sometimes the link checker fails due to flakes. It's annoying that that means the page render check won't run.

Always check if pages render in extended CI check

---

.github/workflows/learning-uploader-test.yml

Fixes a couple of quirks discovered during #760.
- Fixed job skipping when run as `workflow_dispatch`
- Fixed link to logs in issue body

Tweak learning-uploader test action

---

docs/api/qiskit/0.19/qiskit.circuit.library.PauliFeatureMap.md
docs/api/qiskit/0.19/qiskit.quantum_info.OneQubitEulerDecomposer.md
docs/api/qiskit/0.19/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.19/qiskit.quantum_info.purity.md
docs/api/qiskit/0.24/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.24/qiskit.quantum_info.concurrence.md
docs/api/qiskit/0.25/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.25/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.25/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.26/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.26/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.26/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.27/qiskit.circuit.library.LinearAmplitudeFunction.md
docs/api/qiskit/0.27/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.27/qiskit.quantum_info.process_fidelity.md
docs/api/qiskit/0.28/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.29/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.30/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.31/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.32/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.33/qiskit.quantum_info.Pauli.md
docs/api/qiskit/0.35/qiskit.quantum_info.Pauli.md

Part of https://github.com/Qiskit/documentation/issues/673.
This follows up on https://github.com/Qiskit/documentation/pull/763. While it fixed legit Latex issues, it introduced new problems because the HTML was autoformatted, which broke other math snippets.
This change was implemented entirely by changing the folder in Box as follows:
1. Used the latest folders as the base
2. Downloaded our original copies of the folders and replaced the failing files with these original copies
3. Manually fixed the bad HTML that was fixed in #763 
4. Uploaded the zip files and re-generated the docs
This also fixes 0.19 issues, which were never fixed in #763.

Fix Latex errors from bad HTML formatting

---

.github/workflows/extended-checks.yml
README.md
scripts/commands/checkLinks.ts
scripts/commands/checkPagesRender.ts
scripts/commands/updateApiDocs.ts
scripts/lib/api/Pkg.ts
scripts/lib/api/saveImages.ts

This PR adds support to generate dev versions for the API generation script.
For the moment, the automatic regeneration will not take into account dev versions to keep this PR easy to review. I'll add support for that in a follow-up, together with the documentation of the dev versions.
Part of #316

Extend the API generation script to generate dev versions

---

scripts/api-html-artifacts.json
scripts/lib/api/apiArtifacts.ts

Part of #316 
This PR adds the artifacts for the dev versions of qiskit and qiskit-ibm-runtime and fixes how we read the JSON file to take into account the new names of the artifacts.

API generation script uses correct artifact names

---

scripts/commands/regenerateApiDocs.ts

Part of #316 
This PR extends the API automatic regeneration script to regenerate dev versions. When using the `npm run regen-apis` command, the script will read the `_package.json` from the `dev` folder if it exists and regenerate that version as the last one of the package.

Extend the `regen-apis` command to regenerate dev versions

---

scripts/lib/links/FileBatch.ts
scripts/lib/links/LinkChecker.test.ts
scripts/lib/links/LinkChecker.ts

Closes https://github.com/Qiskit/documentation/issues/749. Now we focus the message around the broken link.
Before:
```
❌ docs/api/qiskit/release-notes/0.15.md: Could not find link '/api/qiskit/qiskit.quantum_info.OneQubitEulerDecomposer' ❓ Did you mean '/api/qiskit/qiskit.synthesis.OneQubitEulerDecomposer'?
❌ docs/api/qiskit/release-notes/0.18.md: Could not find link '/api/qiskit/qiskit.quantum_info.OneQubitEulerDecomposer' ❓ Did you mean '/api/qiskit/qiskit.synthesis.OneQubitEulerDecomposer'?
```
After:
```
❌ Could not find link '/api/qiskit/qiskit.quantum_info.OneQubitEulerDecomposer'
docs/api/qiskit/release-notes/0.15.md    ❓ Did you mean '/api/qiskit/qiskit.synthesis.OneQubitEulerDecomposer'?
docs/api/qiskit/release-notes/0.18.md    ❓ Did you mean …
```

Deduplicate link checker error messages

---

README.md
scripts/commands/checkMetadata.ts

Closes https://github.com/Qiskit/documentation/issues/793. 
This unblocks us starting to check API docs in https://github.com/Qiskit/documentation/issues/66. It also speeds up the workflow for non-API docs, which is valuable because non-API and API docs have such different workflows.
I only added an `--apis` argument rather than e.g. `--current-apis` vs `--historical-apis` because this check is fast enough to not need the nuance.

Don't check metadata for API docs by default

---

.github/workflows/api-checks.yml
scripts/lib/links/FileBatch.ts
scripts/lib/links/ignores.ts

This adds the idea of "always ignored URLs", rather than making us repeat every file in which the URL appears. That has become necessary now that we have dev and historical API docs.
This PR also removes some stale ignores.

Better organize link checker ignores

---

docs/start/install.mdx

* Mention a few non-supported modes (FreeBSD, WebAssembly, PyPy) by name so they come up more easily for someone searching for them.
* Fix typo (missing "be").
* Downgrade confidence that Qiskit will work on other platforms
* Expand reference to CPython

Update platform support description

---

scripts/lib/api/processHtml.test.ts
scripts/lib/api/processHtml.ts

Part of https://github.com/Qiskit/documentation/issues/517. Turns out that we already do the right thing! That's because both `sphinx.ext.viewcode` and `sphinx.ext.linkcode` use the same HTML structure.
This PR adds tests and better comments to make that clear.
The key insight is that we don't need to change the URLs at all, unlike using `sphinx.ext.viewcode`. We assume the source repositories are giving us valid URLs.

Add tests showing that `sphinx.ext.linkcode` can be handled

---

.github/workflows/api-checks.yml
scripts/lib/links/FileBatch.ts
scripts/lib/links/ignores.ts

The API checks didn't run in https://github.com/Qiskit/documentation/pull/850 because our GitHub Action didn't include `public/api` in its globs. So, we accidentally broke the link checker.
This PR adds the new mechanism of `IGNORED_FILES`. The `objects.inv` has way too many errors in 0.14 - 0.16 to be worth trying to fix or blocklist specific failures.
Finally, it removes ignores that are now stale thanks to https://github.com/Qiskit/documentation/pull/848.

Fix link checker for historical objects.inv files

---

docs/api/qiskit/0.41/providers_fake_provider.md
docs/api/qiskit/0.41/qiskit.algorithms.linear_solvers.LinearSystemMatrix.md
docs/api/qiskit/0.41/qiskit.algorithms.linear_solvers.NumPyMatrix.md
docs/api/qiskit/0.41/qiskit.algorithms.linear_solvers.TridiagonalToeplitz.md
docs/api/qiskit/0.41/qiskit.circuit.Parameter.md
docs/api/qiskit/0.41/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.41/qiskit.transpiler.passes.DynamicalDecoupling.md
docs/api/qiskit/0.41/qiskit.transpiler.passes.PadDynamicalDecoupling.md
docs/api/qiskit/0.41/qiskit.visualization.plot_distribution.md
docs/api/qiskit/0.41/qiskit.visualization.plot_histogram.md
docs/api/qiskit/0.42/providers_fake_provider.md
docs/api/qiskit/0.42/qiskit.algorithms.linear_solvers.LinearSystemMatrix.md
docs/api/qiskit/0.42/qiskit.algorithms.linear_solvers.NumPyMatrix.md
docs/api/qiskit/0.42/qiskit.algorithms.linear_solvers.TridiagonalToeplitz.md
docs/api/qiskit/0.42/qiskit.circuit.Parameter.md
docs/api/qiskit/0.42/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.42/qiskit.transpiler.passes.DynamicalDecoupling.md
docs/api/qiskit/0.42/qiskit.transpiler.passes.PadDynamicalDecoupling.md
docs/api/qiskit/0.42/qiskit.visualization.plot_distribution.md
docs/api/qiskit/0.42/qiskit.visualization.plot_histogram.md
scripts/lib/api/processHtml.test.ts
scripts/lib/api/processHtml.ts

Follow up to https://github.com/Qiskit/documentation/pull/848. Sphinx used to use a different HTML structure we weren't accounting for.
After this PR, there are no more bad URLs:
```
❯ rg '_downloads' -l
scripts/lib/api/htmlToMd.test.ts
scripts/lib/links/ignores.ts
scripts/lib/api/processHtml.test.ts
```

Remove old style of Matplotlib figures

---

qiskit_bot.yaml

Adds usernames for each file, escaping based on their notification preferences.

Add names to Qiskit bot

---

docs/api/qiskit/0.38/aer_primitives.md
docs/api/qiskit/0.39/aer_primitives.md
docs/api/qiskit/0.40/aer_primitives.md
docs/api/qiskit/0.41/aer_primitives.md
docs/api/qiskit/0.42/aer_primitives.md
scripts/commands/updateApiDocs.ts
scripts/lib/api/Pkg.ts
scripts/lib/api/objectsInv.ts
scripts/lib/api/updateLinks.test.ts
scripts/lib/api/updateLinks.ts

This is prework for https://github.com/Qiskit/documentation/issues/493 to relativize links to docs.quantum.ibm.com. 
This refactors the code that we'll be modifying:
* Always applies the link transformation, whereas before it wasn't used on Qiskit.
* renames `updateUrl` to `normalizeUrl`
* renames `transformLink` to `relativizeLink`
* adds tests for `relativizeLink`

Refactor how we relativize links to qiskit.org

---

.gitignore
scripts/commands/updateApiDocs.ts
scripts/lib/api/Pkg.ts
scripts/lib/api/sphinxArtifacts.ts

Before: `.out/python/sources/qiskit/0.40.0`
After: `.sphinx-artifacts/qiskit/0.40`
We weren't storing anything else in `.out`, so there was no need to have those subfolders.
It also isn't necessary to put the patch version in the folder name since we only ever have one patch per minor release.

Store Sphinx artifacts in a less verbose location

---

scripts/commands/checkLinks.ts
scripts/lib/links/ExternalLink.test.ts
scripts/lib/links/ExternalLink.ts
scripts/lib/links/FileBatch.ts
scripts/lib/links/InternalLink.test.ts
scripts/lib/links/InternalLink.ts
scripts/lib/links/extractLinks.ts

We decided as part of https://github.com/Qiskit/documentation/issues/876 that we should have distinct programs for checking internal vs external links, since they are such distinct workflows.
This PR is a refactor to prepare for that change. The link checker program still behaves the same as before; this is only a refactor.

Split out `InternalLink` and `ExternalLink` classes

---

scripts/commands/checkLinks.ts
scripts/lib/links/ExternalLink.ts
scripts/lib/links/FileBatch.test.ts
scripts/lib/links/FileBatch.ts
scripts/lib/links/InternalLink.test.ts
scripts/lib/links/InternalLink.ts
scripts/lib/links/extractLinks.test.ts
scripts/lib/links/extractLinks.ts

Part of https://github.com/Qiskit/documentation/issues/876 to split the internal and external link checkers into distinct programs. To do this, it's useful to split out internal vs. external links at parse time, whereas before we did it inside `FileBatch`. The external link checker won't use `FileBatch`.
This is only a refactor and doesn't change the program, other than now using `HEAD` for external link requests rather than `GET`. We also now use a `Set` for anchors so that checking if an anchor is included is faster.

Determine internal vs external links at parse time

---

scripts/commands/checkLinks.ts

Fixes a bug in https://github.com/Qiskit/documentation/pull/881. It handled `--qiskit-release-notes` correctly, but it incorrectly would skip `--historical-apis` for Qiskit versions before 0.45.
This also loads fewer files for the migration guides.

Fix logic for checking historical Qiskit docs

---

docs/api/migration-guides/qiskit-1.0-features.mdx
docs/api/migration-guides/qiskit-1.0.mdx
docs/api/migration-guides/qiskit-algorithms-module.mdx
docs/api/migration-guides/qiskit-opflow-module.mdx
docs/build/circuit-construction.ipynb
docs/build/interoperate-qiskit-qasm2.mdx
docs/build/interoperate-qiskit-qasm3.mdx
docs/build/qasm-feature-table.mdx
docs/run/configure-error-mitigation.mdx
docs/run/configure-runtime-compilation.mdx
docs/run/primitives-examples.mdx
docs/run/primitives-get-started.mdx
docs/run/quantum-serverless.mdx
docs/run/run-jobs-batch.mdx
docs/run/run-jobs-in-session.mdx
docs/run/sessions.mdx
docs/start/configure-qiskit-local.mdx
docs/start/index.mdx
docs/transpile/defaults-and-configuration-options.mdx
docs/transpile/index.mdx
docs/transpile/set-optimization.mdx
docs/transpile/transpiler-stages.ipynb
docs/verify/index.mdx
docs/verify/simulate-with-qiskit-primitives.mdx
docs/verify/stabilizer-circuit-simulation.ipynb
scripts/commands/checkMetadata.ts

enforce 50 <= description length <= 160

---

docs/api/qiskit/0.33/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.35/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.35/utils.md
docs/api/qiskit/0.36/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.36/utils.md
docs/api/qiskit/0.37/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.37/utils.md
docs/api/qiskit/0.38/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.38/utils.md
docs/api/qiskit/0.39/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.39/utils.md
docs/api/qiskit/0.40/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.40/utils.md
docs/api/qiskit/0.41/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.41/utils.md
docs/api/qiskit/0.42/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.42/utils.md
docs/api/qiskit/0.43/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.43/utils.md
docs/api/qiskit/0.44/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.44/utils.md
docs/api/qiskit/0.45/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.45/utils.md
docs/api/qiskit/0.46/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/0.46/utils.md
docs/api/qiskit/dev/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/dev/utils.md
docs/api/qiskit/qiskit.circuit.QuantumCircuit.md
docs/api/qiskit/utils.md
scripts/lib/api/processHtml.ts

Closes #167
The script was creating a title for every `<dt>` tag inside a `<dl>` tag. This is almost always correct given that we only have a `<dt>` tag for each method. The problem with overload methods is that we have a `<dt>` for each `@typing.overload` definition.
For example, the `quantumcircuit.py` file overloads the definition of for_loop:
https://github.com/Qiskit/qiskit/blob/244940a10c17f1dc3d74e2665a3ae869dc3d7291/qiskit/circuit/quantumcircuit.py#L4862-L4884
This is an example of the HTML generated
```html
<dl class="py method">
<dt class="sig sig-object py" id="qiskit.circuit.QuantumCircuit.for_loop">
<span class="sig-name descname"><span class="pre">for_loop</span>
<dt class="sig sig-object py">
<span class="sig-name descname"><span class="pre">for_loop</span>
<dd><p>Create a …
```

Deduplicate headers for overloaded methods

---

.github/workflows/notebook-test.yml
README.md
scripts/nb-tester/requirements.txt
tox.ini

Closes https://github.com/Qiskit/documentation/issues/838.
Replaces the message in CI with correct instructions for our repository. I've added a switch to remove the advice from the printed message, I think this is the neatest net logic change: https://github.com/frankharkins/squeaky/commit/33e24f8eb633d25758c787c4efd5d645458c352f.
See https://github.com/frankharkins/documentation/pull/2 for the test PR.
This doesn't display the message when running `tox -e lint`, but I think it's unlikely a contributor would run that command locally without first encountering it in CI.

Replace Squeaky CI advice with custom advice

---

scripts/commands/checkMetadata.ts

Follow up to https://github.com/Qiskit/documentation/pull/890. API docs are auto-generated so we can't easily fix if the line length is not ideal, which often happens from being too short.

Metadata line length check ignores API docs

---

scripts/lib/api/htmlToMd.ts

Part of #845
This is the first refactor of `htmlToMd.ts`. It brings the following changes:
- New function named `buildMathExpression` to build math expressions whether they are inlined or not
- New function named `removeEmphasisSpaces` to remove the initial and trailing spaces in an emphasis node
- The Unified plugin and the creation of the handlers for it were separated into two functions. The unified plugin was inlined into `generateMarkdownFile`

Refactor htmlToMd.ts

---

scripts/ibm-quantum-learning-uploader/src/learning_uploader/upload.py
scripts/ibm-quantum-learning-uploader/test/assert-string-on-page.py
scripts/ibm-quantum-learning-uploader/test/e2e-test.sh
scripts/ibm-quantum-learning-uploader/test/learning-api.conf.yaml

The logic that calculates the URL to display to the user expects the page to belong to a course. This crashes when uploading a tutorial as tutorials don't belong to a course.
This PR fixes that and updates the e2e test to include a tutorial page.
***
Resolves #799

Fix learning uploader to handle tutorials

---

scripts/lib/api/htmlToMd.ts

Part of #845
This PR refactors the `htmlToMd.ts` script. It splits the `prepareHandlers` function into some helper functions to simplify the logic and improve the readability.

Refactor `htmlToMd.ts`: Split `prepareHandlers` function

---

README.md
start

It's confusing when `./start` diverges from `docs.quantum.ibm.com`.
We now warn every time when running `./start`:
```
❯ ./start 
Warning: this may be using an outdated version of the app. Run `docker pull qiskit/documentation` to check for updates.
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
▲ Next.js 14.0.1
- Local:        http://f9e8103d2cee:3000
- Network:      http://172.17.0.2:3000
✓ Ready in 1377ms
[remoteRefresh] server is listening at port 5001
```
I debated always running `docker pull qiskit/documentation` automatically, but I think it's too slow and annoying.

Document how to pull in new versions of preview

---

scripts/commands/updateApiDocs.ts
scripts/lib/api/conversionPipeline.ts

This is a refactor to unblock the new integration test in https://github.com/Qiskit/documentation/issues/715. We need to test the conversion pipeline, so its code needs to live in `lib` not `commands`.
I renamed the function `convertHtmlToMarkdown` to instead `runConversionPipeline` and moved it to `conversionPipeline.ts`. I didn't want the phrase "html to markdown" because because we already have `htmlToMd.ts`; this pipeline does way more than convert HTML to markdown, such as also copying image files and inlining methods into classes.
This PR also refactors the rest of `updateApiDocs.ts` via helper functions. A follow up will refactor `conversionPipeline.ts`.

Split out `conversionPipeline.ts` from `updateApiDocs.ts`

---

scripts/lib/api/conversionPipeline.ts

Uses helper functions and better groups code to make it easier to read. Should be the same behavior.

Refactor release notes logic in `conversionPipeline.ts` 

---

.gitattributes
README.md

This PR adds instructions on setting up Git to use [`sphobjinv`](https://github.com/bskinn/sphobjinv) to display diffs for `objects.inv`.
Since `objects.inv` is compressed, we can't review changes through `git diff`. Git _does_ tell you if the file has changed, but this isn't that helpful as the compressed file can be different even if the uncompressed contents are the same.
Git will default back to binary diff if it doesn't find a rule in `.gitconfig` so adding `.gitattributes` shouldn't disrupt contributors that don't follow the guide.
Hopefully this information will help keep more eyes on the file and spot any unintended changes.
Here's an example of it in action (downgrading qiskit to 0.46):

Add .gitattributes and guide for diffing objects.inv

---

scripts/lib/api/processHtml.ts

This PR splits the `processMembersAndSetMeta` function from the `processHtml.ts` script into several helper functions to process each `apiType`.
These changes are done to the `map()` used to create the `replacement` variable (line 291). The map used to have all the logic to process each child depending on its `apiType`. Now the map starts by early returning in the case we are not processing a `<dt>` tag and calling to a new helper function to process an individual child.
Before the `map()` was setting the metadata, the refactor moved the code outside of it, given that the metadata doesn't depend on the elements iterated.
The new helper function is called `processMember` and starts by preparing the GitHub source link, removing the `apiType` from the `em.property` selector, and calling …

Split `processMembersAndSetMeta` function into helper functions

---

scripts/lib/api/conversionPipeline.ts

This PR fixes the order of the operations we are doing in `conversionPipeline.ts`. The important change is to call `maybeUpdateReleaseNotesFolder` before `writeTocFile`. This is because, in the former, we call to `addNewReleaseNotes`, which modifies the `_toc.json` file that we write in the latter.

Fix sequence of operations in `conversionPipeline.ts`

---

docs/api/qiskit/0.19/_toc.json
docs/api/qiskit/0.24/_toc.json
docs/api/qiskit/0.25/_toc.json
docs/api/qiskit/0.26/_toc.json
docs/api/qiskit/0.27/_toc.json
docs/api/qiskit/0.28/_toc.json
docs/api/qiskit/0.29/_toc.json
docs/api/qiskit/0.30/_toc.json
docs/api/qiskit/0.31/_toc.json
docs/api/qiskit/0.32/_toc.json
docs/api/qiskit/0.33/_toc.json
docs/api/qiskit/0.35/_toc.json
docs/api/qiskit/0.36/_toc.json
docs/api/qiskit/0.37/_toc.json
docs/api/qiskit/0.38/_toc.json
docs/api/qiskit/0.39/_toc.json
docs/api/qiskit/0.40/_toc.json
docs/api/qiskit/0.41/_toc.json
docs/api/qiskit/0.42/_toc.json
docs/api/qiskit/0.43/_toc.json
docs/api/qiskit/0.44/_toc.json
docs/api/qiskit/0.45/_toc.json
docs/api/qiskit/0.46/_toc.json
docs/api/qiskit/_toc.json
docs/api/qiskit/dev/_toc.json
scripts/lib/api/Pkg.ts

This is to better clarify the word "Qiskit". This changes what shows up in the left ToC.
Change was generated with `rg '"title": "Qiskit",' -l | xargs sd '"title": "Qiskit",' '"title": "Qiskit SDK",'`

Call Qiskit API docs "Qiskit SDK"

---

scripts/lib/api/htmlToMd.test.ts

Part of  #845
This PR creates more sections for the `htmlToMd.test.ts` and merges some tests.
- Merged `parse inline attributes section` and `convert method and attributes to titles and handle inlined methods` into `handle inlined methods and attributes`
- Merged `handle <` and `handle {` into `handle special characters: < and {`.
- Created three new sections to classify some tests:
1. Transform methods and attributes
2. transform description HTML tags
3. transform admonitions

Create more sections for `htmlToMd.test.ts` and merge tests

---

docs/start/index.mdx

Point [here](https://www.ibm.com/quantum/blog?topic=qiskit) instead of to Medium.

update the blog link on the start/index page

---

docs/run/primitives-get-started.mdx

- Removes unnecessary tabs
- Reword some sentences for clarity
- Move V2 explanatory prose outside of tabs so that it's easier to see the difference between the tabs when switching between them.

Fix tabs and improve prose of primitives-get-started

---

scripts/lib/api/processHtml.ts

Reverts the order changes when we set the metadata introduced by #954. It turned out that setting the metadata outside the `map()` adds some duplicated `<span>` tags for qiskit legacy versions. This PR moves the code back to where it originally was.

Fix `processHtml.ts` metadata

---

scripts/lib/api/generateToc.test.ts
scripts/lib/api/generateToc.ts

This PR refactors the `generateToc.ts` script splitting out the `generateToc` function into some helper functions. It also removes the if condition to check if the length of the modules is greater than 0 because it's not necessary.
The PR added a test to check the latter, and it was tested regenerating every qiskit and provider versions.

Split `generateToc` into helper functions

---

scripts/commands/checkPagesRender.ts

Closes https://github.com/Qiskit/documentation/issues/998. Before this PR, new folders like `docs/analyze` would not be included in `npm run check:pages-render -- --non-api`.

Future proof pages render check for new Patterns folders

---

docs/build/interoperate-qiskit-qasm2.mdx

This finishes off the guide to interoperation with OpenQASM 2, including more tutorial-like versions of how to work with custom quantum and classical instructions, specific instructions on how to import programs created by the (to-be-fixed) exporter, and how to export programs to OpenQASM 2.
Close #240.

Complete OpenQASM 2 interoperation guide

---

.github/workflows/code-engine-preview.yml
.github/workflows/preview-docs.yml
.github/workflows/staging.yml
docs/start/index.mdx

This is the only repository still using https://github.com/Qiskit/gh-actions, so we can inline its logic and then archive the repository. That allows us to make the workflow file less generic and remove some indirection. It simplifies the overall infrastructure.
I think PR previews might have been broken for a while, but I want to address this in a follow up. https://github.com/Qiskit/documentation/issues/1034

Inline `qiskit/gh-actions`

---

scripts/commands/checkOrphanPages.ts

Closes #1014 
In the interest of readability, the list of allowed urls includes pages that don't exist.  There is a small risk of a false positive if there are any new pages that get added to the api docs of the same name which should actually be checked against their toc instead of ignored.

Add API entries to allowed urls

---

docs/api/migration-guides/qiskit-1.0-features.mdx

The migration guide of qiskit 1.0 has some mistakes about SamplerV2 result.
- Method name: `get_bitstring` -> `get_bitstrings`
- This method returns a list of bitstrings not an ndarray.
Note: If you want to access the shape, you can do it by `data_pub.meas.array.shape`.

Fix a code about `get_bitstrings`

---

scripts/nb-tester/requirements.txt
tox.ini

The linting instructions are actually lies as they you should run `tox -e fix` but this doesn't work unless you pass the files as a posarg. This PR bumps the version of Squeaky to one that supports recursive searching and sets a default posarg of `docs/` so writers can just run `tox -e fix` to clean everything.

Add default posarg to tox.ini

---

README.md
start

The recently released Preview docker image now has a home page, so `localhost:3000` no longer 404s. It acts like a table of contents.
(Users need to run `docker pull qiskit/documentation` to pull in this change.)

Update instructions for preview now that there's a home page

---

scripts/commands/checkPagesRender.ts

Missed in https://github.com/Qiskit/documentation/pull/1054. `localhost:3000` should now be a 200, not 404.

Fix pages render check

---

docs/run/primitives-examples.mdx

Closes #1063 
Instantiate `service` and `backend` before using them in the `generate_preset_pass_manager`. The update is done for the tab item `SamplerV1` and tab item `SamplerV2`

reorder service and backend instantiation for primitive examples

---

README.md

We have a couple more features available via cell tags. See diff for an explanation.

Add new cell tag features to README

---

scripts/api-html-artifacts.json

The links expired in Box and I created two new ones

Update artifact shared links for runtime 0.22 and dev

---

scripts/lib/links/extractLinks.test.ts
scripts/lib/links/extractLinks.ts

This small PR changes the regex used in the link checker to parse the anchors for a non-greedy version of it. After regenerating the API docs with the mdx components, our link checker wasn't able to detect the id from them that we previously had as `<span>` tags.
The problem was how the script was searching for the ids. In the the following screenshots, we can see the change introduced here.
**Before**
**After**
More information on the non-greedy quantifier here: https://www.ibm.com/docs/en/netcoolomnibus/8.1?topic=library-minimal-non-greedy-quantifiers
To see that it fixed the issue, this change was applied to ##1094, #1101, and #1102

Link checker: use the non-greedy quantifier to parse anchors

---

scripts/lib/api/conversionPipeline.ts

This reverts commit 3f151c3df9012b5ce5f2fbc08bf745487ba4e313.
Instead, we fixed by switching Runtime to Towncrier.

Revert "Work around Reno release notes issue with Runtime (#980)"

---

.gitignore
README.md
scripts/nb-tester/requirements.txt

Also explain what to install to get the notebooks working locally. Tested on macOS Apple Silicon. The Linux requirements come from CI but weren't tested locally.

Upgrade Aer to 0.14

---

docs/run/run-jobs-batch.mdx

Update batch example

---

docs/api/migration-guides/qiskit-algorithms-module.mdx
docs/api/migration-guides/qiskit-opflow-module.mdx
docs/verify/simulate-with-qiskit-aer.ipynb
docs/verify/stabilizer-circuit-simulation.ipynb

After Aer .14 is released, remove approximation=true from relevant pages

---

docs/build/_toc.json

The circuit basics page is introductory, such as defining what a circuit is. It makes more sense to present before the circuit library. That follows our Qiskit 101 presentation structure.

Present circuit basics before circuit library

---

.github/workflows/notebook-test-cron.yml

We run notebooks that submit jobs twice a month to check they don't raise errors, but we currently throw away the results. This PR uploads the executed notebooks as an artifact so we can inspect the outputs and update the files in this repo with more recent output.
See https://github.com/Qiskit/documentation/actions/runs/8645293171 for an example of this working.

Upload artifacts from cron job

---

.github/workflows/notebook-test.yml
scripts/nb-tester/requirements.txt
scripts/nb-tester/test-notebook.py
tox.ini
tutorials/build-repitition-codes/notebook.ipynb
tutorials/chsh-inequality/notebook.ipynb
tutorials/explore-composer/notebook.ipynb
tutorials/grovers-algorithm/notebook.ipynb
tutorials/quantum-approximate-optimization-algorithm/notebook.ipynb
tutorials/repeat-until-success/notebook.ipynb
tutorials/submitting-transpiled-circuits/notebook.ipynb
tutorials/variational-quantum-eigensolver/notebook.ipynb

Adds the new tutorial notebooks to the same tests as the documentation notebooks. Most tutorials run jobs on IBM Quantum so will only be tested fortnightly in the cron job workflow.
Part of #1136

Add tutorials to notebook tests

---

scripts/nb-tester/test-notebook.py

I didn't realise `Path.rglob` doesn't support braces expansion. Instead, we just avoid hidden folders (there are a bunch of notebooks from libraries in `.tox/**`).

Fix globs in nb-tester

---

scripts/nb-tester/test-notebook.py

Fix oversight in #1160. This notebook no longer submits jobs so can be removed from the list.

Update notebook test list

---

docs/api/qiskit-ibm-provider/0.10/_toc.json
docs/api/qiskit-ibm-provider/0.7/_toc.json
docs/api/qiskit-ibm-provider/0.8/_toc.json
docs/api/qiskit-ibm-provider/0.9/_toc.json
docs/api/qiskit-ibm-provider/_toc.json
docs/api/qiskit-ibm-provider/release-notes.mdx
docs/api/qiskit-ibm-runtime/release-notes.mdx
scripts/lib/api/Pkg.ts
scripts/lib/api/conversionPipeline.ts

We're also changing other parts of the UI like the API dropdown in the top nav bar. This will change the left ToC here:
This PR also removes the version number from the H1 for the release notes for Runtime and Provider to no longer have the version number in them. That didn't make sense to do because they're the same release notes for all versions.

Indicate IBM Provider is deprecated in left navbar

---

scripts/nb-tester/requirements.txt
scripts/nb-tester/test-notebook.py

Notebooks were tested locally with `tox`. Everything succeeded except for `save-jobs.ipynb` because it doesn't work with other users' accounts.

Upgrade Runtime and Provider for notebook testing

---

.github/actions/set-up-notebook-testing/action.yml
tox.ini

We currently test everything with Python 3.11, but this is a problem as not all writers have it available on their system. We also want to make sure our docs work with as many versions of Python as possible.
This PR allows writers to test their docs with any version of Python, and sets CI to test with Python 3.8 (the minimum version that Qiskit supports).

Change how we specify Python versions for testing

---

.github/actions/set-up-notebook-testing/action.yml

Fixes https://github.com/Qiskit/documentation/pull/1207. We use `list[str]` in type hints rather than `List[str]`, which was only added in Python 3.9. So it broke CI.
Python 3.9 is fine as a floor, given that Python 3.12 is newest.

Fix Python version in CI

---

docs/run/save-jobs.ipynb

This page originally submitted a simple job using the cloud simulator as a demonstration. Since the simulators are being deprecated, #1160 removed the job-submitting step and hardcoded the `job_id` into the notebook. This was a bad idea because it means the notebook breaks if not run with my IBM Quantum account.
This PR reorganises the page to get `job_id` programatically first. This lets us avoid hardcoding the `job_id` in the notebook, which means we can run the notebook with any IBM account that has submitted at least one job.

Reorganise "Save jobs" page

---

docs/verify/plot-quantum-states.ipynb

This page wrapped code blocks in `<TabItem>` tags to include them in the tab component. This looks nice but unfortunately relied on some implementation details of how the notebook is converted to the web page, which is something we want to avoid.
This PR removes the tabs and uses headings instead to unblock publishing the page while we work on a more robust solution.

Remove tabs from "Plot quantum states"

---

scripts/nb-tester/test-notebook.py

An alternative to https://github.com/Qiskit/documentation/pull/1181. This should help when executing many notebooks that submit jobs as they'll all submit their jobs immediately and begin queueing in parallel.

Use asyncio to parallelize notebook testing

---

.github/workflows/deploy-tutorials.yml
tutorials/learning-api.conf.yaml

I thought I'd tested this in #1154 but I actually only tested the uploader test workflow. I'd forgotten to pass the environment from the input to the job.
Something which wasn't my fault is that some tutorial UUIDs seem to have changed, I'm not sure why this is but am investigating.
With the new UUIDs, the workflow is working ([see run](https://github.com/Qiskit/documentation/actions/runs/8798350887/job/24145159885)).

Fix tutorial deployment process

---

docs/start/install.mdx

Closes #1183, and also incorporates suggestions from #1163 (adds the video and moves admonition statement "out of the way")

Install page updates

---

docs/run/primitives-get-started.mdx

Fix url in Get started with primitives

---

Dockerfile
docs/start/index.mdx

We use a new approach in closed source that sets `ENV HOSTNAME 0.0.0.0` in the Dockerfile to work around https://github.com/vercel/next.js/issues/53171 breaking IBM Code Engine with IPv6.

Switch to new Docker image for staging/PR builds

---

docs/api/qiskit-ibm-provider/0.10/_toc.json
docs/api/qiskit-ibm-provider/0.7/_toc.json
docs/api/qiskit-ibm-provider/0.8/_toc.json
docs/api/qiskit-ibm-provider/0.9/_toc.json
docs/api/qiskit-ibm-provider/_toc.json
docs/api/qiskit-ibm-runtime/0.18/_toc.json
docs/api/qiskit-ibm-runtime/0.19/_toc.json
docs/api/qiskit-ibm-runtime/0.20/_toc.json
docs/api/qiskit-ibm-runtime/0.21/_toc.json
docs/api/qiskit-ibm-runtime/0.22/_toc.json
docs/api/qiskit-ibm-runtime/_toc.json
docs/api/qiskit-ibm-runtime/dev/_toc.json
scripts/lib/api/Pkg.ts
scripts/lib/api/conversionPipeline.test.ts
scripts/lib/api/generateToc.test.ts
scripts/lib/api/generateToc.ts

Closes https://github.com/Qiskit/documentation/issues/1212. As explained there, this is because:
1. Qiskit SDK is getting a bigger revamp in https://github.com/Qiskit/documentation/issues/1211 and it will also flatten submodules, so we want to be consistent.
2. The module list is so short that it's useful to have the navbar be flatter. It makes things less crowded and more discoverable.
Note that some of the Runtime provider pages aren't very useful...I opened https://github.com/Qiskit/documentation/issues/1240 to track that.
For now, this is implemented as the `Pkg` constructor setting a boolean argument for whether modules should be nested or not. I'm coming up with an alternative—but similar factoring—while working on https://github.com/Qiskit/documentation/issues/1211. This PR is …

Flatten left table of contents for Runtime and Provider

---

README.md

Clarify the options for fixing a file with a Prettier error.

Specify command to run Prettier

---

docs/api/migration-guides/_toc.json
docs/api/migration-guides/index.mdx

* `/api/migration-guides/v2-primitives` is already in the ToC as a top-level entry called "Migrate to the Qiskit Runtime V2 primitives"
* `/api/migration-guides/qiskit-runtime-from-provider` is already in the section `Migrate to Qiskit Runtime`, but under the new URL `qiskit-runtime-from-ibm-provider`
I think it was a bad merge conflict to duplicate the entries in the new Runtime 0.20 section.

Remove duplicate entries in Migration Guides ToC

---

docs/verify/index.mdx

Hardware recommendations for simulation

---

docs/run/retired-systems.mdx

Algiers, Cairo, and Hanoi (27-qubit systems) to be retired on 30 April. Add to retired systems page.

Falcon processors retirement on 30 April

---

scripts/lib/api/generateToc.ts
scripts/lib/stringUtils.test.ts
scripts/lib/stringUtils.ts

Prework for https://github.com/Qiskit/documentation/pull/1256. It was confusing how we pass both `tocModules: TocEntry[]` and `tocModulesByTitle: Dictionary<TocEntry>`. It wasn't clear how those values relate, and `Dictionary` is an under-documented API by Lodash.
Also adds `hasPrefix`, which we will need in https://github.com/Qiskit/documentation/pull/1256.

Refactor generateToc.ts to not use dictionary type

---

.github/ISSUE_TEMPLATE/config.yml

I mistakenly put a dash in front of each line of the new issue template code, rather than just the first line, so the template isn't showing up.

fix format of issue template

---

scripts/lib/api/generateToc.test.ts
scripts/lib/api/generateToc.ts

This is to unblock https://github.com/Qiskit/documentation/issues/1249. We now use the project folder that `Pkg.mock().outputDir()` would use.
This also removes inline snapshots. They can't be updated via `npm test -- -u` due to Prettier, so it's more helpful to use a normal `expect().toEqual()`.

Refactor generateToc tests to use normal project structure

---

docs/verify/plot-quantum-states.ipynb

This is possible with the new `CodeCellPlaceholder` components. [Check it out](https://qiskit-docs-preview-pr-1278.1799mxdls7qz.us-south.codeengine.appdomain.cloud/verify/plot-quantum-states).
***
Closes #1219

Add tabs back into "Plot quantum states"

---

docs/api/qiskit-ibm-provider/0.10/_toc.json
docs/api/qiskit-ibm-provider/0.7/_toc.json
docs/api/qiskit-ibm-provider/0.8/_toc.json
docs/api/qiskit-ibm-provider/0.9/_toc.json
docs/api/qiskit-ibm-provider/_toc.json
docs/api/qiskit-ibm-runtime/0.14/_toc.json
docs/api/qiskit-ibm-runtime/0.15/_toc.json
docs/api/qiskit-ibm-runtime/0.16/_toc.json
docs/api/qiskit-ibm-runtime/0.17/_toc.json
docs/api/qiskit-ibm-runtime/0.18/_toc.json
docs/api/qiskit-ibm-runtime/0.19/_toc.json
docs/api/qiskit-ibm-runtime/0.20/_toc.json
docs/api/qiskit-ibm-runtime/0.21/_toc.json
docs/api/qiskit-ibm-runtime/0.22/_toc.json
docs/api/qiskit-ibm-runtime/_toc.json
docs/api/qiskit-ibm-runtime/dev/_toc.json
scripts/commands/checkOrphanPages.ts
scripts/lib/api/__snapshots__/conversionPipeline.test.ts.snap
scripts/lib/api/generateToc.test.ts
scripts/lib/api/generateToc.ts

Closes https://github.com/Qiskit/documentation/issues/1249. 
Some of the reasons we decided to make this change:
1. Consistency with Qiskit SDK
2. It's useful to show the currently selected page in the left ToC when you land on the index
Before:
After:

Add index page to left ToC for Runtime and Provider

---

docs/api/migration-guides/qiskit-runtime-use-case.mdx
docs/run/quantum-serverless.mdx

The github.io URL has changed from quantum-serverless to qiskit-serverless, and there is no redirect.
https://qiskit-extensions.github.io/quantum-serverless/ -> https://qiskit-extensions.github.io/qiskit-serverless/
Update the URLs in our docs

url change for serverless

---

scripts/lib/api/Pkg.ts
scripts/lib/api/__snapshots__/conversionPipeline.test.ts.snap
scripts/lib/api/conversionPipeline.test.ts
scripts/lib/api/generateToc.test.ts
scripts/lib/api/generateToc.ts

The upcoming cloud transpiler client docs will not have release notes at first.

Allow packages to not have release notes

---

scripts/lib/api/Pkg.ts

The new Qiskit transpiler service client will not have GitHub links when we first add it.

Allow not setting githubSlug

---

scripts/lib/api/TocGrouping.ts

This temporarily broke docs regeneration. My bad!

Fix typo in TocGrouping

---

scripts/lib/api/Pkg.ts
scripts/lib/api/generateToc.test.ts
scripts/lib/api/generateToc.ts

Thanks to https://github.com/Qiskit/documentation/issues/1213, we no longer nest submodules in the left ToC. We don't plan to nest again in the future because it limits discoverability of modules and results in too deep of nesting.

Remove unused ToC nesting mechanism

---

docs/api/qiskit/0.19/logging.mdx
docs/api/qiskit/0.24/logging.mdx
docs/api/qiskit/0.25/logging.mdx
docs/api/qiskit/0.26/logging.mdx
docs/api/qiskit/0.27/logging.mdx
docs/api/qiskit/0.28/logging.mdx
docs/api/qiskit/0.29/logging.mdx
docs/api/qiskit/0.30/logging.mdx
docs/api/qiskit/0.31/logging.mdx
docs/api/qiskit/0.32/logging.mdx
docs/api/qiskit/0.33/logging.mdx
docs/api/qiskit/0.35/logging.mdx
docs/api/qiskit/0.36/logging.mdx

This PR adds the header of a class that was missing its id. The id was manually fixed in Box by modifying the HTML, and this is the regeneration as a follow-up of #1283

Add missing header - class without id

---

scripts/lib/api/generateApiComponents.ts

This PR refactors the dispatch table used to prepare the props of each API component in order to simplify the `generateApiComponents.ts` script. The functions for "functions" and "methods" cannot be merged trivially because they check in different ways the `isDedicatedPage` prop. Using the same method for that gives us false positives on pages like [this](https://docs.quantum.ibm.com/api/qiskit/0.36/execute). Moreover, functions don't need any header in those cases.
Thanks @Eric-Arellano for the idea on #1283

Deduplicate `generateApiComponents` dispatch table entries

---

scripts/commands/updateApiDocs.ts
scripts/lib/fs.ts

This was getting in the way of adding the new qiskit-transpiler-service docs, since its folder is empty. This also was a problem when rerunning the script if the folder had been previously deleted without having restored the deleted files before the rerun.

Fix API docs script to tolerate empty docs folder

---

scripts/commands/checkInternalLinks.ts
scripts/commands/checkMetadata.ts
scripts/commands/checkOrphanPages.ts
scripts/commands/checkPagesRender.ts
scripts/commands/convertApiDocsToHistorical.ts

Unblocks https://github.com/Qiskit/documentation/pull/1317
Context: we can't use `api/*` for globs because it would match against `api/migration-guides`.

Make generic scripts for new projects

---

scripts/lib/api/Pkg.ts
scripts/lib/api/generateToc.test.ts
scripts/lib/api/generateToc.ts

Turns out, this truncation does not work well with https://github.com/Qiskit/documentation/pull/1317. We agreed the best approach is to show the full module path for that package.
This PR also fixes https://github.com/Qiskit/documentation/pull/1308 to put the error in the correct location.

Don't truncate API ToC by default

---

README.md
docs/api/qiskit-transpiler-service/_package.json
docs/api/qiskit-transpiler-service/_toc.json
docs/api/qiskit-transpiler-service/ai.mdx
docs/api/qiskit-transpiler-service/index.mdx
docs/api/qiskit-transpiler-service/qiskit_transpiler_service.ai.AIRouting.mdx
docs/api/qiskit-transpiler-service/qiskit_transpiler_service.transpiler_service.TranspilerService.mdx
docs/api/qiskit-transpiler-service/transpiler_service.mdx
docs/api/qiskit-transpiler-service/utils.mdx
public/api/qiskit-transpiler-service/objects.inv
scripts/api-html-artifacts.json
scripts/lib/api/Pkg.ts

Docs for https://pypi.org/project/qiskit-transpiler-service/.
These docs are not ready to go live to production yet. But we can safely merge them in this repository to unblock infrastructure work in closed source. We won't have closed source sync over these files until we get the final okay from the transpiler service team.

Add Qiskit Transpiler Service Client docs

---

.github/workflows/weekly-checks.yml

Closes #547. This PR makes a new issue whenever the weekly checks fail. We decided to create a new issue rather than reopening / commenting. This reduces code complexity and lets us reuse the code from `.github/workflows/learning-uploader-test.yml`.

Make issue when weekly checks fail

---

docs/api/migration-guides/qiskit-runtime-use-case.mdx
docs/run/quantum-serverless.mdx

This is the final planned URL.
I'll update the Runtime release notes link separately.

Update Qiskit Serverless URLs to final destination

---

scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py

When we use the fake backend to test code examples, we can get the following warnings ([example](https://github.com/Qiskit/documentation/actions/runs/8991252592/job/24698420154?pr=1307#step:7:74)).
```
Cell 24:
│ /home/runner/work/documentation/documentation/.tox/py3/lib/python3.9/site-
│ packages/qiskit_ibm_runtime/session.py:157: UserWarning: Session is not
│ supported in local testing mode or when using a simulator.
│   warnings.warn(
Cell 28:
│ /home/runner/work/documentation/documentation/.tox/py3/lib/python3.9/site-
│ packages/qiskit_ibm_runtime/fake_provider/local_service.py:243:
│ UserWarning: Options {'default_shots': 10000, 'dynamical_decoupling':
│ {'enable': True}} have no effect in local testing mode.
│   warnings.warn(f"Options {options_copy} have no effect in local testing …
```

Ignore local testing warnings when testing with fake backend

---

.gitignore
.prettierignore

If people run MyPy in the repo, they'll have the folder `.mypy_cache` which Prettier will format and Git will try to add.

Prettier ignore mypy_cache

---

scripts/commands/updateApiDocs.ts

This adds a `--sphinx-artifact-folder` (alias `--sphinx-output`) option to manually specify the root of the Sphinx HTML output for a given package.  This implies `--skip-download`.  This is convenient for local API-docs development of the targetted packages, since I can use their regular docs-build processes and then just point `gen-api` at the right place without needing to copy anything into special folders.
For example, I've locally been using Sphinx as normal in Qiskit, then running
```bash
npm run gen-api -- -p qiskit -v 1.2.0 -a /path/to/docs/_build/html
```
to have the script directly target the Sphinx files without copying them.
I made the magic `/artifact` suffix a bit more local, rather than spread between two functions for two reasons:
1. it's easier to reason about magic …

Add option to use arbitrary Sphinx HTML artifact folder

---

README.md

The PR adds instructions to the readme to preview changes made for API docs authors locally.

Update readme to include preview instructions

---

docs/api/qiskit/0.19/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.24/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.25/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.26/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.27/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.28/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.29/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.30/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.31/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.32/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.33/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.35/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.36/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.37/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.38/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.39/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.40/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.41/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.42/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.43/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.44/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.45/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx
docs/api/qiskit/0.46/qiskit.transpiler.passes.NoiseAdaptiveLayout.mdx

Closes #1200
This PR fixes a bad indentation in `NoiseAdaptiveLayout` as explained in #1200.

Fix bad indentation in `NoiseAdaptiveLayout`

---

scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py

Running notebooks with the `FakeKyoto` backend was occassionally taking a very long time (see https://github.com/Qiskit/documentation/pull/1307#issuecomment-2099165171). We believe this is due to some notebooks taking advantage of the large number of qubits it supports.
This PR switches to Qiskit's `GenericBackendV2`. This should be much faster and gives us more fine-grained control over the test backend properties.

Use generic backend for testing

---

docs/run/get-backend-information.ipynb

This notebook explicitly requested a simulator backend, which doesn't work with our testing provider. They'll also be removed soon, so the best fix is to use a real device instead.
I've also changed the instance to the open provider so users see the same list of backends.
---
Fixes #1228.

Remove simulator from "Get backend information"

---

scripts/lib/api/TocGrouping.test.ts

The Qiskit devs were worried about the index page from https://github.com/Qiskit/qiskit/pull/12333 falling out of sync with our custom grouping for `_toc.json`. 
This PR adds a test to ensure that the two files are in sync. In particular, it checks that the grouping and sequence of modules is identical. It does not check that the label for the groups are the same, though.
For now, we only check the dev docs because the latest docs (1.0) fail. https://github.com/Qiskit/documentation/issues/1341 will also start checking the latest docs once 1.1 is released.

Test that Qiskit TocGrouping is in sync with index page

---

docs/run/_toc.json
docs/run/monitor-job.mdx

How to cancel a job on the UI and programmatically

---

.gitignore

Used by https://github.com/pyenv/pyenv-virtualenv.

add .python-version to .gitignore

---

scripts/nb-tester/notebooks.toml
scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py

Closes #1319.
* The script no longer uses `all-notebooks` as a glob pattern to search, instead it just iterates through the list of filepaths
* Added a check to detect unclassified notebooks

Make sure all notebooks are classified in `notebooks.toml`

---

scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py

We occasionally see the following warnings when executing notebooks:
[See logs](https://github.com/Qiskit/documentation/actions/runs/9020672968/job/24786345632#step:7:90).
These warnings are harmless, out of our control, and break CI. This PR runs some code in the kernel before notebook execution to disable them.

Ignore MPL cache warnings

---

scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py

#1362 didn't work as Matplotlib emits warnings through the `logging` module rather than the `warnings` module. This follows advice (https://github.com/matplotlib/matplotlib/issues/23326#issuecomment-1164772708) to correctly suppress the warnings.

Fix MPL warning suppression

---

README.md

Ask contributors to use `tox` for final notebook execution.

---

docs/run/_toc.json
docs/run/circuit-execution.mdx
docs/run/monitor-job.mdx

[WIP] Updates and de-orphaning of circuit-execution.mdx

---

docs/start/hello-world.ipynb
docs/start/install.mdx

rmv mention of zsh as not necessary

---

scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py

Embarassingly, #1368 broke the mocking code as `warnings` was never imported. I didn't notice because `kernel.execute` doesn't report if the execution fails. I'm making a companion PR to catch this.

Fix mocking code

---

scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py

We run some code before notebook execution to silence some warnings and set up mock backends. At the moment, errors are ignored and the kernel continues, often leading to unexpected behaviour.
This PR explicitly checks for errors when running the initialization code and exits early if needed.

Check for errors when executing initialization code

---

scripts/nb-tester/notebooks.toml

We didn't notice this until we tried executing notebooks that submit jobs.

Fix notebooks.toml

---

.github/workflows/weekly-checks.yml
scripts/lib/links/ExternalLink.ts

Part of #823
This PR adds a new HTTP header to the external link checker to set the auth for GitHub when we are checking GitHub links. The new header is only used for GitHub links following what we do in the closed-source repo.
In order to be able to get the environment variable from typescript with `process.env.GITHUB_TOKEN`, we need to define it in the workflows. In the case of running the script locally, the token could be undefined.

External link checker: Add an HTTP header for the auth for GitHub

---

.github/actions/set-up-notebook-testing/action.yml
.github/workflows/main.yml
scripts/nb-tester/pyproject.toml
scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py
scripts/nb-tester/test/test_notebook_classification.py
tox.ini

We want to run the notebook classification check on every PR. This PR pulls that test out into a separate pytest suite and runs it as part of the standard CI job. I'd like to also add some more tests to this suite as the `nb-tester` has grown in complexity and there were some issues with it recently.

Pull notebook classification out into separate test

---

docs/build/circuit-library.ipynb

Move standard gates first in Circuit Library pg

---

scripts/ibm-quantum-learning-uploader/pyproject.toml
scripts/ibm-quantum-learning-uploader/src/learning_uploader/upload.py

Small refactor before #1390.
The spinner was fun when the tool was primarily used locally, but now it's annoying in CI and is an extra dependency. See an example of the new behaviour in the [test](https://github.com/Qiskit/documentation/actions/runs/9173882338/job/25223510491#step:5:102).

Remove spinner from learning uploader

---

docs/api/qiskit-transpiler-service/_toc.json
scripts/lib/api/Pkg.ts

We got updated instructions from leadership to remove this and instead have a banner saying that the API is experimental.

Revert putting `(beta)` in Transpiler Service title

---

docs/start/configure-qiskit-local.mdx
scripts/commands/checkInternalLinks.ts

The check broke because the missing ` messed up the markdown parser.

Fix broken link in configure-qiskit-local.mdx

---

tutorials/chsh-inequality/chsh-inequality.ipynb

First part of #1443 
Still need to figure out how to change the tags on the platform.

Remove mention of simulated results in CHSH tutorial

---

docs/verify/_toc.json
docs/verify/simulate-with-qiskit-primitives.mdx

We should clarify this is the Qiskit SDK. 
We don't change the URL because it will be redirected anyways soon to its new home in the `guides/` section, so it's not worth renaming yet.

Clarify title for Qiskit SDK simulator page

---

scripts/patterns-reorg/entries.py
scripts/patterns-reorg/models.py
scripts/patterns-reorg/page_content.py

This also improves the patterns index pages:
* adds missing metadata
* uses `dedent()` so the code is easier to modify
* Adds an h2 `Guides`

Use the new labels mechanism in docs guide reorganization

---

scripts/patterns-reorg/entries.py

Before:
```
* [Configure runtime compilation](./configure-runtime-compilation)
* [Configure runtime error mitigation](./configure-error-mitigation)
* [Advanced runtime options](./advanced-runtime-options)
* [Introduction to execution modes](./execution-modes-intro)
* [Introduction to sessions](./sessions)
* [Run jobs in a session](./run-jobs-in-session)
* [Run jobs in a batch](./run-jobs-batch)
* [Monitor or cancel a job](./monitor-job)
* [Estimate job run time](./estimate-job-run-time)
* [Minimize job run time](./minimize-time)
* [Maximum execution time](./max-execution-time)
* [Execution modes FAQs](./execution-modes-faq)
```
After:
```
* [Configure runtime compilation](./configure-runtime-compilation)
* [Configure runtime error mitigation](./configure-error-mitigation)
* [Advanced …
```

Fix workflow index page for Execute on Hardware

---

start

For some reason, a couple weeks ago `ctrl-c` stopped properly shutting down the Docker container when running `./start`. So I'd have to manually kill the container.
It now works when using `--init`:
```
❯ docker run --help | grep init
--init                           Run an init inside the container that forwards signals and reaps processes
```

Fix ctrl-c not shutting down ./start

---

scripts/lib/links/ignores.ts

Closes #1478
The link checker complains about a Slack link that is not broken. This PR adds the link to the ignores.

Ignore slack archives link

---

docs/start/hello-world.ipynb

This fixes #1477 with the correct ordering of operators

Correct operator ordering

---

scripts/patterns-reorg/page_content.py

Add descriptions to new patterns pages

---

docs/verify/index.mdx

Update language to "debug"

---

scripts/patterns-reorg/entries.py
scripts/patterns-reorg/main.py
scripts/patterns-reorg/models.py

This PR changes the patterns script to use '`"url": "/guides"`' instead of `"url": "/guides/index"'` for the index entry of the guides `_toc.json`. The PR doesn't modify the `entries.py` script to avoid having an empty slug.

Change index entry from patterns `_toc.json`

---

scripts/patterns-reorg/page_content.py

We shouldn't be using external links in general.
This PR also updates to use the new `guides/` URLs. Note that we have some risk that the links we hardcode here diverge from our source of truth in `entries.py`. We can't have `page_content.py` load the final URLs from `entries.py` because it would result in a circular import. However, our link checker will complain if there are any divergences, so it should be fine.

Use internal links for new index page

---

scripts/patterns-reorg/main.py

Part of https://github.com/Qiskit/documentation/issues/1297. Now when you run `scripts/patterns-reorg/main.py --delete-existing`, Git will recognize which files were renamed and preserve their Git history.

Allow deleting all existing docs guides

---

docs/run/configure-error-mitigation.mdx
docs/run/configure-runtime-compilation.mdx

How to turn off error mitigation and suppression

---

docs/start/setup-channel.mdx

Add Overwrite=true when saving API key to make it easier for users who are updating their key

Add Overwrite=true when saving API key

---

docs/transpile/index.mdx

Typo fix on transpile/index

---

qiskit_bot.yaml

Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
there's other folks better suited to reviewing the docs for serverless these days

Drop paul as serverless reviewer

---

scripts/patterns-reorg/entries.py

After a meeting about #1301, we decided the most appropriate action was to link out to the existing "Product updates" page.

Add "Latest updates" link to patterns reorg

---

scripts/patterns-reorg/entries.py

Turns out we don't want to do this any more.

Revert "Add "Latest updates" link to patterns reorg (#1536)"

---

.github/workflows/notebook-test-cron.yml

Each time the fortnightly cron job runs, I usually make a PR updating the notebooks in this repo with the output of the cron job. This PR automates that process. As well as saving some manual work, this also means I can review those PRs too.
See https://github.com/frankharkins/documentation/pull/10 for an example of this working.

Have cron job create PR to update notebook outputs

---

docs/build/unitary-synthesis.mdx

Closes #1439 
Decompose is basically only used here to visualize the circuit correctly. If it wasn't, it  just be an opaque block when calling `draw()`

Explain why decompose is used

---

docs/support.mdx

Add instructions to delete account and account data

---

docs/build/_toc.json
docs/build/operator-class.ipynb
docs/build/operators-overview.ipynb
qiskit_bot.yaml
scripts/nb-tester/notebooks.toml

Closes #1440 
@kevinsung, here's what I have so far in terms of content to include. I think it might be worth mentioning the overloaded operators for the `SparsePauliOp` class and demonstrate some of the algebra that can be done.

Update "operators overview" page to highlight SparsePauliOp and split in-depth Operator coverage to separate page

---

docs/run/_toc.json
docs/run/error-mitigation-explanation.ipynb

Add in "suppression" to error mitigation pg title to make more accurate

---

.github/workflows/main.yml
package.json
scripts/commands/checkPatternsIndex.ts

Closes https://github.com/Qiskit/documentation/issues/1299
This PR adds a script that validates that every page shows up both in the Tools folders and in the Workflow index pages.

Add patterns index validation

---

docs/build/operator-class.ipynb
docs/build/operators-overview.ipynb

Noticed a few edits to make in a [recent closed PR](https://github.com/Qiskit/documentation/pull/1517). 
- Changed "we" to "you"
- avoided "will" when appropriate
- replaced "may" with either "can" or "might" depending on context
- general typo/punctuation/capitalization cleanup

Edits to operators pages

---

docs/run/save-jobs.ipynb

This code example fails in our tests if the most recent job is cancelled. This PR filters by job status to avoid that.

Make code example in "save-jobs" more robust

---

Dockerfile
docs/start/index.mdx
start

We removed the remote refresh mechanism from the previews, so port 5001 is no longer relevant. 
We also can now use the Dockerhub image for both `./start` and IBM Code Engine PR previews, so we can be consistent and stop using the IBM Container Registry version. That simplifies our infra.

Use new Docker image for previews

---

docs/run/error-mitigation-explanation.ipynb
docs/start/latest-updates.mdx

bring in the latest blog and the newest docs updates. 
Also closes https://github.com/Qiskit/documentation/issues/1597 to use reverse chronological order for the Runtime service updates.

update the latest updates page

---

docs/transpile/custom-transpiler-pass.ipynb

The `custom-transpiler-pass.ipynb` notebook was using a [deprecated](https://numpy.org/devdocs/release/1.25.0-notes.html#deprecations) numpy function called `alltrue`. This PR changes the notebook to use instead the function `all`.
In this [CI](https://github.com/Qiskit/documentation/actions/runs/9762810433/job/26947134720?pr=1631) run you can find the notebook failing because of the deprecation.

Fix custom-transpiler-pass notebook

---

docs/guides/processor-types.mdx

Text from the hardware team:
HeronR2:
This is a revision of our original Heron processor. The chip has been redesigned to now include 156 qubits in a heavy-hexagonal lattice. While continuing to make use of the innovations of the original Heron systems, it also introduces a new TLS mitigation feature that controls the TLS environment of the chip, thereby improving coherence and stability across the whole chip.

Add r2 to Heron entry in processor-types file

---

docs/guides/install-qiskit.mdx

Qiskit contract with respect of QPY is kind of strong and deserves an explanation. Adding it to https://docs.quantum.ibm.com/start/install#release-schedule

Explain QPY support in install#release-schedule

---

scripts/lib/links/extractLinks.test.ts
scripts/lib/links/extractLinks.ts

In Jupyter notebooks, we weren't correctly detecting headers if the markdown section right above it ended in `</Admonition`. This broke CI in https://github.com/Qiskit/documentation/pull/1673.

Fix markdown link extraction

---

scripts/pr_previews/builder.py

Part of https://github.com/Qiskit/documentation/issues/1043. 
The new `scripts/pr-previews/builder.py` file builds a static copy of the site using the Git branch's current copy of the docs, then writes the static files to the folder specified, like `scripts/pr-previews/builder.py pr-reviews/90`. The static site can then be served with a simple server like `python3 -m http.server` or GitHub Pages.
The script takes 57 seconds on my MacBook Pro.
The script expects that the Docker image for the static builder can be accessed via `docker pull`, i.e. that you already have authentication and everything. For now, I'm using a local copy of the Docker image. Once the new image is published, we'll switch to the Container Registry copy. Setting up Container Registry will be handled in the GitHub …

Add script to statically build PR previews

---

.github/workflows/pr-preview.yml
scripts/pr_previews/builder.py
scripts/pr_previews/deploy.py
scripts/pr_previews/poll_deployment.py
scripts/pr_previews/utils.py

Part of https://github.com/Qiskit/documentation/issues/1043.
This deploys a new folder at https://qiskit.github.io/documentation/pr-{x}. For now, it's a contrived `index.html` only to get the technique working. We will switch to the full built preview app once the Docker image is accessible.
The GitHub workflow follows this logic:
1. Build the static site
2. Deploy by pushing the files to the `gh-pages` branch under the folder `pr-{x}`
3. Check if the deploy has worked by polling https://qiskit.github.io/documentation/pr-{x}, with a one minute timeout.
A follow up will add the cleanup mechanism.

Add PR preview GitHub infrastructure

---

docs/api/migration-guides/qiskit-runtime-from-ibm-provider.mdx
docs/api/migration-guides/qiskit-runtime-from-ibmq-provider.mdx

Closes #1667. Update broken code to 
`QiskitRuntimeService.save_account(channel="ibm_quantum", token="<IQP_TOKEN>", overwrite=True, set_as_default=True)`
Affects two migration guides.

Fix typo in Runtime save_account code

---

index.html

While the deployment action links directly to the subfolder, people might still stumble on the index page.

Improve index page for GitHub pages

---

docs/api/migration-guides/local-simulators.mdx

Fix circuit in sampler in migration guide
In the migration guide **Migrate from cloud simulators to local simulators**, the section on Clifford simulation creates a `circuit` but does not use it in the pass manager and sampler. This is fixed here.

Fix circuit in sampler in migration guide

---

scripts/pr_previews/builder.py

We explicitly list all the folders to make sure API docs aren't included.

Fix PR previews not including Additional Resources

---

docs/guides/install-qiskit.mdx

Improvements to install page 

---

package.json
scripts/commands/api/convertApiDocsToHistorical.ts
scripts/commands/api/regenerateApiDocs.ts
scripts/commands/api/updateApiDocs.ts

I was spending some time in `scripts/commands` and realized it's gotten quite big. The 3 API scripts are all very focused on one single workflow, so we can make things better organized with a folder.

Group API scripts together

---

.github/workflows/pr-preview.yml

A PR preview failed to deploy today because a prior workflow was already pushing the deploy, which messed up the Git state. We should only ever attempt to deploy one PR preview at a time - pushing a new commit should cancel the prior deploy attempt if still in progress.
To cancel, this uses the technique from https://www.meziantou.net/how-to-cancel-github-workflows-when-pushing-new-commits-on-a-branch.htm.

Avoid race condition with PR previews

---

CODE_OF_CONDUCT.md

The code of conduct was migrated to https://docs.quantum.ibm.com/open-source/code-of-conduct from qiskit/qiskit repo because it is more discoverable.

Point Code of Conduct to the docs site

---

scripts/js/lib/api/dedupeHtmlIds.test.ts
scripts/js/lib/api/generateApiComponents.test.ts
scripts/js/lib/api/generateToc.test.ts
scripts/js/lib/api/htmlToMd.test.ts
scripts/js/lib/api/mergeClassMembers.test.ts
scripts/js/lib/api/objectsInv.test.ts
scripts/js/lib/api/specialCaseResults.test.ts
scripts/js/lib/api/updateLinks.test.ts
scripts/js/lib/testUtils.ts

To unblock packaging our scripts for the Qiskit Functions repos, I plan to migrate us to Playwright. I was having issues with getting Jest to work with TypeScript and ES Modules (vs CommonJS modules), whereas Playwright works out-of-the-box.
Playwright does not have `toMatchInlineSnapshot`, and `toMatch` has different semantics; so, this switches to `toEqual`. It also removes unnecessary `describe()` blocks.

Refactor tests to prepare for Playwright

---

scripts/js/commands/api/convertApiDocsToHistorical.ts
scripts/js/lib/api/Pkg.ts
scripts/js/lib/api/releaseNotes.ts
scripts/js/lib/api/sphinxArtifacts.ts
scripts/js/lib/fs.test.ts
scripts/js/lib/fs.ts
scripts/js/lib/links/extractLinks.ts

`getRoot()` isn't going to work well when we package `scripts/js` for the Qiskit Functions repositories. One particular challenge is that in this repo, we run scripts from `scripts/js/commands/`—but the Functions repos will run from `node_modules/qiskit-documentation/dist/commands`—so the relative path we were using cannot work for both situations.
Another issue is that Playwright does not define `__dirname` because it runs with ES Modules rather than CommonJS.
Turns out, we don't even need to use `getRoot()`. The relative paths will be relative to the cwd, which should be the repo root anyways.

Remove `getRoot()` helper function

---

docs/guides/create-transpiler-plugin.ipynb
docs/guides/transpiler-plugins.ipynb
docs/guides/transpiler-stages.ipynb
package.json
scripts/config/cspell/cSpell.json
scripts/config/cspell/dictionaries/qiskit.txt
scripts/js/commands/checkSpelling.ts
scripts/js/lib/fs.ts

Closes https://github.com/Qiskit/documentation/issues/1741. We use the cspell library to check Jupyter notebooks:
```
❯ npm run check:spelling
> qiskit-documentation@0.1.0 check:spelling
> tsx scripts/js/commands/checkSpelling.ts
$ npx cspell --no-progress --config scripts/config/cspell/cSpell.json docs/**/*.mdx !docs/api/**/*.mdx docs/api/migration-guides/*.mdx
CSpell: Files checked: 53, Issues found: 0 in 0 files
❌ Unrecognized word in docs/guides/hello-world.ipynb: typoooooo
```
There is now an `--apis` flag, although there are currently failures.
--
Other repositories can also now run cspell with this `script`:
```
"check:spelling": "node node_modules/qiskit-documentation/dist/commands/checkSpelling.js --config node_modules/qiskit-documentation/scripts/config/cspell/cspell.json"
```

Spellcheck Jupyter notebooks & allow running checker from other repos

---

.github/workflows/weekly-checks.yml
README.md
start

The preview app is slow due because the it searches through the docs folder each time we load a page. Eric had the idea to improve the speed by removing API docs from the image. Since the API docs are so large, this roughly halves the time taken per page load. Writers can ask to include API docs using the `--apis` option.
Helps with https://github.com/Qiskit/documentation/issues/1720.

Allow skipping API docs in local previews

---

.github/workflows/main.yml

We need to volume mount API docs in the pages render check because `/api/migration-guides`. This fixes https://github.com/Qiskit/documentation/actions/runs/10079828374/job/27868447282?pr=1665#step:16:76
See https://github.com/Qiskit/documentation/pull/1750 for the source of the regression.

Fix pages render check in CI

---

docs/api/migration-guides/index.mdx
docs/api/migration-guides/qiskit-algorithms-module.mdx
docs/api/migration-guides/qiskit-opflow-module.mdx
docs/api/migration-guides/qiskit-quantum-instance.mdx
docs/api/migration-guides/qiskit-runtime-examples.mdx
docs/api/migration-guides/v2-primitives.mdx

This is to prepare for us moving the migration guides to not have `/api` in their URL. When we move those files, all the relative links like `../qiskit` stop working.
The change was generated by find-and-replace, and the link checker will validate it's all good.

Use absolute internal links in migration guides

---

start

We are switching from Dockerhub to Container Registry. The image is public and you do not need to set up anything specific; you only need normal Docker.

Switch to IBM Container Registry

---

package-lock.json
package.json
scripts/js/lib/api/htmlToMd.ts

The main motivation is that old versions of `rimraf` and `glob` are not supported, and were using `inflight` which was deprecated because it has a memory leak.

Upgrade cspell, Prettier, and transitive deps

---

.github/workflows/pr-preview.yml

Don't waste resources.
From [GH Action's documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore):
> If you want to both include and exclude path patterns for a single event, use the paths filter prefixed with the ! character to indicate which paths should be excluded.
>
> The order that you define paths patterns matters:
>
> - A matching negative pattern (prefixed with !) after a positive match will exclude the path.
> - A matching positive pattern after a negative match will include the path again.

Don't build PR previews for API docs

---

scripts/config/notebook-testing.toml

Closes https://github.com/Qiskit/documentation/issues/1788. The `tutorials/` entries were accidentally added back due to a bad merge conflict.

Remove tutorials folder from notebook-testing.toml

---

docs/guides/get-started-with-primitives.mdx

This PR is a proposal to partially address https://github.com/Qiskit/documentation/issues/846. The issue was written pre-backend primitives V2, when there were more differences in the interface (*) between runtime and backend primitives, so proposing a separate guide seemed reasonable at the time. Now (V2), I think the differences are small enough to keep the backend primitives section as an appendix to the get-started page, where I just added the usual V1-V2 tabs and a section at the end explaining differences. 
This is just a rough proposal and it has been a while since I've written a guide, so feel free to edit it to fit the style/conventions that are used now.
---
(*) Backend primitives handled different kinds of pass managers to run before and after parameter binding, but V2 …

V2 additions to backend primitives section

---

docs/migration-guides/qiskit-quantum-instance.mdx

This is a proposal to address https://github.com/Qiskit/documentation/issues/1696, which doesn't correspond with my original reply.
While updating to the changes in ISA handling doesn't seem to complicated, I realized that updating the guide to use Primitives V2 seems very strange to me (because that is not how the migration was done at the time). The current guide is a (in my opinion, valid) reflection of what the motivations were with primitives V1, and the reason why it was appreciated was because it reflected well the evolution of the code. I also think that it is commonly understood that migration guides are written at a specific point in time, and may require "chaining" with a further migration guide to reach the current state of the package. So, instead of migrating everything to …

Add deprecation notice and further instructions to QuantumInstance migration guide

---

docs/guides/execution-modes-faq.mdx

#1799 says you cannot change a session's max TTL. What it really meant to say was you cannot change the _system defined_ max TTL. You can, however, set a limit that's lower than the system ceiling. 
Thanks @beckykd for spotting this!

Fix wording from 1799

---

scripts/nb-tester/requirements.txt

Serverless 0.15 no longer supports Python 3.9 and 3.10, which messes up our CI. We'll add this back after checking in with the Serverless team.

Revert to Serverless 0.14.2

---

.github/actions/set-up-notebook-testing/action.yml
.github/workflows/notebook-test.yml
scripts/nb-tester/pyproject.toml
scripts/nb-tester/requirements.txt
tox.ini

Closes https://github.com/Qiskit/documentation/issues/1826.
Qiskit Serverless requires Python 3.11+ now, even though Qiskit SDK still supports 3.9 and 3.10. While I'm talking to the Serverless team, it seems very unlikely they are going to change their mind on this due to their own constraints.
Unfortunately, this means that we need to always use Python 3.11 with our repository so that we can install serverless for the files that use it. Our other alternative is to stop testing the files with Serverless, but that seems even worse.
The risk with using 3.11 in CI rather than 3.9 is that we may use syntax not in Python 3.9 and 3.10. However, given the actual history of our docs, this seems unlikely: we don't use new Python syntax like type hints. If we do use Python 3.11-syntax, it's not the …

Restore Serverless 0.15.2 and test notebooks when changing requirements

---

.github/workflows/notebook-test-cron.yml
.github/workflows/notebook-test.yml
docs/guides/hello-world.ipynb

The artifact upload was failing because `path` was set to the empty string. It's fine to give an invalid file path like `no-changes`, so long as we give something. The action will warn but not fail in this case.

Fix artifact upload when no changes made

---

scripts/js/commands/api/convertApiDocsToHistorical.ts

Before, we never copied images for the release notes file to the historical API folder. For example, if we had the file `public/images/qiskit/release_notes_0_0.png`, we would not copy it over to `public/images/qiskit/1.1/release_notes_0_0.png` when we convert 1.1 from the latest release to instead be a historical release stored at `qiskit/1.1`. 
That is the right behavior for Runtime and Provider, because they only have a single `release_notes.mdx` file. However, it does not work correctly with Qiskit, which has one release note file per release.
This PR differentiates between the two use cases. It keeps things generic by using our `Pkg.hasSeparateReleaseNotes` mechanism.

Fix images in Qiskit release notes for historical versions

---

docs/guides/latest-updates.mdx

Now that [the blog](https://www.ibm.com/quantum/blog/qiskit-1-2-release-summary) is available, add a link to the release summary in the latest-updates file.

Add blog link to the SDK v1.2 latest-updates blurb

---

docs/guides/fair-share-scheduler.mdx

Suggestion to make the sentence clearer - use this, from Marco:
> The scheduler's default behavior is to select the next job by first identifying the group that has used the least amount of their allocation within the current scheduling window. If the selected group has more than one project, and both have jobs waiting to be executed, then the scheduler identifies the project that has used the least of their allocation within the scheduling window. Finally, if the selected project has submitted more than one job, the scheduler will select the oldest job first. 
Also adds appropriate trademark to a recent appearance of "IBM" on the page

Clarify wording in fair-share file

---

README.md
docs/api/qiskit-ibm-runtime/0.14/_toc.json
docs/api/qiskit-ibm-runtime/0.15/_toc.json
docs/api/qiskit-ibm-runtime/0.16/_toc.json
docs/api/qiskit-ibm-runtime/0.17/_toc.json
docs/api/qiskit-ibm-runtime/0.18/_toc.json
docs/api/qiskit-ibm-runtime/0.19/_toc.json
docs/api/qiskit-ibm-runtime/0.20/_toc.json
docs/api/qiskit-ibm-runtime/0.21/_toc.json
docs/api/qiskit-ibm-runtime/0.22/_toc.json
docs/api/qiskit-ibm-runtime/0.23/_toc.json
docs/api/qiskit-ibm-runtime/0.24/_toc.json
docs/api/qiskit-ibm-runtime/0.25/_toc.json
docs/api/qiskit-ibm-runtime/0.26/_toc.json
docs/api/qiskit-ibm-runtime/0.27/_toc.json
docs/api/qiskit-ibm-runtime/_toc.json
docs/api/qiskit-ibm-runtime/dev/_toc.json
docs/guides/latest-updates.mdx
docs/guides/save-jobs.ipynb
docs/migration-guides/qiskit-runtime-from-ibmq-provider.mdx
scripts/js/lib/api/Pkg.ts
scripts/js/lib/api/specialCaseResults.ts

We were being inconsistent with calling Runtime "Qiskit Runtime IBM Client" but "Qiskit IBM Runtime REST API". We also don't use IBM with "Qiskit Transpiler Service Client" and "Qiskit SDK". So, `@jyu00` and `@javabster` proposed that we simplify to remove the redundant IBM.
This PR updates the left page titles we use. A closed source PR will update the top dropdown.
We don't update the index pages for Runtime API docs because those are auto-generated.

Use consistent name for Qiskit Runtime Client

---

scripts/js/commands/checkSpelling.ts

Zx does not log `stdout` by default, but it does stderr. So, the MDX files weren't getting their stdout logs shown. My bad!
Closes https://github.com/Qiskit/documentation/issues/1846.

Fix cspell not outputting errors for MDX files

---

docs/guides/get-qpu-information.ipynb
docs/guides/monitor-job.mdx
docs/guides/primitive-input-output.ipynb

Timing data in Sampler

---

docs/guides/local-testing-mode.ipynb

Remove tag from cell and verify that the notebook runs properly.
Closes #1845

Deprecation warning no longer exists

---

.github/workflows/api-checks.yml
README.md
scripts/js/commands/checkInternalLinks.ts
scripts/js/lib/links/ignores.ts

This is to unblock https://github.com/Qiskit/documentation/issues/495. Our goal is to fix all broken links for Qiskit 0.46+, whereas we don't plan to fix <0.46. So, we want our script to make it ergonomic to check 0.46+.
This PR results in us now checking 0.46, 1.0, and 1.1 docs. It does that with two changes:
1. Rename `--skip-broken-historical` to `--include-broken-historical` so that, by default, `--historical-apis` "just works".
1. `--qiskit-release-notes` is renamed to `--qiskit-legacy-release-notes`. 
- It now only checks <0.46. 
- `--current-apis` will check the release notes for the latest version, whereas before you had to remember to  specify `--qiskit-release-notes`
- For Qiskit 0.46+, `--historical-apis` will check the release note for each version, whereas before you had to …

Change internal link checker's Qiskit SDK strategy

---

.github/workflows/weekly-checks.yml
scripts/js/lib/links/ignores.ts

Closes https://github.com/Qiskit/documentation/issues/495. 
We are checking every Runtime and qiskit-ibm-transpiler version, plus Qiskit 0.46+. This PR makes it more explicit and precise which links we have to ignore to get that green. That reduces the risk of false positives.
This PR also now has the external link checker check every single Qiskit version, whereas before it skipped historical links. It's important we don't have 404s, even for old docs. Note that the external link checker doesn't check GitHub source code links, which makes this change much less expensive.
The remaining issues are tracked by https://github.com/Qiskit/documentation/issues/1938.

Make link checker more precise

---

docs/guides/index.mdx

Page is getting long and could use the navigational guides. Also restores the option for a reader to vote on the page's helpfulness, and to report a bug on GitHub.

Add back page toc on intro-to-qiskit

---

docs/guides/functions.ipynb
docs/guides/ibm-circuit-function.ipynb

If a user's Qiskit Function errors, they need a traceback to identify how to fix their workload submission. 
Adding a few lines to Qiskit Functions docs to clarify how to pull this

Notes on fetching errors from Qiskit Functions

---

scripts/js/lib/links/extractLinks.ts
scripts/js/lib/links/ignores.ts

There is no easy way to check that an email address actually exists. Closes https://github.com/Qiskit/documentation/issues/1950.

Skip emails in internal link checker

---

docs/guides/latest-updates.mdx

Because we've had two new blogs released at about the same time, I am including both blog announcements rather than deleting the one that is only one day old. Normally we would only include one blog announcement at a time on the latest updates page.

Add performance blog announcement to the latest updates file

---

docs/guides/configure-error-mitigation.mdx
docs/guides/index.mdx
docs/guides/setup-channel.mdx

As of 18 Sep the Q-CTRL performance strategy will be deprecated. Removing mention of it in our docs.
Sneaking in a typo fix I found on the index page.

Remove mention of QCTRL performance strategy

---

scripts/pr-previews/poll_deployment.py

I had a [job](https://github.com/Qiskit/documentation/actions/runs/10999772330/job/30540690617?pr=2015) fail even though the [deployment](https://github.com/Qiskit/documentation/actions/runs/10999819575) succeeded. The script just timed out a little early. This PR bumps the timeout to 3mins, and increases the interval a bit to reduce the number of requests we make.

Increase timeout for PR previews

---

docs/guides/serverless-manage-resources.ipynb

This makes the code examples runnable. Unfortunately we can't add tests just yet (will happen in #1960), but this does mean users will be able to run all the code on the page.
I've removed the section on automatic QPU selection after discussion with the serverless team. This feature is being developed but isn't ready just yet. We'll add the section back in when it's ready.

Fix code examples in "Manage Qiskit Serverless compute and data resources"

---

.github/workflows/main.yml
docs/guides/bit-ordering.mdx
start

CI can fail if `docker pull ...` takes longer than expected. This PR adds a `--pull-only` option to `./start`, then waits for it to complete in CI.

Wait for docker pull in CI

---

docs/guides/ibm-circuit-function.ipynb

As an effort to unify the interfaces of all circuit functions, IBM circuit function has renamed the `backend` parameter to `backend_name`, and removed `precision` (since there is already `default_precision` in the options). This PR updates the docs accordingly.

Update ibm cf parameter names

---

scripts/js/lib/links/ignores.ts

Closes https://github.com/Qiskit/documentation/issues/2008 and https://github.com/Qiskit/documentation/issues/1944. Some of the broken links are false positives, whereas some are true positives that actually 404. The actual errors are tracked by https://github.com/Qiskit/documentation/issues/2029.

Classify broken external links in link ignores

---

scripts/js/commands/checkInternalLinks.ts
scripts/js/lib/links/ignores.ts

Closes https://github.com/Qiskit/documentation/issues/1955.
We remove `--include-broken-historical` since that no longer makes sense. However, we still keep the `skipVersions` mechanism in the code itself to facilitate temporarily changing the script locally to only check certain versions.

Check all historical Qiskit internal links

---

docs/guides/job-limits.mdx

The unicode times symbol was rendering as an $x$. Trying to replace it with $\times$.

Fix rendering of times symbol on job limits page

---

.github/workflows/main.yml
.github/workflows/notebook-test.yml
docs/guides/ibm-circuit-function.ipynb
scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py
scripts/nb-tester/test/test_notebook_classification.py

Closes https://github.com/Qiskit/documentation/issues/1649.
1. Don't run the last three steps if earlier steps failed.
- We were missing `if: success()`
2. Move the lint job to normal CI. 
- This is useful because it means we won't accidentally merge something with bad linting. That was possible before because the Execute notebooks job is expected to fail on forks, although it is still important the lint job passes.
- We already were setting up the Python environment in main CI, so there is not much downside to this
3. Don't fail CI if none of the notebooks could have been tested anyways because they're not mockable, e.g. `hello-world`.
Now the failure looks like this:

Improve fork behavior for notebook job

---

docs/guides/execution-modes.mdx
docs/guides/run-jobs-session.mdx

Clarify ITTL.
Add note that a session will auto-close if nothing has been submitted to it in 30 minutes.

Add clarifications to execution modes docs

---

scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py

Fixes https://github.com/Qiskit/documentation/pull/2062. 
While we now correctly detect in forks when no notebooks need to be run, we still were trying to call cleanup code, even though there are no jobs to clean up. That cleanup code requires logging into Runtime, so it fails on forks.
Instead, we should early exit if there are no notebooks to run.

Fix forks running job cancellation code in PRs

---

docs/guides/execution-modes.mdx

This broke the Runtime release notes.

Fix broken anchor link from execution modes rewrite

---

scripts/js/lib/links/ExternalLink.test.ts
scripts/js/lib/links/ExternalLink.ts

We weren't properly catching errors due to reusing the symbol `error`. That resulted in a test recently saying that a link we expected to 404 was instead a valid link.
This PR also improves the tests to be deterministic by mocking `fetch()`. This removes the risk of flakiness and makes our test faster.

Fix external link checker exception handling

---

.github/workflows/dev-docs-sync.yml

The dev docs sync PR is correctly running and regenerating the dev docs, but it's skipping the step to open PRs. This is because `@frankharkins` pointed out tj-actions/changed-files compares files across branches, rather than based on the current working directory.

Fix dev docs sync detection of changed files

---

scripts/js/lib/links/InternalLink.test.ts
scripts/js/lib/links/InternalLink.ts

Closes https://github.com/Qiskit/documentation/issues/2159.
This change also results in more suggestions happening than we had before, as shown in the tests.

Fix suggestion for image link checker

---

docs/guides/algorithmiq-tem.ipynb

Updating the Algorithmiq TEM documentation in the Example section. The parameter `max_execution_time` was removed.

Algorithmiq TEM documentation: change parameter in example

---

.prettierignore
README.md

Closes #2173. Also documents the `CodeAssistantAdmonition` component.

Add instructions for `CodeCellPlaceholder` component

---

README.md
start

Closes https://github.com/Qiskit/documentation/issues/1611. Now users don't have to manually run `docker pull` to get the latest version of the image. The responsibility moves from everyday users to the maintainers of the Docker image; we now need to open a PR to update the digest.
The approach of using a digest—rather than a tag—works great because it is auto-computed by Docker. The publisher can still keep simply publishing the `:latest` tag without having to manually set the digest. 
PR previews will continue to use `:latest` for `icr.io/qc-open-source-docs-prod/preview-builder`. They don't persist the image across jobs, so they will already have the latest image every time.
Note that security best practices recommend using digests rather than tags when building and deploying apps. …

Ensure `./start` is always up-to-date by using image digest

---

scripts/js/lib/api/updateLinks.test.ts
scripts/js/lib/api/updateLinks.ts

Fixes https://github.com/Qiskit/documentation/pull/2177. We weren't normalizing the hash in all cases.

Fix hash capitalization in API links

---

docs/api/qiskit-ibm-runtime/0.30/_toc.json
docs/api/qiskit-ibm-transpiler/0.3/_toc.json
docs/api/qiskit-ibm-transpiler/0.4/_toc.json
docs/api/qiskit-ibm-transpiler/0.5/_toc.json
docs/api/qiskit-ibm-transpiler/0.6/_toc.json
docs/api/qiskit-ibm-transpiler/_toc.json
docs/api/qiskit-ibm-transpiler/release-notes.mdx
docs/api/qiskit/0.19/qiskit.optimization.applications.ising.tsp.mdx
docs/api/qiskit/0.24/qiskit.optimization.applications.ising.tsp.mdx
docs/api/qiskit/0.25/qiskit.optimization.applications.ising.tsp.mdx
docs/api/qiskit/0.26/qiskit.optimization.applications.ising.tsp.mdx
docs/api/qiskit/0.27/qiskit.optimization.applications.ising.tsp.mdx
docs/api/qiskit/0.28/qiskit.optimization.applications.ising.tsp.mdx
docs/api/qiskit/0.29/qiskit.optimization.applications.ising.tsp.mdx
docs/api/qiskit/0.30/qiskit.optimization.applications.ising.tsp.mdx
docs/api/qiskit/0.31/qiskit.optimization.applications.ising.tsp.mdx
docs/api/qiskit/0.32/qiskit.optimization.applications.ising.tsp.mdx

Generated with `npm run regen-apis`. I changed the Box artifacts for the Qiskit docs to not have the broken links. Closes https://github.com/Qiskit/documentation/issues/2187.
Also applies https://github.com/Qiskit/documentation/pull/2195 to qiskit-ibm-transpiler - I forgot to regen.

Regen API docs to remove broken external links

---

scripts/js/lib/links/extractLinks.test.ts
scripts/js/lib/links/extractLinks.ts

The link checker was failing to detect inline class methods (related to https://github.com/Qiskit/documentation/issues/2210) because it does not peek inside `<Class>` components.
To fix this, we now use our own parsing code for headings. 
It's possible there will be future edge cases this PR does not account for in its heading parsing. Our link checker will fail in that case and we can forward fix.

Link checker parses headings inside component

---

docs/guides/addons.mdx

This adds qiskit-addon-aqc-tensor to the docs page.
Notes:
- Currently, this addon's tutorial is phrased as step 2 of a Qiskit pattern.  However, after gaining experience with it, I believe it actually fits in better as step 1.  I plan to update the tutorial, but in the meantime I've proposed it here under "Addons for mapping."
- I wrote a new description for it here, motivated by the desire to be consistent with both (i) unitary AQC, which will likely be added soon, and (ii) the phrasing as a "step 1" operation.

Add qiskit-addon-aqc-tensor to addons.mdx

---

docs/guides/save-jobs.ipynb
scripts/config/notebook-testing.toml
scripts/js/lib/links/ignores.ts

The notebook is failing with this:
```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
Cell In[2], line 3
1 # Get ID of most recent successful job for demonstration.
2 # This will not work if you've never successfully run a job.
----> 3 successful_job = next(jforjinservice.jobs()ifj.status().name=="DONE")
4 job_id = successful_job.job_id()
5 print(job_id)
StopIteration: 
```
Also closes https://github.com/Qiskit/documentation/issues/2277 by ignoring a valid link.

Stop running save-jobs notebook in CI for now

---

scripts/js/commands/checkPatternsIndex.ts

We were complaining that the index pages don't show up in the left ToC - that error didn't make sense and was only an oversight.
For some reason, `/guides/circuit-library` was also allowlisted to not be in the left ToC even though it is there.

Remove false positives from checkPatternsIndex.ts

---

docs/api/qiskit/0.19/qiskit.aqua.algorithms.MinimumEigensolver.mdx
docs/api/qiskit/0.19/qiskit.aqua.components.oracles.Oracle.mdx
docs/api/qiskit/0.19/qiskit.aqua.operators.OperatorBase.mdx
docs/api/qiskit/0.19/qiskit.aqua.operators.legacy.LegacyBaseOperator.mdx
scripts/js/lib/api/generateApiComponents.ts
scripts/js/lib/api/htmlToMd.test.ts
scripts/js/lib/api/processHtml.test.ts

Part of https://github.com/Qiskit/documentation/issues/2330.
Our old code would try to remove modifiers for `py.attribute`, but that was not necessary because they cannot be set. (An attribute is the default, like setting a value in `__init__`; a property is when you set `@property` on a function)
Modifiers are only set on properties. This is evidenced by `npm run regen-api` not changing despite removing code to handle `py.attribute`.
For a typical end-user, an attribute and `property` are essentially the same. The only time I think it'd be relevant is if you're subclassing the class; otherwise, I think `property` is distracting.
So, we continue to not preserve `property`, the same as before.
We capture the whole `abstract property` because the phrase is much more meaningful than …

Handle abstract properties

---

scripts/config/notebook-testing.toml

The OBP notebook can't be tested with our mocking technique. This PR fixes CI by ignoring that notebook so it'll only get tested during our fortnightly cron job. Tested by running `tox` locally.

Fix notebook CI

---

scripts/js/lib/links/FileBatch.ts
scripts/js/lib/links/ignores.ts

This PR adds a new mechanism to ignore links where we can add a regex expression to ignore all the URLs that match it. It adds regexes for the non-API docs in the addons' and runtime's objects.inv.
Closes #2296

Link checker: Add a method to ignore non-API docs for objects.inv

---

docs/guides/qiskit-code-assistant-local.mdx

Closes https://github.com/Qiskit/documentation/issues/2335. We decided it's more clear to users to show the links as code rather than normal external links, since they would 404.

Escape localhost links as code

---

start

Closes https://github.com/Qiskit/documentation/issues/2330. Brings in the closed source change needed to render `abstract property`.

Update preview image for `abstract property` support

---

docs/guides/runtime-options-overview.mdx

qiskit-ibm-runtime 0.32.0 released today includes a new DD option `skip_reset_qubits`.
https://github.com/Qiskit/qiskit-ibm-runtime/releases/tag/0.32.0
https://github.com/Qiskit/qiskit-ibm-runtime/pull/1981

Add `skip_reset_qubits` option for DD

---

README.md

We recently fixed DefinitionTooltip being broken due to a styling change we had made to fix the scroll behavior of inline Latex. However, we could not easily fix an edge case where you have both a DefinitionTooltip and the Latex in the _same_ paragraph. So, for now, we document the edge case.

Warn about using Latex with DefinitionTooltip

---

scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py

Migrating from #2344
Effectively allows the nb-tester script to be run against any backend. Also allows you to pass authentication and configuration directly to QiskitRuntimeService (if preferred).
Here's an example of how you can use the new changes to run a set of notebooks against test_eagle using qiskit_ibm_runtime:
```
test-docs-notebooks --config-path scripts/config/notebook-testing.toml --provider "qiskit_ibm_runtime" --backend "test_eagle2"
```
By default, `--provider` is set to `qiskit_fake_provider`, which runs the same provider code that was present in nb_tester before. By changing the provider, you can also specify "runtime_fake_provider" to use the fake_providers in `qiskit_ibm_runtime.fake_provider`, or "qiskit_ibm_runtime" to rely on real backends, and the credentials …

Add params to nb-tester

---

docs/guides/save-circuits.ipynb
docs/guides/save-jobs.ipynb
docs/guides/serverless-first-program.ipynb
scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py

We have some notebooks that write files to disk. At the moment, running these notebooks through `tox` means these notebooks use the docs repo as their working directory and will write files there. This is problematic for a couple of reasons:
1. Notebooks that write to disk can interfere with eachother. For example, two notebooks may try to write/read from the same file.
2. Notebook failures (or killing the script) will leave working files in the repo.
This PR solves the problem by modifying the script to execute each notebook in its own temporary directory.

Execute each notebook in its own temporary directory

---

scripts/js/lib/links/ignores.ts

Part of https://github.com/Qiskit/documentation/issues/2379. The other link https://arxiv.org/abs/2307.17405 is actually broken and I've asked the addons team to fix it.

Ignore valid external link

---

docs/guides/serverless-manage-resources.ipynb
scripts/config/notebook-testing.toml

Fixes #2325 and adds some tests.
I couldn't get the file download functionality working. I believe it's actually impossible at the moment so I'm removing it from the docs. When https://github.com/Qiskit/qiskit-serverless/issues/1544 is closed, we can add it back in.

Fix `serverless-manage-resources.ipynb`

---

.github/workflows/notebook-test.yml

Another slip-up in CI (sorry!)
There isn't really a good way to test these actions so we sometimes have to wait for edge cases to come up.

Fix notebook testing action

---

docs/guides/runtime-options-overview.mdx

Add `ibm_brisbane` and `ibm_strasbourg` to the gen3-turbo enabled backend list.

Add additional backends for gen3-turbo

---

.github/workflows/notebook-test-cron.yml
.github/workflows/notebook-test.yml
scripts/ci/check-all-notebooks-are-tested.py
scripts/config/notebook-testing.toml
scripts/nb-tester/README.md
scripts/nb-tester/patches/qiskit-fake-provider
scripts/nb-tester/patches/qiskit-ibm-runtime
scripts/nb-tester/patches/runtime-fake-provider
scripts/nb-tester/pyproject.toml
scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py
scripts/nb-tester/qiskit_docs_notebook_tester/config.py
scripts/nb-tester/test/test_get_notebook_jobs.py

Attempt to simplify the way we control `nb-tester`.
This PR includes the patch information in the config file. Like before, each notebook is part of a group. The new aspect is each group can define how to patch each notebook in different situations.
This PR also adds tests and documentation for the config part of the script. If you exclude the new README and tests, this PR reduces the script size by ~100 LOC.
Take the following config file as an example.
```toml
[my-group]
test-strategy.ci = { patch="qiskit_ibm_runtime", backend="test-eagle" }
test-strategy.hardware = {}
notebooks = ["..."]
```
If we run nb-tester against this file with `--test-strategy=ci`, each notebook in the group will be patched with the `test-eagle` device. If we run it with `--test-strategy=hardware`, the notebooks …

Redesign nb-tester interface

---

scripts/image-tester/sphinx_alt_text_validator/verify_images.py

The linter had an encoding error when reading the files in Windows:
```bash
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "c:\qiskit-ibm-runtime\tools\verify_images.py", line 108, in <module>
main()
File "c:\qiskit-ibm-runtime\tools\verify_images.py", line 83, in main
results = pool.map(validate_image, files)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\multiprocessing\pool.py", line 367, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python312\Lib\multiprocessing\pool.py", line 774, in get
raise self._value
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1420: character maps to <undefined>
```

Fix sphinx-alt-text-validator encoding error in Windows

---

scripts/config/notebook-testing.toml
scripts/nb-tester/patches/qiskit-ibm-runtime-open

This PR adds a new patch that picks the least busy backend that's also available on the open plan, regardless of which instance you're using.
We need this because we've added the `test_eagle_us-east` device to the instance we use for testing. The problem is that this device is always the least busy, so it'll be selected when we're doing our hardware runs. We can't just switch to the open instance for this test because I'm regularly out of credits and the priority is too low to run all the jobs in our time window.

Add nb-tester patch to only select open plan backends

---

scripts/nb-tester/README.md
scripts/nb-tester/patches/qiskit-ibm-runtime-open
scripts/nb-tester/qiskit_docs_notebook_tester/config.py

By default, nb-tester will **not** allow writing patched notebooks to disk. This is to reduce the risk of accidentally displaying results from patched notebooks to users. For example, if we write the output of a notebook patched with `qiskit-fake-provider`, it will appear the results in the notebook come from the least busy IBM Quantum backend when they actually come from a noiseless simulator. This could be considered false advertising.
However, we do have patches with which it's safe to generate user-facing results. This PR adds the ability to allow writing results from these patches by adding the comment `# nb-tester: allow-write` anywhere in the patch file.
The built-in `qiskit-ibm-runtime-open` patch is an example of such a patch: It only selects a real hardware backend that's …

Allow writing nb-tester results with certain patches

---

README.md

I think this is the best place for it.

Explain how to use "New" pill

---

docs/guides/qiskit-transpiler-service.mdx
docs/guides/transpile-rest-api.mdx
scripts/js/commands/checkInternalLinks.ts
scripts/js/lib/links/ignores.ts

Progress towards https://github.com/Qiskit/documentation/issues/2476. Fixes some QTS links + ignores valid journal links from API docs.

Fix Qiskit Transpiler Service links

---

scripts/nb-tester/README.md

We already include docs on the config file and CLI, just need to explain how to install.

Add docs on installing nb-tester

---

.github/workflows/api-checks.yml
.github/workflows/main.yml
scripts/js/commands/checkImages.ts

This PR moves the check of the alt text check for API docs images to the api--checks job. See https://github.com/Qiskit/documentation/pull/2426#discussion_r1887618361

Check API images in the api-checks job

---

README.md
start

Closes https://github.com/Qiskit/documentation/issues/1607. There are two issues:
1. The shebang will be ignored, so you need to run `python ./start` instead of `./start`
2. Volume mounting with Docker on Windows uses Unix-style path, per https://medium.com/@kale.miller96/how-to-mount-your-current-working-directory-to-your-docker-container-in-windows-74e47fa104d7

Improve `./start` to work on Windows

---

scripts/js/commands/checkPagesRender.ts
scripts/js/commands/checkStaleImages.ts

Closes https://github.com/Qiskit/documentation/issues/2518.
We were before checking every image inside `await Promise.all()` and only logging results at the end. This is too slow to keep that much in memory, and it results in the experience feeling laggy to not get results until the very end.
Instead, it makes more sense to check one image at a time and eagerly report violations. 
Other improvements in this PR:
* Use ripgrep rather than git grep. The downside is requiring users have ripgrep installed, but this is a manual script we run with `npx tsx`, so it should be fine.
* Log progress every 20 images
* Add an allowlist.
<details><summary>example run</summary>
```
❌ image is unused: public/images/migration/dedicated_queue_no_jobs1.jpg
❌ image is unused: …
```

Fix performance of stale image check

---

README.md

See https://git-scm.com/docs/git-clone#Documentation/git-clone.txt-code--filtercodeemltfilter-specgtem. This option means we lazily download blobs. We use this technique in closed source's sync very well. It should not break Git history like git blame.

Document Git clone tip

---

README.md
scripts/js/lib/api/processHtml.ts
scripts/js/lib/api/saveImages.ts

Includes a feature flag as requested. This requires the user have ImageMagick installed.

Convert images to AVIF during API docs generation

---

docs/guides/construct-circuits.ipynb

Related to https://github.com/Qiskit/qiskit/pull/13616. It was noted that we do not have explanatory material on the concept of circuit depth; adding it here.

Add section on circuit depth to construct circuits pg

---

docs/guides/runtime-options-overview.mdx

`gen3-turbo` mode now supports parameter expressions. This PR removes the claim that we don't.

Remove the primitives incompatibility gen3-turbo+parameter expressions

---

scripts/config/historical-pages-to-latest.json
scripts/js/commands/api/generateHistoricalRedirects.ts

Fix `historical-pages-to-latest.json` for transpiler after https://github.com/Qiskit/documentation/pull/2588

Fix historical pages to latest qiskit-ibm-transpiler

---

docs/guides/runtime-options-overview.mdx

Gen3 execution path now supports measurement level 1. Removing the restriction from `gen3-turbo` list.

Remove meas level 1 limit on gen3 engine

---

scripts/js/lib/links/ignores.ts

The last generation of the runtime API docs ([here](https://github.com/Qiskit/documentation/pull/2620)), needed to set two temporary ignores. This PR removes them as they are not necessary anymore.

Remove temporary ignores

---

scripts/nb-tester/requirements.txt

Parital fix for #2638.
We've resisted adding this requirement for a while, but `docs/guides/q-ctrl-optimization-solver.ipynb` uses some features of networkx that rustworkx doesn't have (e.g. `random_regular_graph`). It's possible there are suitable replacements, but I don't know enough about the domain or graph theory to work that out. I think this is the best solution for now.

Add `networkx` requirement

---

docs/guides/_toc.json
docs/guides/qiskit-code-assistant-openai-api.mdx
qiskit_bot.yaml
scripts/config/cspell/dictionaries/qiskit.txt
scripts/js/commands/checkPatternsIndex.ts

This PR adds documentation about the new compatibility of the Qiskit Code Assistant with the OpenAI API completion endpoints.
Fixes #2662

Adding documentation about OpenAI API compatibility for the Qiskit Code Assistant

---

docs/guides/install-qiskit.mdx
docs/open-source/qiskit-sdk-version-strategy.mdx

This commit updates the documentation for the pending 2.0.0 release to include the changes to platform support for Qiskit 2.0 and the versioning strategy.
Closes #2570

Update versioning and platform support for 2.0

---

.prettierignore
README.md
mdx-guide.md
scripts/nb-tester/README.md
style-guide.md

Our README has gotten pretty overwhelming. This PR tries to improve it by splitting into three guides:
* README.md
- entry point
- how to install the project
- how to run checks
* mdx-guide.md: how to write MDX & set up new pages
* style-guide.md: guidance on things like tone
This also adds guidance on how to have platform-specific pages, which was written by `@frankharkins` in closed source.

Revamp README by creating a separate MDX guide

---

docs/guides/job-limits.mdx

Closes #2736.
Waiting to merge this until gen3 is deployed on dedicated systems (sometime this week, so aiming to merge early next week - week of March 17)

Updates to job limits

---

scripts/js/commands/checkOrphanPages.ts

I nerd-sniped myself into this change. I was trying to improve the performance of the orphan check for https://github.com/Qiskit/documentation/issues/2800 by using `Promises.all()`, but it turns out it barely makes an improvement.
This PR:
```
❯ hyperfine "npx tsx scripts/js/commands/checkOrphanPages.ts -- --apis" 
Benchmark 1: npx tsx scripts/js/commands/checkOrphanPages.ts -- --apis
Time (mean ± σ):     587.6 ms ±  14.6 ms    [User: 778.5 ms, System: 155.7 ms]
Range (min … max):   567.8 ms … 621.2 ms    10 runs
```
Main branch:
```
❯ hyperfine "npx tsx scripts/js/commands/checkOrphanPages.ts -- --apis"
Benchmark 1: npx tsx scripts/js/commands/checkOrphanPages.ts -- --apis
Time (mean ± σ):     592.6 ms ±  18.8 ms    [User: 781.1 ms, System: 153.7 ms]
Range (min … max):   570.7 ms … 631.7 …
```

Refactor checkOrphanPages.ts

---

docs/guides/primitives.mdx
docs/migration-guides/external-providers-primitives-v2.mdx
docs/migration-guides/qiskit-runtime.mdx

Currently, we only document the "why" of primitives in the migration guides.

Document why we use primitives in a regular guide

---

.github/workflows/main.yml
.github/workflows/notebook-test-extended.yml
.github/workflows/notebook-test.yml

We continue pinning to an exact commit for better security. General context: https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised#stepsecurity-harden-runner.

Use more modern version of changed-files action

---

scripts/js/lib/api/Metadata.ts
scripts/js/lib/api/Pkg.ts
scripts/js/lib/api/conversionPipeline.ts
scripts/js/lib/api/generateApiComponents.ts
scripts/js/lib/api/generateToc.ts
scripts/js/lib/api/processHtml.ts

This PR makes three changes to the API generation script:
- **Recognize C `typedef` and format as class**
- **Do not use dedicated pages in C API**
In Python APIs, if a class has the same name as the page name, the page will be a "dedicated page" for that class. This commit disables that for the C API. The C API pages are a grouping of structs and associated functions, rather than a class and its methods. This change reflects that in the information heirarchy.
- **Fix TOC for C API**
C does not have modules, so we can't group pages by module. This commit just lists all C API pages in the TOC.

Tweaks to C API parser

---

scripts/js/lib/api/Metadata.ts
scripts/js/lib/api/generateApiComponents.ts
scripts/js/lib/api/htmlToMd.ts
scripts/js/lib/api/processHtml.ts

Small refactor to keep information about API types in one place. This should make it a little cleaner to add new API types.
In addition to running the regular tests, I also ran `npm run regen-apis` up to Qiskit v0.42.0 then checked the following command had no output.
```
git diff f9acc9098af856cc11eadfa863baf4afa69b959c --name-only | grep -v '\.avif$'
```

Refactor API types

---

scripts/js/lib/api/Metadata.ts
scripts/js/lib/api/generateApiComponents.ts

This just makes the script recognise struct members, we're still working out how to best display them.

Handle struct members in C API

---

scripts/js/lib/api/processHtml.ts

This removes the "Public members" rubric from structs in the C API docs. This is because the rubric appears to have the same level at the fields themselves. We decided the best solution to avoid a confusing information hierarcy is to remove the rubric.

Remove 'Public members' rubric

---

scripts/js/lib/api/processHtml.test.ts
scripts/js/lib/api/processHtml.ts

Currently, we're looking for an ID attribute starting with `group__` to work out if a page is a module or not. This isn't very robust because the `group__` ID only appears if there's a `doxygengroup` in the page, which isn't always the case.
Instead, this PR treats all pages as modules except the index page and the release notes page, which we identify by their `<h1>`.

Fix C API metadata handling

---

check
fix
scripts/tool_runner/__init__.py

Closes https://github.com/Qiskit/documentation/issues/2800. (Performance improvements are now tracked by https://github.com/Qiskit/documentation/issues/2854)
Success:
```
❯ ./check
✅ Notebook linters (1/8)
✅ patterns index pages (2/8)
✅ Qiskit Bot (3/8)
✅ metadata (4/8)
✅ images (5/8)
✅ orphan pages (6/8)
✅ spelling (7/8)
✅ internal links (8/8)
🎉 All checks passed!
```
For failure, we add a divider and indent by 2 spaces:
```
❯ ./check
✅ Notebook linters (1/8)
❌ patterns index pages
——————————————————————————————————————————————————
> qiskit-documentation@0.1.0 check:patterns-index
> tsx scripts/js/commands/checkPatternsIndex.ts
❌ The entry /guides/measure-qubits is not present on any index page
Add the entries in one of the following index pages, or add the URL to the `IGNORED_URLS` list …
```

Improve logging for `./check` and `./fix`

---

scripts/js/lib/api/Pkg.ts
scripts/js/lib/api/generateToc.ts

The Qiskit C API release notes should just be a link to the Qiskit release notes. This PR implements that.

Point Qiskit C API release notes to Qiskit release notes

---

docs/guides/job-limits.mdx
docs/guides/runtime-options-overview.mdx

Both the gate limits and `gen3-turbo` backend limits have changed. This PR updates them to the new values.

Update with new limits

---

docs/api/qiskit-addon-aqc-tensor/simulation.mdx
scripts/js/lib/api/generateApiComponents.ts

Closes https://github.com/Qiskit/documentation/issues/2792
`qiskit-addon-aqc-tensor` is using the "multiple dispatch" paradigm which results in Sphinx nesting functions inside functions. In these cases, the nested functions don't have any ID defined. 
Here is an example of how Sphinx renders the `tensornetwork_from_circuit` function:
<details><summary>Screenshot</summary>
</details>
This PR changes the MDX pipeline to stop assuming that every function will have an ID defined. If the ID is not defined the pipeline won't create a new empty heading matching that way the Sphinx output.
<details><summary>Screenshot of the current live docs</summary>
</details>
<details><summary>Screenshot how the docs will look after this PR</summary>
</details>

Remove empty headings for Functions without ID

---

scripts/js/lib/api/releaseNotes.ts
scripts/js/lib/api/saveImages.ts

For the C API, we link to Qiskit's Python API release notes. However, we were still generating the release notes page for the C API, just not using it. This PR skips the release notes generation in the conversion pipeline.

Skip generating release notes for C API docs

---

.github/workflows/main.yml
.github/workflows/notebook-test-extended.yml
.github/workflows/notebook-test.yml

The new action is broken for `separator`, which is blocking https://github.com/Qiskit/documentation/pull/2757.
We will find a minimum reproduction & file an issue with their repository.
We had landed https://github.com/Qiskit/documentation/pull/2757 out of an abundance-of-caution to address https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised#stepsecurity-harden-runner. The security team wanted us to be using the latest version of the action.
However, it was not actually necessary to land https://github.com/Qiskit/documentation/pull/2757 because the prior commit we pinned to was not compromised. There is no known CVE with the old pinned commit.
While it's generally a good idea to use the latest version of deps, it is not strictly …

Revert "Use more modern version of changed-files action (#2814)"

---

scripts/js/commands/api/updateApiDocs.ts
scripts/js/lib/apiVersions.ts

Closes https://github.com/Qiskit/documentation/issues/2879
This PR adds a mechanism to catch when a version is incomplete when running `npm run gen-api`

Error when API versions are incomplete

---

scripts/js/commands/checkStaleImages.ts

None of our open source images are used anymore in closed source files. Furthermore, we are almost finished moving all of our closed source content to now live in open source, so there isn't even a concept any more of closed-source images.

Remove stale image check warning about closed source

---

scripts/nb-tester/requirements.txt

We pinned this temporarily to unblock CI, but it shouldn't be needed any more.

Unpin osqp

---

.github/workflows/notebook-test-cron.yml
.github/workflows/notebook-test.yml

I didn't realize this has been running on forks: https://github.com/Gyan-max/documentation/pull/2. It shouldn't be, and will result in issues with contributors who merge those PRs to `main`.

Turn off cron job for forks

---

scripts/nb-tester/qiskit_docs_notebook_tester/patches/qiskit-ibm-runtime-inline

This new patch ensures that the QiskitRuntimeService exists correctly, and collects each parameter inline (except for the token, which is fetched from the "DOCS_QISKIT_TOKEN" environment variable). This method of patching is helpful for running nb-tester in a controlled environment (like a docker image).

Adds inline patch for qiskit-ibm-runtime

---

docs/guides/cloud-account-structure.mdx
docs/guides/manage-appid.mdx
scripts/config/cspell/dictionaries/people.txt
scripts/js/commands/checkSpelling.ts

Turns out the spellcheck won't block CI if it finds an error in an MDX file, only notebooks.

Fix spellcheck CI

---

scripts/ci/check-for-version-info-cells.py
tox.ini

Checks that all notebooks have a markdown cell with tag `version-info`. We add these cells so the notebook tester knows where to insert package version information so users can see which package versions were used to run the notebook.

Check all notebooks contain `version-info` cells

---

scripts/js/commands/checkSpelling.ts

Prework for https://github.com/Qiskit/documentation/issues/2914. This makes the code more generic so that we can add more content types than MDX and Jupyter.

Refactor checkSpelling.ts

---

check

This is checked in CI but not in the local `./check`

Add notebook categorization check to `./check`

---

docs/migration-guides/qiskit-2.0.mdx

Fix link in migration guide

---

.github/workflows/dev-docs-sync.yml

The dev docs sync runs every day and we often have a few dev docs PRs open at a time which means many are usually not merged. This PR reduces the frequency to run only three times a week, avoiding weekends.

[Suggestion]: Reduce frequency of dev docs sync

---

scripts/config/cspell/cSpell.json

#2965 added support to spellcheck TOCs, but this has the side-effect of also checking URLs.
Unfortunately, there are some words that are valid in a URL but shouldn't be added to the dictionary as they're not valid elsewhere. One example of this is `grovers`; usually this should be corrected to `Grover's`, but it _is_ valid in a URL. 
Since we can't add file-level ignores in the `_toc.json`, I think the best approach is to ignore these URLs using a regex.
This is not a problem on `main`, but it's blocking CI in #2978.

Do not spellcheck URLs

---

scripts/config/api-html-artifacts.json
scripts/js/commands/api/syncDevDocs.ts
scripts/js/commands/api/updateApiDocs.ts
scripts/js/lib/api/Pkg.ts
scripts/js/lib/api/sphinxArtifacts.ts

This PR combines the generation of Qiskit's Python and C APIs into a single pipeline. Both these APIs use the same artifact and should be generated at the same time.
***
Closes #2863 and closes #2900.

Unify Python and C API generation

---

docs/guides/q-ctrl-optimization-solver.ipynb
docs/guides/q-ctrl-performance-management.ipynb

ibm_kyiv has been retired, this PR removes mention of it from documentation guides for the Q-CTRL qiskit functions.

chore: Remove retired device ibm_kyiv from docs guides

---

start

This is a prework for https://github.com/Qiskit/documentation/pull/2958 and https://github.com/Qiskit/documentation/pull/2973. The new image, removes the `/docs` segment from the links if needed.

Update preview hash

---

docs/guides/retired-qpus.mdx

ibm_kyiv, 127-qubit QPU, has been retired as of Friday 18 April 2025.

Add ibm_kyiv to retired QPUs list

---

.github/workflows/pr-cleanup.yml
scripts/pr-previews/cleanup.py

Part of #2799.
This PR changes the PR preview cleanup to squash all commits on the branch, and to run at midnight rather than every push to `main`.

Squash `gh-pages` commit history every night

---

.gitignore

Writers sometimes use new notebooks as scratch pads and it can be annoying when they show up in version control. This PR ignores unnamed notebooks (called `Untitled` by default). This is safe as we'll never want to commit an unnamed notebook. I wouldn't recommend adding this as a global ignore rule because I have seen other repos with `Untitled.ipynb` committed.

Ignore `Untitled*.ipynb` files

---

.github/ISSUE_TEMPLATE/courses.yaml
.github/ISSUE_TEMPLATE/guides.yaml

"tutorial" is copied in all three types of issue template.

Fix mislabeled section of issue templates

---

docs/guides/plans-overview.mdx

This PR removes the `isNew` tag from the plan overview metadata.

Remove isNew pill from plans overview

---

start

This PR updates the image digest from the `start` script. The new image allows the user to override the dividers from the TOC.

Update docker digest from start script

---

README.md

Running `git fetch` is very slow in this repository because of the `gh-pages` branch, even though you never use that locally. https://stackoverflow.com/a/64439191 says how to ignore the branch.

Document how to ignore gh-pages branch

---

docs/guides/qiskit-addons-aqc.mdx

This updates it so AQC consistently is expanded as "approximate quantum compilation"
This content was originally added in #2291.

AQC = approximate quantum compilation

---

docs/guides/max-execution-time.mdx
docs/guides/minimize-time.mdx
docs/guides/noise-learning.ipynb

Some minor fixes to the pages on timing, including
- Use the same wording to describe quantum time
- Change `QPU-calculated max execution time` to `service-calculated`, since QPU is just hardware
- Fix hyperlink text to match the new topic names
- Add wording on minimizing run time for estimator jobs

Minor fixes to the timing pages

---

docs/guides/run-jobs-batch.mdx
docs/guides/run-jobs-session.mdx

@jyu00 noticed that when I updated the batch max TTL, I needed to also update the session max TTL.

Update session max TTL 

---

docs/guides/fair-share-scheduler.mdx

Mention on fair-share-scheduler page that the 28-day rolling window only applies to Premium, not Flex Plan.

Specify rolling plan is for Premium only

---

docs/guides/circuit-library.ipynb
docs/guides/qiskit-addons-mpf-get-started.ipynb
scripts/nb-tester/qiskit_docs_notebook_tester/config.py
tox.ini

Closes #2716 
According to the official python docs, `PendingDeprecation` warnings are [ignored by default](https://docs.python.org/3/library/exceptions.html#PendingDeprecationWarning) unless [Python Development Mode](https://docs.python.org/3/library/devmode.html) is enabled (done either through the `-Xdev` or `-Wd` flags when invoking `python` or by setting the environment variable `PYTHONDEVMODE=1`). 
This PR sets the `tox` environment to run using dev mode with the `PYTHONDEVMODE` env var.

Update testing env to include `PendingDeprecation` warnings

---

.github/ISSUE_TEMPLATE/courses.yaml
.github/ISSUE_TEMPLATE/guides.yaml
.github/ISSUE_TEMPLATE/tutorials.yaml
.github/ISSUE_TEMPLATE/ui.yml

@Qiskit/docs-content-team now exists and tags @beckykd and @abbycross. Adding to our issue templates.

Use docs-content-team tag in issue templates

---

.github/ISSUE_TEMPLATE/courses.yaml
.github/ISSUE_TEMPLATE/guides.yaml
.github/ISSUE_TEMPLATE/tutorials.yaml
.github/ISSUE_TEMPLATE/ui.yml

The issue templates are not recognizing the Qiskit/docs-content-team so I am taking off the `Qiskit/` to see if that solves it.

Try to fix team tag in issue templates

---

.github/workflows/notebook-test-cron.yml

Adds the image extraction step to the notebook cron job.

Extract notebook image outputs after executing in cron job

---

docs/guides/run-jobs-batch.mdx

The expression "initializing the `Batch` class" might refer to the `__init__` call of a class. I think "passing a `Batch` instance to the parameter `mode=` of the primitive" is more correct.

Update run-jobs-batch.mdx to be more explicit about the wording

---

.prettierignore

We don't have Prettier running on files the content writers touch because they found it really annoying.

Prettier should skip learning folder

---

scripts/notebook-normalizer/qiskit_docs_notebook_normalizer/cell_output_data.py
scripts/notebook-normalizer/test/test_normalization.py

Originally, I was trying to do everything in-memory so we could push side-effects to the end of the program, but that didn't seem to work on Fedora for some reason. This works for me on OSX, and @kaelynj tested this out and it works on her Fedora machine.

Use tempfiles in image extraction

---

docs/guides/hello-world.ipynb

The Hello World guide seems to have a error (or potentially misleading statement) in its description of an expectation value. While it is true that the referenced expectation value is 1 for the specific entangled state created by the example circuit, that expectation value does not have to be 1 for all entangled states.

Fix small error

---

scripts/config/notebook-testing.toml

The was left in accidentally and doesn't point to a real notebook. The real notebook is listed correctly in [L159](https://github.com/Qiskit/documentation/pull/3189/files#diff-0eeb1ae761e24b8ec90fd935f7c9a5ab340a645115f863ef8bf58c4fa3ee7801R156-R160).

Fix typo in notebook config

---

docs/guides/qiskit-code-assistant-jupyterlab.mdx
docs/guides/qiskit-code-assistant-vscode.mdx
docs/guides/qiskit-code-assistant.mdx

Right now the Qiskit Code Assistant is not available through the new IBM Quantum platform. This PR adds references that it's available only for the users registered in the IBM Quantum Platform classic.

Adding references about the Qiskit Code Assistant service is available only through the IBM Quantum Platform classic

---

docs/guides/install-c-api.mdx

Following discussions around Qiskit/qiskit#14138 we decided to document explicitly that Qiskit's C API requires the C11 standard. So you need a C11 compatible C compiler to use the C API. This commit updates the C installation guide to document this requirement.

Document Qiskit C API compiler requirements

---

scripts/notebook-normalizer/qiskit_docs_notebook_normalizer/cell_output_data.py

This PR aims to fix the following error when running the notebook normalizer:
```
magick: improper image header `/var/folders/d1/z9l0cjmx5jn7nthr53czl1qm0000gn/T/tmpp5co82hx.png' @ error/png.c/ReadPNGImage/3947.
```
Given that the error is with the header, I suspect that magick wasn't able to read it when opening the images. This could be caused because after the `write`, the File Handle is not located at the beginning of the file.
This is an example of some positions printed after the `write` command for some images:
```
6560
41510
55567
54349
86080
104641
2564
```
This PR changes the File Handle position to the beginning of the file before running the magick command to prevent that

Fix magick improper header error

---

mdx-guide.md
start

This PR updates the docker image hash to bring the new IBMVideo component to the `start` preview and adds a brief description in the MDX guides.

Add `IBMVideo` component to the preview

---

learning/courses/basics-of-quantum-information/_toc.json
learning/courses/foundations-of-quantum-error-correction/_toc.json
learning/courses/fundamentals-of-quantum-algorithms/_toc.json
learning/courses/general-formulation-of-quantum-information/_toc.json
learning/courses/quantum-business-foundations/_toc.json
learning/courses/quantum-chem-with-vqe/_toc.json
learning/courses/quantum-computing-in-practice/_toc.json
learning/courses/quantum-diagonalization-algorithms/_toc.json
learning/courses/quantum-machine-learning/_toc.json
learning/courses/utility-scale-quantum-computing/_toc.json
learning/courses/variational-algorithm-design/_toc.json
learning/modules/computer-science/_toc.json
learning/modules/quantum-mechanics/_toc.json

Part of https://github.com/Qiskit/documentation/issues/3287
This PR updates the courses/modules TOC to:
- Add the following additional properties to the Overview page:
- useDivider
- preventBold
- Add a top-level subsection called "Lessons" (or "Modules") for all the pages
I used the script provided in the issue (kudos to @frankharkins) together with a small manual change (added some whitespace at the end of the files and fix the two modules subsections as said in the issue).
The only course left is "Practical Introduction to Quantum-Safe Cryptography", which hasn't been merged yet (https://github.com/Qiskit/documentation/pull/3303)

Update the TOC structure of the Learning courses/modules

---

docs/tutorials/real-time-benchmarking-for-qubit-selection.ipynb

Closes  #3197 where it was noted that the optimization setting chosen for the transpilation is not noise aware, thus the new calibrations are not used.

fix bug in real-time qubit selection tutorial

---

docs/tutorials/grovers-algorithm.ipynb

This PR is just a small change in one of the cells of the [Grover's tutorial notebook](https://learning.quantum.ibm.com/tutorial/grovers-algorithm) to consider the edge case where one of the marked states is all 1s.
Before this PR, doing something like this would fail:
```python
grover_oracle("111")
```
After this PR, it works as expected and the circuit contains no X gates in that edge case.
I have limited the change to that cell in the notebook, and I have not rerun the whole notebook to avoid modifying cells metadata and other irrelevant things.
Fixes: #3315

Fix `grover_oracle()`

---

docs/tutorials/krylov-quantum-diagonalization.ipynb

Closes https://github.com/Qiskit/documentation/issues/3202. See https://github.com/Qiskit/documentation/pull/3217 for the original PR.

Fix Krylov tutorial being Heron-specific

---

.github/actions/set-up-notebook-testing/action.yml
.github/workflows/main.yml
.github/workflows/notebook-test-cron.yml
.github/workflows/notebook-test-extended.yml
.github/workflows/notebook-test.yml
scripts/nb-tester/qiskit_docs_notebook_tester/config.py
scripts/nb-tester/qiskit_docs_notebook_tester/execute.py
scripts/nb-tester/qiskit_docs_notebook_tester/patches/qiskit-ibm-runtime-open
tox.ini

This PR migrates our notebook testing setup to use the IBM Cloud provider rather than the legacy provider.

Migrate testing to cloud

---

.github/actions/set-up-notebook-testing/action.yml

Previously, `save_account` would happily accept an empty string for the `token`, but this seems to have changed. Since some notebooks can be tested without a valid account, this PR adds a try/except to continue even if account setup fails. The existing script will give an appropriate error message if any notebooks fail on a fork.

[nb-tester]: Handle forks better

---

scripts/config/notebook-testing.toml
scripts/nb-tester/requirements.txt

This PR updates all Python dependencies used for testing to their latest versions.
We were blocked on this by #3363

Update notebook tester dependencies

---

README.md

The README is technically correct, but since we don't allow writing results from mocked runs, it still won't write results most of the time. This is a way to ensure results are written.

Update README with notebook execution information

---

.github/workflows/main.yml
.github/workflows/weekly-checks.yml
mdx-guide.md
scripts/js/commands/checkPagesRender.ts
start

This PR deletes the `platform` option from the `start` script. This is because we are removing the legacy app in inner source and from the preview app. It also simplifies the render checker to only verify cloud pages.
This change will be accompanied by a follow-up that finishes removing missing parts once we don't use any platform specific tag in the content.

Stop using the legacy app in previews

---

docs/guides/qiskit-code-assistant-local.mdx

We recently released new GGUF versions for the newer Qiskit Code Assistant models, which are specially useful to run the assistant locally in personal laptops. This PR adds this information and fixes #3453

Adding references to the new GGUF models released for the Qiskit Code Assistant

---

.github/workflows/notebook-test-cron.yml

This step was not running because the "Execute notebooks" step almost always fails. It should always be safe to run the normalization.

Always run notebook normalization in cron job

---

scripts/js/lib/links/extractLinks.test.ts
scripts/js/lib/links/extractLinks.ts

Our code wasn't accounting for headings that contain double and single quotes. I found this issue while working in translations. To find the behavior of the anchors with this type of titles, you can go to https://quantum.cloud.ibm.com/docs/en/guides/composer#click-run-on-qpu-name to see how the double quotes are removed.

Fix anchors detection for headings with single/double quotes

---

scripts/js/commands/checkPatternsIndex.ts

We no longer have platform-specific content.

Remove platform-specific workaround for patterns index check

---

docs/guides/stretch.mdx

Looks like we forgot to delete the QASM3 line in the stretch example, when converting to circuits.

Remove extra line in stretch example

---

docs/guides/install-c-api.mdx

This PR fixes a compilation error in the code example of the C API installation guide. 
Fixes #3689

Fix code example in the C API installation guide

---

docs/guides/cloud-setup-invited.mdx
docs/guides/cloud-setup-untrusted.mdx
docs/guides/cloud-setup.mdx

A user saved their account with a default instance but then initialized the `QiskitRuntimeService` with a token so the saved account was not used. This confusion caused them to mistakenly use a premium instance, thinking they were using the open instance. 
```python
QiskitRuntimeService.save_account(
token=token,
channel="ibm_quantum_platform",
instance=CRN
)
service = QiskitRuntimeService(channel="ibm_quantum_platform", token=token)
```

Clarify service init behavior

---

docs/guides/qasm-feature-table.mdx

The notes at the top of the table say that "full support" involves being able to load from OpenQASM 3, but a couple of the rows indicated "full support" and used the note to explain that this did not include loading from OQ3.
This corrects the table to label those rows as "partially supported", to clarify the note (which had caused confusion), and to explain that loading from OQ3 (into Qiskit) is not typically necessary for full-path submission in the majority case.
Fix #3681

Fix Qiskit's supported OpenQASM 3 feature table

---

docs/guides/install-qiskit-source.mdx

`pip install -r requirements-dev.txt` does not work for qiskit-ibm-runtime because we removed the requirements text files in https://github.com/Qiskit/qiskit-ibm-runtime/pull/2053

Update qiskit-ibm-runtime install from source instructions

---

docs/guides/custom-roles.mdx

Add missing info, and remove the unused actions on the Custom roles page. (See internal issue.)

updates to Custom roles: view analytics only section

---

docs/migration-guides/classic-iqp-to-cloud-iqp.mdx
docs/support/faq.mdx
docs/tutorials/compilation-methods-for-hamiltonian-simulation-circuits.ipynb
docs/tutorials/global-data-quantum-optimizer.ipynb

Closes some small PRs - 
fixes #3845 
fixes #3782
fixes https://github.com/Qiskit/documentation/issues/3629

Cleanup: header levels, missing comma in code, add 'citation'

---

.github/ISSUE_TEMPLATE/config.yml

New slack url is [qisk.it/join-slack](http://qisk.it/join-slack)
Thank you @abdonrd for flagging!

Update slack link in issue template

---

.github/ISSUE_TEMPLATE/translations.yaml

This PR adds a new issue template to report incorrect translations. The template asks for:
* The URL of the page
* Language containing the problem
* The full paragraph before the fix
* Correction of the entire paragraph
* Explanation of what the problem was

Add a new issue template for translations

---

docs/api/qiskit-ibm-runtime/release-notes.mdx

Part of https://github.com/Qiskit/documentation/issues/3787
This PR replaces a link in the qiskit-ibm-runtime release notes that was pointing to one of the archived migration guides.

Replace a broken link from the runtime release notes
