Qiskit/documentation

- .github/workflows/main.yml
- .github/workflows/preview-docs.yaml
- .gitignore
- README.md
- docs/placeholder.md
- package-lock.json
- package.json
- scripts/checkMetadata.js
- scripts/checkMetadata.ts
- tsconfig.json
In the closed source repository that consumes Qiskit/docs, we have this same check for valid file metadata. It is useful to run it here too so that we fail more eagerly.
Like the internal code, this uses TypeScript. It makes the code more readable and better aligned with the internal code.
> Check for valid metadata

- docs/build/qasm-circuits.mdx
- docs/run/index.mdx
I left these off in https://github.com/Qiskit/documentation/pull/70 on accident. The files are copy and pasted without changes.
> Migrate missing files from closed source

- docs/run/account-management.mdx
> Remove default

- .github/ISSUE_TEMPLATE/config.yml
More improvements to issue templates
> add URLs to linkouts on the open-an-issue page

- docs/run/algorithm-tuning-options.mdx
- docs/run/primitive-options.mdx
- docs/start/migrate.mdx
- docs/start/runtime.mdx
- docs/verify/noise.mdx
We missed these on accident, in the absence of the link checker.
> Fix bad internal links to optimize section

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/new-content.yaml
- .github/ISSUE_TEMPLATE/ui.yml
- .github/ISSUE_TEMPLATE/user-feedback.yml
Closes #149 
@tobi-lasisi FYI -- I'm adjusting the template to remove requests for any personal info, and adding the feedback program link to all our issue templates for broader reach.
> Update user feedback template

- .github/workflows/main.yml
- README.md
- package.json
- scripts/commands/checkLinks.ts
- Add ignore list
- Also ignore files in `docs/api`
- Add `npm run check:links` command
- Add to CI
- Update README
> Link checker update

- docs/run/max-execution-time.mdx
- docs/run/run-jobs-in-session.mdx
- docs/verify/_toc.json
Found some errors when copying over the changes for sessions
> Found some typos

- docs/api/migration-guides/__migration-guide-algorithms.md.txt
- docs/api/migration-guides/__migration-guide-opflow.md.txt
- docs/api/migration-guides/__migration-guide-qi.md.txt
Part of https://github.com/Qiskit/documentation/issues/213.
> Convert admonitions in Qiskit migration guides

- docs/build/classical-feedforward-and-control-flow.ipynb
- docs/run/run-jobs-in-session.mdx
- docs/run/sessions.mdx
> misc session fixes

- docs/run/_toc.json
- docs/run/advanced-runtime-options.mdx
- docs/run/configure-error-suppression.mdx
- docs/run/configure-runtime-compilation.mdx
* error suppression -> runtime compilation
* mark deprecated advanced options
* add language about the expectation of target circuits
> Configure error suppression updates

- docs/start/hello-world.ipynb
- docs/verify/simulate-with-qiskit-primitives.mdx
> Fix bad admonitions for Hello World

- docs/start/_toc.json
Change nav in response to Slack request from @javabster
> update Start toc

- docs/run/retired-systems.mdx
> add auckland to the retired systems list

- docs/run/run-jobs-in-session.mdx
Closes #258 
cc @AndreiConstantin00 @jyu00
> Refactor Run jobs in a session

- docs/run/run-jobs-in-session.mdx
- docs/start/setup-channel.mdx
The only allowed types are `note, tip, info, caution, danger` (source https://github.com/Qiskit/documentation/pull/414#pullrequestreview-1751092648).
> Change admonition types

- docs/transpile/_toc.json
We aren't ready to launch those pages yet live.
> Trim Transpile table of contents

- docs/run/retired-systems.mdx
> New example of retrieving retired QR jobs

- docs/run/quantum-serverless.mdx
> Update serverless docs to use qiskit patterns

- cSpell.json
- package.json
Closes https://github.com/Qiskit/documentation/issues/442.
> Spellcheck migration guides

- docs/run/run-jobs-in-session.mdx
> Add session import statement

- docs/transpile/_toc.json
> Collapse the transpile left nav bar

- docs/verify/building_noise_models.ipynb
> Switch transpile to passmanagers in "Building noise models"

- docs/api/migration-guides/qiskit-runtime.mdx
- docs/run/advanced-runtime-options.mdx
- docs/run/configure-runtime-compilation.mdx
- docs/transpile/_toc.json
- docs/transpile/ai-transpiler-passes.mdx
- docs/transpile/common-parameters.mdx
- docs/transpile/custom-transpiler-pass.ipynb
- docs/transpile/defaults-and-configuration-options.mdx
- docs/transpile/dynamical-decoupling-pass-manager.ipynb
- docs/transpile/index.mdx
- docs/transpile/qiskit-transpiler-service.mdx
- docs/transpile/representing_quantum_computers.mdx
- docs/transpile/set-optimization.mdx
- docs/transpile/transpile-with-pass-managers.ipynb
- docs/transpile/transpiler-stages.ipynb
> Add links to Transpile section

- docs/verify/building_noise_models.ipynb
- docs/verify/simulate-with-qiskit-aer.ipynb
- docs/verify/simulate-with-qiskit-primitives.mdx
- docs/verify/stabilizer-circuit-simulation.ipynb
- docs/verify/using-ibm-quantum-simulators.mdx
Part of https://github.com/Qiskit/documentation/issues/464
> Add Next steps to Verify section

- docs/build/bit-ordering.mdx
- docs/build/circuit-construction.ipynb
- docs/build/circuit-library.ipynb
- docs/build/circuit-visualization.ipynb
- docs/build/classical-feedforward-and-control-flow.ipynb
- docs/build/index.mdx
- docs/build/interoperate-qiskit-qasm2.mdx
- docs/build/interoperate-qiskit-qasm3.mdx
- docs/build/introduction-to-qasm.mdx
- docs/build/operators-overview.ipynb
- docs/build/pulse.ipynb
- docs/build/qasm-feature-table.mdx
- docs/build/specify-observables-pauli.mdx
- docs/build/unitary-synthesis.mdx
> Add next steps to build

- docs/run/configure-error-mitigation.mdx
- docs/run/configure-runtime-compilation.mdx
- docs/run/estimate-job-run-time.mdx
- docs/run/fair-share-queue.mdx
- docs/run/get-backend-information.ipynb
- docs/run/instances.mdx
- docs/run/max-execution-time.mdx
- docs/run/minimize-time.mdx
- docs/run/monitor-job.mdx
- docs/run/primitives-examples.mdx
- docs/run/run-jobs-batch.mdx
- docs/run/run-jobs-in-session.mdx
- docs/run/sessions.mdx
- docs/verify/_toc.json
- docs/verify/cloud-based-simulators.mdx
Closes #464 
I didn't add links to the topics that are purely reference, such as Retired systems.
> Add links to Run section

- docs/build/introduction-to-qasm.mdx
- docs/build/pulse.ipynb
Without this, the pages crash.
> Add missing closing tags for docs

- scripts/lib/sphinx/updateLinks.test.ts
- scripts/lib/sphinx/updateLinks.ts
Minor refactor in anticipation of upcoming work
> [Refactor]: Pull update url logic into own function

- docs/start/index.mdx
- scripts/commands/checkLinks.ts
Fix broken runtime link in start
> Fix broken link in start/index.mdx

- docs/api/qiskit-ibm-provider/_package.json
- docs/api/qiskit-ibm-provider/ibm_job.md
- docs/api/qiskit-ibm-provider/ibm_jupyter.md
- docs/api/qiskit-ibm-provider/ibm_transpiler.md
- docs/api/qiskit-ibm-provider/ibm_utils.md
- docs/api/qiskit-ibm-provider/ibm_visualization.md
- docs/api/qiskit-ibm-provider/index.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.IBMBackend.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.IBMBackendService.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.job.IBMCircuitJob.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.job.IBMCompositeJob.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.least_busy.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.ALAPScheduleAnalysis.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.ASAPScheduleAnalysis.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.BlockBasePadder.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.DynamicCircuitInstructionDurations.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.PadDelay.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.PadDynamicalDecoupling.md
- docs/api/qiskit-ibm-provider/qiskit_ibm_provider.transpiler.passes.scheduling.md
- docs/api/qiskit-ibm-provider/release-notes.md
This will result in the diff in https://github.com/Qiskit/documentation/issues/558 being more focused.
This also adds missing methods/attributes thanks to @arnaucasau's bug fix in https://github.com/Qiskit/documentation/pull/552.
> Update Provider docs to 0.7.3

- docs/api/migration-guides/qiskit-algorithms-module.mdx
- docs/api/migration-guides/qiskit-opflow-module.mdx
- docs/api/migration-guides/qiskit-quantum-instance.mdx
- docs/api/migration-guides/qiskit-runtime-examples.mdx
- docs/api/migration-guides/qiskit-runtime-from-provider.mdx
- docs/api/migration-guides/qiskit-runtime.mdx
- docs/build/qasm-feature-table.mdx
- docs/run/estimate-job-run-time.mdx
- docs/run/index.mdx
- docs/run/instances.mdx
- docs/run/primitives-get-started.mdx
- docs/run/primitives.mdx
- docs/run/quantum-serverless.mdx
- docs/run/run-jobs-in-session.mdx
- docs/run/system-information.mdx
- docs/start/configure-qiskit-local.mdx
- docs/start/install.mdx
- docs/transpile/ai-transpiler-passes.mdx
- docs/transpile/defaults-and-configuration-options.mdx
- docs/transpile/index.mdx
- docs/transpile/qiskit-transpiler-service.mdx
- docs/transpile/representing_quantum_computers.mdx
- docs/transpile/set-optimization.mdx
> Backend vs system

- docs/support.mdx
> Add citation information for composer

- .github/ISSUE_TEMPLATE/new-content.yaml
Partially fulfilling requirements for #284
> Update issue template

- docs/run/sessions.mdx
> Sessions don't work on sims

- docs/api/migration-guides/qiskit-runtime.mdx
Just playing with some formatting
> improve readability

- docs/api/qiskit/release-notes/0.42.md
- scripts/lib/links/ignores.ts
> Fix issues with broken links

- docs/build/interoperate-qiskit-qasm2.mdx
- docs/build/interoperate-qiskit-qasm3.mdx
- docs/transpile/common-parameters.mdx
Minor tweaks to make the code examples run. Closes #609.
> Minor fixes for markdown code examples

- docs/transpile/custom-transpiler-pass.ipynb
empty cell visible at the top of https://docs.quantum.ibm.com/transpile/custom-transpiler-pass
> delete empty jupyter cell

- docs/api/qiskit/release-notes/0.25.md
> Fix broken release note link

- docs/api/qiskit/_package.json
- scripts/lib/api/releaseNotes.ts
- Restore `_package.json` that was accidentally deleted in #683
> Add back _package.json

- docs/run/primitives.mdx
Closes #646 
Remove distracting formatting and review use of the word "provider" on this page.
> Tweaks to intro to primitives page

- README.md
Very minor corrections I found while following the guide.
> Tweak API generation guide

- docs/api/qiskit/0.40/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
- docs/api/qiskit/0.41/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
- docs/api/qiskit/0.42/qiskit.algorithms.linear_solvers.AbsoluteAverage.md
Part of https://github.com/Qiskit/documentation/issues/673.
> Fix bad Latex for Qiskit 0.40-0.42

- docs/run/monitor-job.mdx
- docs/verify/cloud-based-simulators.mdx
> Fix links for 1.0

- scripts/commands/regenerateApiDocs.ts
I regenerated the docs last night and we haven't changed Box artifacts since then. I want to regenerate the docs again today, so it's convenient to let me skip the download to speed things up.
> Allow skipping download when regenerating all docs

- docs/api/migration-guides/index.mdx
- docs/api/migration-guides/qiskit-1.0.mdx
This slipped through yesterday; think my brain was a bit fried 😅
> Fix migration guide links

- qiskit_bot.yaml
> qiskit-bot: add start folder and fix bug

- docs/run/configure-runtime-compilation.mdx
- docs/run/estimate-job-run-time.mdx
- docs/run/primitives-examples.mdx
- docs/run/primitives-get-started.mdx
- docs/start/hello-world.ipynb
> Specify optimization level with generate_preset_pass_manager

- docs/run/run-jobs-in-session.mdx
As pointed out by @Alienah, the statement being removed by this PR isn't true at this time.
> Remove sentence that doesn't apply

- qiskit_bot.yaml
Late response as reviewer was OOO.
> Add Qiskit bot reviewer for 'quantum-serverless' page

- scripts/lib/api/htmlToMd.ts
Part of https://github.com/Qiskit/documentation/issues/845.
> Extract another helper function in htmlToMd.ts

- docs/run/run-jobs-in-session.mdx
- docs/run/sessions.mdx
> Add note about recent change to sessions

- scripts/lib/api/conversionPipeline.ts
Work around https://github.com/Qiskit/documentation/issues/978.
> Work around Reno release notes issue with Runtime

- docs/api/migration-guides/v2-primitives.mdx
- docs/run/primitives-examples.mdx
> Update SamplerV2 example to use a list of circuits

- README.md
I thought it would look better this way
> restructure image

- docs/start/hello-world.ipynb
> Fix hello world 

- docs/support.mdx
Requested by @fvarchon to clarify for PayGO users how to contact support.
> Add info for Cloud users to access support

- docs/run/configure-runtime-compilation.mdx
> Clarify that Sampler V2 does not support optimization_level

- scripts/nb-tester/test-notebook.py
This notebook was fixed in #810
> Allowlist transpiler-stages.ipynb

- docs/run-new/_toc.json
- docs/run-new/index.mdx
- docs/run/index.mdx
> Refactor Run intro section for Qiskit Patterns

- docs/start/_toc.json
- docs/start/install.mdx
- docs/start/setup-channel.mdx
> Update install page

- docs/transpile/_toc.json
Fixes https://github.com/Qiskit/documentation/issues/1057.
I also decided to move "Represent quantum computers" to the end of the section.
> reorder transpile secion toc

- docs/run/advanced-runtime-options.mdx
> Fix zne example

- docs/start/hello-world.ipynb
- docs/verify/local-testing-mode.ipynb
- scripts/nb-tester/requirements.txt
- scripts/nb-tester/test-notebook.py
We weren't blocking PRs in CI on the notebook check, so some problems slipped through.
> Fix broken notebooks

- docs/start/index.mdx
Accidental change from https://github.com/Qiskit/documentation/pull/990. My bad!
> Revert bad change to start/index.mdx from testing

- .github/workflows/code-engine-preview.yml
- docs/run/circuit-execution.mdx
https://github.com/IBM-Cloud/ibm-cloud-cli-release/issues/202/ was fixed.
> Upgrade IBM Cloud CLI

- docs/run/retired-systems.mdx
> [1 APRIL] Add Kolkata and Mumbai to retired systems list

- docs/run/run-jobs-batch.mdx
closes #1081 
View changes here: https://qiskit-docs-preview-pr-1085.1799mxdls7qz.us-south.codeengine.appdomain.cloud/run/run-jobs-batch
> Changes for batch mode

- docs/start/hello-world.ipynb
Fixes #1110 and another mismatch I found doing a read-through
> Minor fixes in 'Hello world'

- .github/workflows/notebook-test-cron.yml
We have a new hub on IBM Quantum dedicated to testing docs content.
> Switch to dedicated testing hub

- docs/api/migration-guides/qiskit-1.0.mdx
> Update blog link on SDK 1.0 migration guide

- tutorials/README.md
Today's meeting reminded me of this gotcha. Adding it to the readme to save someone a headache in the future.
> Warn about tutorial titles

- docs/run/system-information.mdx
> Indicate metric for gate error: average gate fidelity

- docs/run/run-jobs-in-session.mdx
This should have been deleted yesterday.
> delete unwanted content

- scripts/ibm-quantum-learning-uploader/README.md
The script has undergone some changes that weren't reflected in the docs.
> Update learning uploader README.md

- scripts/nb-tester/qiskit_docs_notebook_tester/__init__.py
Blindly following advice from error message. I can't test as I don't have a Windows machine.
> Attempt `nb-tester` fix for Windows

- scripts/lib/api/TocGrouping.test.ts
Closes https://github.com/Qiskit/documentation/issues/1341.
> Generalize TocGrouping.test.ts for future Qiskit versions

- docs/run/configure-error-mitigation.mdx
- docs/run/configure-runtime-compilation.mdx
- docs/run/get-backend-information.ipynb
- docs/start/setup-channel.mdx
> Remove most references to qasm simulator

- docs/api/migration-guides/v2-primitives.mdx
> Fix code bug

- docs/api/migration-guides/local-simulators.mdx
> Add missing QiskitRuntimeService in migration guide

- docs/transpile/ai-transpiler-passes.mdx
- docs/transpile/qiskit-transpiler-service.mdx
In #1435 I did not update the status of the Qiskit transpiler service from "alpha" to "beta".
This PR fixes it
> Minor fix to reflect the Qiskit transpiler service is on beta status

- docs/verify/index.mdx
- docs/verify/local-testing-mode.ipynb
- docs/verify/simulate-with-qiskit-aer.ipynb
> aer has v2 primitives now

- scripts/lib/api/__snapshots__/conversionPipeline.test.ts.snap
- scripts/lib/api/testdata/qiskit-sphinx-theme/apidoc/index.html
- scripts/lib/api/testdata/qiskit-sphinx-theme/apidoc/inline_classes.html
- scripts/lib/api/testdata/qiskit-sphinx-theme/apidoc/module.html
- scripts/lib/api/testdata/qiskit-sphinx-theme/stubs/api_example.Electron.html
- scripts/lib/api/testdata/qiskit-sphinx-theme/stubs/api_example.my_function1.html
The name of the function was missing due to duplicate IDs.
> Fix function ID in integration test

- Dockerfile
- docs/run/advanced-runtime-options.mdx
Use preview app for PR previews
> Change docker image

- tutorials/README.md
Minor fix for clarity: make headers parallel
> Update header titles in tutorials readme

- tutorials/chsh-inequality/chsh-inequality.ipynb
> Add QPU estimate to CHSH

- tutorials/build-repetition-codes/build-repetition-codes.ipynb
- tutorials/chsh-inequality/chsh-inequality.ipynb
> Tutorial housekeeping: Build repetition codes

- docs/run/quantum-serverless.mdx
> IBMServerlessProvider deprecation - update serverless page

- docs/run/run-jobs-in-session.mdx
> Update broken threading code in Run-jobs-in-session

- Dockerfile
Closes https://github.com/Qiskit/documentation/issues/1551.
> Fix images in PR previews

- docs/run/processor-types.mdx
Fixes part of #1588. The other two will need to be fixed in the Qiskit source or HTML arifacts.
> Update redirected links

- scripts/patterns-reorg/page_content.py
Removed Qiskit TOQM item from the intro to qiskit page as it is no longer part of the qiskit ecosystem
> removed toqm from intro to qiskit page

- scripts/patterns-reorg/page_content.py
This PR fixes a broken link in the intro-to-patterns page
> Fix broken link

- scripts/commands/checkPatternsIndex.ts
- scripts/commands/checkQiskitBotFiles.ts
- scripts/patterns-reorg/update_qiskit_bot.py
This PR fixes our scripts to update the qiskit bot config file and the validation script for the pattern index pages
> Fix patterns scripts

- .github/workflows/notebook-test.yml
- scripts/commands/checkPatternsIndex.ts
- scripts/nb-tester/notebooks.toml
This PR finishes with all the To-Do we had from the guides reorg
> Complete guides reorg To-Do

- README.md
This component is unused and being removed.
> Remove README entry about Composer component

- start
This reduces resource usage. Otherwise you have to manually clean up containers.
> Clean up containers for local previews

- docs/guides/execute-on-hardware.mdx
- docs/guides/index.mdx
- docs/guides/intro-to-patterns.mdx
- docs/guides/map-problem-to-circuits.mdx
- docs/guides/optimize-for-hardware.mdx
- docs/guides/post-process-results.mdx
- docs/guides/transpile.mdx
- docs/guides/transpiler-stages.ipynb
> Ensure all images have alt text

- scripts/nb-tester/notebooks.toml
I think this was left in by accident
> Remove non-existent notebook from test list

- .github/actions/set-up-notebook-testing/action.yml
- .github/workflows/api-checks.yml
- .github/workflows/deploy-tutorials.yml
- .github/workflows/learning-uploader-test.yml
- .github/workflows/main.yml
- .github/workflows/weekly-checks.yml
- tutorials/qaoa-utility-scale/qopt_example.ipynb
Closes https://github.com/Qiskit/documentation/issues/1681.
> Disable GitHub Actions cache

- .github/workflows/notebook-test-cron.yml
Removes @kevinsung as per request.
> Update notebook test failure assignees

- .github/workflows/pr-preview.yml
- docs/guides/bit-ordering.mdx
- scripts/pr_previews/builder.py
- scripts/pr_previews/poll_deployment.py
Closes https://github.com/Qiskit/documentation/issues/1043.
> Enable PR previews

- scripts/commands/checkPagesRender.ts
I'm using this for testing but figured it might be helpful to report in our weekly checks too.
> Report page render times

- docs/open-source/index.mdx
Initial draft for index page in `/open-source`
> Qiskit open-source index page

- scripts/commands/checkPagesRender.ts
This really doesn't matter much but it bugged me that I had to use `!` on line 93. I think this is better.
> Improve types in page check

- docs/guides/_toc.json
This frees up valuable real estate in the left ToC.
> Move "Advanced setup" underneath "Install"

- README.md
Some small improvements with changes we've made over time.
> Refresh README instructions

- docs/guides/custom-transpiler-pass.ipynb
- docs/guides/dynamical-decoupling-pass-manager.ipynb
- docs/guides/set-optimization.ipynb
- docs/guides/transpile-with-pass-managers.ipynb
- docs/guides/transpile.mdx
- docs/guides/transpiler-stages.ipynb
Closes #1694 
Also addresses @javabster 's comment "we should remove any text referring to the transpile() function and talk about generate_preset_passmanager instead"
> Nit in set-optimization

- .github/actions/set-up-notebook-testing/action.yml
Copies https://github.com/Qiskit/qiskit-neko/pull/48 to temporarily fix CI.
> Temp fix for CI

- docs/guides/fair-share-scheduler.mdx
Closes #1768 
Bringing in the file updated by @francabrera
> language change: "share" replaced by "allocation"

- docs/guides/execution-modes-faq.mdx
- docs/guides/max-execution-time.mdx
- docs/guides/run-jobs-batch.mdx
- docs/guides/run-jobs-session.mdx
> Update wording on batch limits

- docs/guides/execution-modes-faq.mdx
Add to execution modes FAQ about whether users can change iTTL or max TTL.
> Add TTL change to FAQ

- docs/guides/execution-modes.mdx
- docs/guides/max-execution-time.mdx
- docs/guides/primitives-examples.mdx
- docs/guides/run-jobs-batch.mdx
- docs/guides/run-jobs-session.mdx
- docs/migration-guides/qiskit-algorithms-module.mdx
- docs/migration-guides/qiskit-runtime-from-ibm-provider.mdx
- docs/migration-guides/v2-primitives.mdx
Closes #1805 
Batches should be closed to avoid confusion
> Need to close a batch

- docs/guides/specify-observables-pauli.mdx
> Fix gate ordering for Y-basis measurement

- docs/open-source/_toc.json
> Replace absolute links to contributor license agreements by relative ones

- docs/guides/get-qpu-information.ipynb
- docs/guides/instances.mdx
- docs/guides/monitor-job.mdx
- docs/guides/retired-qpus.mdx
- docs/guides/run-jobs-batch.mdx
- docs/guides/run-jobs-session.mdx
- docs/guides/sessions.mdx
> Remove references to ibm_provider

- qiskit_bot.yaml
Fixing the github username in one of the qiskit_bot entries because a different Becky was being tagged!
> Wrong Becky was tagged in qiskit_bot

- docs/guides/specify-runtime-options.mdx
> Add twirling options to Shots description

- docs/guides/execution-modes.mdx
- docs/guides/instances.mdx
Usage applies across all QPUs.
> Clarify priority and usage

- docs/guides/specify-runtime-options.mdx
closes #1878 
Added a note here: https://qiskit.github.io/documentation/pr-1883/guides/specify-runtime-options#precision-estimator-only
> Precision scales with usage

- docs/guides/instances.mdx
> clarification that active jobs still run

- scripts/js/commands/api/regenerateApiDocs.ts
The script is quite slow, so it's better to log the output eagerly so it doesn't look like things hung.
> Eagerly log output of `regen-apis`

- docs/guides/latest-updates.mdx
- docs/guides/primitive-input-output.ipynb
- scripts/js/commands/checkSpelling.ts
Add the latest blog entry as well as "What's new in the docs" from July/August.
> Update the latest-updates file

- docs/guides/_toc.json
- docs/guides/ai-transpiler-passes.mdx
- docs/guides/index.mdx
- docs/guides/noise-learning.ipynb
- docs/guides/optimize-for-hardware.mdx
- docs/guides/primitives-rest-api.mdx
- docs/guides/qiskit-transpiler-service.mdx
- docs/guides/transpile-rest-api.mdx
- docs/guides/transpile.mdx
Closes #1899 - also other small fixes across the docs
> Spot-cleaning: typos and other tweaks

- README.md
Closes https://github.com/Qiskit/documentation/issues/1841.
> Document how to upgrade noteboook requirements.txt

- docs/guides/monitor-job.mdx
> Fix monitor-job

- docs/guides/max-execution-time.mdx
> Update code to not use the Options class

- docs/guides/_toc.json
- docs/guides/algorithmiq-tem.ipynb
- docs/guides/intro-to-patterns.mdx
- docs/guides/latest-updates.mdx
- docs/guides/optimize-for-hardware.mdx
By request - updating the Algorithmiq function name to Tensor-network error mitigation
> Adjust function name to Tensor-network error mitigation

- docs/guides/hello-world.ipynb
- docs/guides/index.mdx
- docs/responsible-quantum-computing.mdx
> Remove reporting link until it's externally accessible

- scripts/config/cspell/dictionaries/qiskit.txt
> Sync cspell config

- docs/guides/functions.ipynb
> Lint notebooks

- docs/guides/qiskit-code-assistant-jupyterlab.mdx
- docs/guides/qiskit-code-assistant-vscode.mdx
- docs/guides/qiskit-code-assistant.mdx
> Improve code assist docs

- README.md
I keep getting tripped up on all the places we need to list new files.  Adding that information here in hopes of saving all those failed builds!
> Add details to New page instructions

- docs/guides/ibm-circuit-function.ipynb
> Add defaults to options

- docs/guides/functions.ipynb
> Add missing job statuses

- docs/guides/index.mdx
> benchmarking info for intro pg

- scripts/js/commands/checkPatternsIndex.ts
Unblocks https://github.com/Qiskit/documentation/pull/2000. We plan to link to the other index pages on the intro page, but those index pages don't show up under "Tools" so we would get an error like this:
```
❌ docs/guides/intro-to-patterns.mdx: The entry /guides/map-problem-to-circuits doesn't appear in the `Tools` menu.
```
Now you can allowlist those URLs.
> Allow page to be linked from index page but not in Tools ToC

- docs/guides/online-lab-environments.mdx
- scripts/js/lib/links/ignores.ts
Closes https://github.com/Qiskit/documentation/issues/2047.
There is one remaining issue with Qiskit 0.46 that I will fix in the Qiskit SDK repo.
> Fix link ignores with external links

- docs/guides/_toc.json
> toc nesting audit

- docs/guides/_toc.json
- docs/guides/execute-on-hardware.mdx
- docs/guides/job-limits.mdx
- docs/guides/primitives-examples.mdx
- docs/guides/run-jobs-batch.mdx
- docs/guides/run-jobs-session.mdx
- qiskit_bot.yaml
> Document job limitations

- scripts/js/commands/api/syncDevDocs.ts
The cron job was failing because Runtime's recent `main` branch CI runs have failing integration tests. Those are irrelevant to the docs build, so we should tolerate it.
> Handle Runtime dev docs' CI having integration test failures

- .github/ISSUE_TEMPLATE/new-content.yaml
> Adjust issue template with new label

- .github/ISSUE_TEMPLATE/bug.yaml
Update to match the new-content issue template
> update bug issue template

- docs/guides/qiskit-transpiler-service.mdx
> Clarify transpiler service limitations

- docs/guides/dynamical-decoupling-pass-manager.ipynb
> Fix typo in dynamical-decoupling file

- docs/guides/latest-updates.mdx
- scripts/js/commands/checkInternalLinks.ts
> Add latest blog to latest updates page

- docs/guides/_toc.json
- docs/guides/execution-modes.mdx
- docs/guides/max-execution-time.mdx
- docs/guides/run-jobs-batch.mdx
- docs/guides/run-jobs-session.mdx
- docs/guides/sessions.mdx
Improve documentation about execution modes; specifically clarifying the max timeout information
> Improvements to execution modes docs

- .github/workflows/weekly-checks.yml
> Update assignees for weekly checks

- docs/guides/q-ctrl-optimization-solver.ipynb
- docs/guides/q-ctrl-performance-management.ipynb
This PR updates the contact link for one of Q-CTRL's docs notebooks.
> chore: Update contact link

- docs/guides/_toc.json
- docs/guides/latest-updates.mdx
Both content and infra changes are reflected here.
> What's new in the docs updates since early Sept

- docs/guides/plot-quantum-states.ipynb
Expressions must be JSON serializable
> Fix syntax in CodeAssistantAdmonition

- docs/guides/run-jobs-session.mdx
Closes #2176 
I searched and didn't find any other improperly coded imports.  Hopefully there aren't any more lurking in there!
> Update Sampler import

- docs/guides/configure-error-mitigation.mdx
> Mention mthree on configure-error-mitigation

- docs/migration-guides/_toc.json
> Rename Migrate to Qiskit Runtime section

- docs/guides/serverless-hamsim-template.ipynb
I am not able to push directly to the branch in #2300, so I opened this instead.
> Tweaks to function template guide

- docs/guides/runtime-options-overview.mdx
Closes #2256.
~Waiting on a name for the option~ name is gen3-turbo
> [MERGE THU 14 NOV] Add experimental option to runtime options table

- docs/api/qiskit-addon-sqd/_package.json
- docs/api/qiskit-addon-sqd/release-notes.mdx
There was an issue with the release notes, so it's not properly classified with the release.
> Bump version for qiskit-addon-sqd

- docs/guides/latest-updates.mdx
> Add QDC blog to latest updates page

- docs/guides/ai-transpiler-passes.mdx
> Fixing typos in AI transpile passes examples

- README.md
This will help people find and fix the issue.
> add error to new notebook text

- docs/guides/runtime-options-overview.mdx
> Add backends to gen3-turbo support list

- README.md
- docs/guides/build-noise-models.ipynb
> Fix Latex inside table

- scripts/js/commands/checkPagesRender.ts
https://github.com/Qiskit/documentation/pull/2389#discussion_r1857383341
> Fix use of yargs conflicts()

- docs/api/qiskit-addon-mpf/backends-quimb-circuit-circuit-evolver.mdx
- docs/api/qiskit-addon-mpf/backends-quimb-circuit.mdx
- docs/api/qiskit-addon-mpf/dynamic.mdx
Fixed in https://github.com/Qiskit/qiskit-addon-mpf/pull/38
> Fix broken link in qiskit-addon-mpf

- docs/guides/common-parameters.ipynb
> remove deprecated tag

- docs/guides/primitive-input-output.ipynb
- docs/guides/specify-runtime-options.mdx
- docs/migration-guides/v2-primitives.mdx
> Describe how to convert V2 output back to V1

- .github/workflows/notebook-test-cron.yml
- .github/workflows/weekly-checks.yml
- scripts/js/lib/links/ignores.ts
Also set better labels for our weekly CI jobs.
> Ignore valid journal link

- docs/guides/latest-updates.mdx
> Add Qiskit 1.3 release summary to Latest Updates

- docs/guides/pulse.ipynb
- docs/migration-guides/_toc.json
- docs/migration-guides/pulse-migration.mdx
- qiskit_bot.yaml
> Add pulse migration guide

- docs/guides/retired-qpus.mdx
Related to https://github.ibm.com/IBM-Q-General/client-comms/issues/461
need to verify number of qubits
> Add Nazca to retired QPUs list

- docs/guides/pulse.ipynb
Closes #2414
There's actually already an admonition at the top of the page so this PR just ignores the warnings. I've ignored all warnings in all cells.
> Ignore warnings in `pulse.ipynb`

- scripts/ci/pr-execute-notebooks.py
I missed this while migrating the test to it's own file.
> Fix new notebook CI

- docs/guides/_toc.json
- start
Pulls in new features, including the "new" pill
> Update preview image

- docs/guides/runtime-options-overview.mdx
> Remove aachen

- docs/guides/latest-updates.mdx
- scripts/config/cspell/dictionaries/qiskit.txt
Mid/late Oct through mid Dec updates.
> Update "What's new in the documentation"

- docs/api/qiskit/0.19/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.24/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.25/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.26/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.27/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.28/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.29/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.30/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.31/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.32/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.33/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.35/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.36/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.37/qiskit.transpiler.CouplingMap.mdx
- docs/api/qiskit/0.38/qiskit.transpiler.CouplingMap.mdx
- scripts/config/historical-pages-to-latest.json
Closes https://github.com/Qiskit/documentation/issues/2476. The artifacts were updated directly and uploaded to Box, then regenerated with `npm run regen-apis`.
> Fix Pillow links

- docs/guides/serverless-template-hamiltonian-simulation.ipynb
> Ensure that the two source listings are equivalent

- docs/guides/_toc.json
- docs/guides/execute-on-hardware.mdx
- docs/guides/index.mdx
- docs/guides/intro-to-patterns.mdx
- docs/guides/map-problem-to-circuits.mdx
- docs/guides/optimize-for-hardware.mdx
- docs/guides/post-process-results.mdx
> Update workflow name for globalization

- scripts/js/commands/checkMetadata.ts
- scripts/js/commands/checkPagesRender.ts
- translations/.gitkeep
The infrastructure is going to live in closed source.
> Remove translations infrastructure

- scripts/js/lib/links/ignores.ts
Closes https://github.com/Qiskit/documentation/issues/2521.
> Ignore link to auth endpoint

- README.md
- docs/guides/install-qiskit-source.mdx
- docs/guides/install-qiskit.mdx
- docs/migration-guides/qiskit-1.0-installation.mdx
- scripts/config/cspell/dictionaries/qiskit.txt
- scripts/nb-tester/README.md
Address user feedback from Qiskit Slack
> Clarify the notebook path

- scripts/config/notebook-testing.toml
- scripts/nb-tester/requirements.txt
> Don't install pyscf on windows

- start
Updates Docker image digest and adds option to pass environment variable.
> Update local preview

- docs/guides/addons.mdx
- docs/guides/qiskit-addons-aqc.mdx
- docs/guides/qiskit-addons-obp.mdx
- docs/guides/qiskit-addons-sqd.mdx
> Add tutorial links to addons

- docs/guides/index.mdx
- scripts/pr-previews/builder.py
- start
This PR updates the preview to use the new `docs/` structure where we need to specify that the content corresponds to the English locale.
> Update previews to set the correct docs' path

- docs/guides/multiverse-computing-singularity.ipynb
This PR:
1. Removes `IBMServerlessClient`.
2. Updates client methods to catalog methods for shared data directory usage.
> Change shared data directory interface in multiverse documentation

- docs/faq.mdx
- docs/migration-guides/_toc.json
- docs/migration-guides/index.mdx
- docs/migration-guides/metapackage-migration.mdx
- docs/migration-guides/qiskit-1.0-installation.mdx
- docs/migration-guides/qiskit-1.0.mdx
- qiskit_bot.yaml
Closes #2487 and is the last issue for and closes #2146
> Add metapackage migration guide

- docs/guides/get-qpu-information.ipynb
- scripts/config/notebook-testing.toml
> Fix get-qpu-information

- docs/migration-guides/migrate-classic-rest-api.mdx
Adding clarity to the rest api migration guide.
> Update rest migration guide

- docs/faq.mdx
- docs/guides/cloud-setup.mdx
closes #2713 
Users have been confused because they have the wrong account.
> Add instructions to choose a different account to a few more places

- docs/guides/_toc.json
- docs/guides/cloud-setup.mdx
- docs/guides/manage-cost.mdx
preview: https://qiskit.github.io/documentation/pr-2729/guides/manage-cost#set-or-change-a-cost-limit-or-instance-limit
> Update commands to add a cost limit

- docs/guides/cloud-setup.mdx
- docs/migration-guides/classic-iqp-to-cloud-iqp.mdx
- docs/migration-guides/index.mdx
- docs/migration-guides/migrate-classic-rest-api.mdx
Make sure the correct new name is used everywhere.
> classic to Classic

- docs/guides/_toc.json
> Add new pill to Qunova notebook

- qiskit_bot.yaml
Adding myself as docs team contact to qiskit_bot.yaml
> Add docs team member to qiskit_bot.yaml for qunova

- docs/guides/qunova-chemistry.ipynb
> Update paper link for Qunova

- docs/faq.mdx
- docs/support.mdx
Closes #2752 
Will add to the support page as an admonition, and also an item in the FAQ
Note: made the topic more general ("trouble logging in") since the steps to resolve are the same with other cloud account creation issues.
> Login loop issue admonition

- docs/guides/_toc.json
- docs/guides/qunova-chemistry.ipynb
Closes #2770 
@pandasa123 FYI.
> replace with updated name for Qunova function

- docs/api/qiskit-c/sparse-observable.mdx
- scripts/js/lib/api/processHtml.test.ts
- scripts/js/lib/api/processHtml.ts
This PR fixes the code blocks of `qiskit-c` to set the correct programming language.
> Qiskit C API: Fix code block to be C

- docs/guides/_toc.json
- docs/migration-guides/_toc.json
Closes #2838 
Checked toc files in both `/guides/` and `/migration-guides/`.
> Remove New pill on anything older than 2 weeks

- scripts/nb-tester/requirements.txt
Workaround for https://github.com/osqp/osqp/issues/728
> Fix CI by pinning osqp

- docs/guides/_toc.json
Fix TOC
preview: https://qiskit.github.io/documentation/pr-2923/guides/
> Move Accounts section

- docs/guides/monitor-job.mdx
> Update `monitor-job.mdx` jobs example

- docs/migration-guides/classic-iqp-to-cloud-iqp.mdx
DO NOT MERGE UNTIL APRIL 10
Add sunset date and link to "retrieve and download jobs"
Updated content: https://qiskit.github.io/documentation/pr-2959/migration-guides/classic-iqp-to-cloud-iqp
> Add sunset date

- docs/migration-guides/metapackage-migration.mdx
- scripts/config/cspell/dictionaries/qiskit.txt
- scripts/js/commands/checkSpelling.ts
Closes https://github.com/Qiskit/documentation/issues/2914.
> Spellcheck table of contents

- docs/guides/plans-overview.mdx
closes #2707 !!!
Adding this description for completeness.
> Add a description of the dedicated service

- docs/tutorials/improving-energy-estimation-of-a-fermionic-hamiltonian-with-sqd.ipynb
> fix import formatting

- docs/guides/considerations-set-up-runtime.mdx
@Matt-Stypulkoski noticed this behavior and requested that it be called out more clearly.
> You can cancel others' workloads

- docs/guides/classical-feedforward-and-control-flow.ipynb
- docs/guides/runtime-options-overview.mdx
> Dynamic circuits deprecation

- docs/guides/hello-world.ipynb
- docs/guides/install-qiskit.mdx
- docs/tutorials/chsh-inequality.ipynb
- start
This PR adds the base path to two links that were missing.
> Add base path to `ImageLink`s

- scripts/js/lib/api/updateLinks.test.ts
- scripts/js/lib/api/updateLinks.ts
> Relativize cloud base links

- .github/workflows/api-checks.yml
- .github/workflows/notebook-test.yml
> Run API and notebook tests on workflow change

- docs/tutorials/solve-higher-order-binary-optimization-problems-with-q-ctrls-optimization-solver.ipynb
I missed this notebook while migrating the tutorials.
> Set missing platform metadata

- .github/ISSUE_TEMPLATE/courses.yaml
- .github/ISSUE_TEMPLATE/guides.yaml
- .github/ISSUE_TEMPLATE/tutorials.yaml
> URL typo in issue template

- docs/guides/qiskit-addons-obp.mdx
> Add reference to OBP guide

- qiskit_bot.yaml
modify qiskit-bot yaml to update github handles of various tutorial authors
> add tutorials authors

- docs/guides/hello-world.ipynb
- docs/guides/install-qiskit.mdx
> Clarify Jupyter usage

- LICENSE
- LICENSE-DOCS
- README.md
After team discussions the decision has been made to update our license to protect content under a creative commons license that is more appropriate than apache 2.0 (which is designed for code). all code remains licensed under apache 2.0
> update license file to include creative commons terms

- docs/guides/instances.mdx
> Fix broken links in instances guide

- docs/guides/run-jobs-batch.mdx
> Update max ttl defaults

- docs/guides/qiskit-addons-sqd-get-started.ipynb
> Add admonition about pyscf in SQD guide

- scripts/nb-tester/requirements.txt
> Adds additional tutorials requirements for nb-tester

- docs/tutorials/_toc.json
- docs/tutorials/index.mdx
Update category name from "Workflows toward utility" to "Workflows toward advantage"
> Update tutorial category name

- docs/guides/qiskit-addons-sqd-get-started.ipynb
Closes #3051 
The print call when outputting the batch size was causing the strange rendering issue.
> Fix SQD output

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/courses.yaml
- .github/ISSUE_TEMPLATE/guides.yaml
- .github/ISSUE_TEMPLATE/tutorials.yaml
- .github/ISSUE_TEMPLATE/ui.yml
- Add Chris Porter's id
- add emojis
- clean up escape characters that didn't work
> Follow-on cleanup for issue templates

- .github/ISSUE_TEMPLATE/guides.yaml
- .github/ISSUE_TEMPLATE/tutorials.yaml
Still testing. Will need to open one more PR to implement, after I figure out what works
> 3rd try: docs-content-team tag in issue templates

- docs/guides/index.mdx
- start
This PR updates the image hash in the `start` script.
> Update preview image hash

- .github/workflows/weekly-checks.yml
- docs/guides/_toc.json
- docs/migration-guides/_toc.json
Closes #3179 
The `new-pill-checker` was incorrectly formatted in the `.yml` file. I also removed all of the outdated new pills here.
Passing workflow run on this branch: https://github.com/Qiskit/documentation/actions/runs/15217555309
> Fix new pill workflow

- docs/guides/access-groups.mdx
> Add Support Center access policy to admin access group docs

- docs/guides/get-qpu-information.ipynb
Remove channel specification and mention of Sherbrooke from get-qpu-information file
> Remove channel specification

- scripts/nb-tester/qiskit_docs_notebook_tester/config.py
I left this in from debugging :facepalm:
> [nb-tester]: Make warning ignores more specific

- learning/courses/quantum-diagonalization-algorithms/krylov.ipynb
> Fix KQD typo

- learning/courses/basics-of-quantum-information/entanglement-in-action/introduction.ipynb
- learning/courses/basics-of-quantum-information/multiple-systems/introduction.ipynb
- learning/courses/basics-of-quantum-information/quantum-circuits/introduction.ipynb
- learning/courses/basics-of-quantum-information/single-systems/introduction.ipynb
- learning/courses/foundations-of-quantum-error-correction/correcting-quantum-errors/introduction.ipynb
- learning/courses/foundations-of-quantum-error-correction/fault-tolerant-quantum-computing/introduction.ipynb
- learning/courses/foundations-of-quantum-error-correction/quantum-code-constructions/introduction.ipynb
- learning/courses/foundations-of-quantum-error-correction/stabilizer-formalism/introduction.ipynb
- learning/courses/fundamentals-of-quantum-algorithms/grover-algorithm/introduction.ipynb
- learning/courses/fundamentals-of-quantum-algorithms/phase-estimation-and-factoring/introduction.ipynb
- learning/courses/fundamentals-of-quantum-algorithms/quantum-algorithmic-foundations/introduction.ipynb
- learning/courses/fundamentals-of-quantum-algorithms/quantum-query-algorithms/introduction.ipynb
- learning/courses/general-formulation-of-quantum-information/density-matrices/introduction.ipynb
- learning/courses/general-formulation-of-quantum-information/general-measurements/introduction.ipynb
- learning/courses/general-formulation-of-quantum-information/purifications-and-fidelity/introduction.ipynb
- learning/courses/general-formulation-of-quantum-information/quantum-channels/introduction.ipynb
- learning/courses/quantum-diagonalization-algorithms/krylov.ipynb
Added pdfs back into John Watrous's courses.
Fixes #3469 and its duplicates.
> Add PDFs back to John Watrous's courses

- docs/tutorials/repeat-until-success.ipynb
> Remove old tutorial

- qiskit_bot.yaml
Updating some tags in the qiskit-bot.yaml file to reflect tutorial ownership
> Update qiskit_bot.yaml to add tutorials owners

- qiskit_bot.yaml
- scripts/js/commands/checkQiskitBotFiles.ts
Closes #3557 
@beckykd and @abbycross I looked through the commit history for some of these and put you both as owners on files that made sense to me. Would you mind checking to make sure the files I've added ya'll to make sense?
> Add bot owners to new GA pages

- docs/guides/qiskit-code-assistant-local.mdx
Hi! 
In this PR we would like to add documentation related to the use of `llama.cpp` for the Qiskit Code Assistant GGUF models. 
CC: @cbjuan
> Adding documentation for the usage of `llama.cpp` for Qiskit Code Assistant GGUF models

- docs/tutorials/quantum-approximate-optimization-algorithm.ipynb
Fixes #3550
Fixes typo in QAOA "vertices" -> "edges"
> Fixed QAOA typo vertices-> edges

- docs/security/_toc.json
- docs/security/index.mdx
- docs/security/responsibilities.mdx
- qiskit_bot.yaml
Part of #3525.
Need to find a way to indicate differences among plans - possibly with flair tags. See box note.
> Responsibilities for GA

- learning/courses/variational-algorithm-design/optimization-loops.ipynb
Fixes #3541
Text has been added explaining that the 8 refers to the number of variational parameters.
> VAD course - add expl text

- learning/courses/quantum-machine-learning/quantum-kernel-methods.ipynb
- learning/modules/quantum-mechanics/bells-inequality-with-qiskit.ipynb
Fixes #3585 
Fixed latex typo in exponent.
> Fixed minor latex typo in answer to checkin question

- learning/courses/general-formulation-of-quantum-information/general-measurements/naimark-theorem.ipynb
> Typo in Naimark's theorem metadata

- docs/guides/simulate-with-qiskit-sdk-primitives.ipynb
> remove copy/paste error from code snippet

- scripts/js/commands/checkInternalLinksFromOtherRepo.ts
- scripts/js/commands/checkMetadata.ts
- scripts/js/commands/checkNewPills.ts
- scripts/js/commands/checkOrphanPages.ts
- scripts/js/commands/checkPatternsIndex.ts
- scripts/js/lib/apiVersions.ts
- scripts/js/lib/fs.ts
- scripts/js/lib/markdownReader.test.ts
- scripts/js/lib/markdownReader.ts
closes #3592 Added a new helper function readJsonFile, and modified other files.
> Improve lint error messages for JSON parsing

- docs/guides/cloud-setup.mdx
- docs/security/ha-dr.mdx
> Add instructions to log in

- docs/guides/multiverse-computing-singularity.ipynb
Closes Qiskit/documentation#3626
> Update multiverse singularity machine learning documentation

- learning/courses/quantum-safe-cryptography/symmetric-key-cryptography.ipynb
- learning/courses/quantum-safe-cryptography/whats-next.mdx
> Updated post-survey link and fixed typo in quantum-safe cryptography course

- docs/responsible-quantum-computing.mdx
Add link to the Cloud Services Agreement to Responsible Quantum Computing page
> add acceptable use link

- learning/courses/basics-of-quantum-information/entanglement-in-action/chsh-game.ipynb
> Fix typo on qubit labels

- learning/courses/basics-of-quantum-information/entanglement-in-action/chsh-game.ipynb
- learning/courses/quantum-safe-cryptography/quantum-safe-cryptography.ipynb
> Fixed figure caption (changed 'red vector' to 'yellow vector')

- learning/courses/quantum-diagonalization-algorithms/krylov.ipynb
> Correcting crossover dimension in Krylov

- .github/workflows/dev-docs-sync.yml
- .github/workflows/notebook-test-cron.yml
To make sure they are seen by the right people
> Update who gets notified by github actions

- learning/courses/fundamentals-of-quantum-algorithms/phase-estimation-and-factoring/phase-estimation-procedure.ipynb
> Fixed missing i's in exponents

- docs/guides/runtime-options-overview.mdx
closes #3745 
Preview: https://qiskit.github.io/documentation/pr-3748/docs/guides/runtime-options-overview
> Reformat options table

- docs/guides/fair-share-scheduler.mdx
Has been approved offline by @marcolincs
> Update fair-share-scheduler page

- docs/guides/qpu-information.mdx
> Reordering information in qpu-information.mdx

- docs/guides/q-ctrl-performance-management.ipynb
Updated Fire Opal Management documentation to reflect supported Qiskit versions
> docs: Update qctrl version documentation

- docs/migration-guides/index.mdx
- docs/security/index.mdx
> Remove links from index pages

- docs/guides/choose-execution-mode.mdx
- docs/guides/execution-modes.mdx
- docs/guides/plans-overview.mdx
- docs/migration-guides/qiskit-algorithms-module.mdx
- docs/migration-guides/qiskit-backendv1-to-v2.mdx
- docs/migration-guides/qiskit-runtime-from-ibmq-provider.mdx
- learning/courses/fundamentals-of-quantum-algorithms/exam.mdx
> Remove characters that aren't allowed from titles and descriptions

- docs/accessibility.mdx
> add link to ACR

- docs/guides/classical-feedforward-and-control-flow.ipynb
- scripts/js/commands/checkInternalLinks.ts
Wait till we get the green light to merge.
Also, do not merge before the referenced announcement merges!
Finishes work started in #3943
> Remove admonition

- docs/guides/instances.mdx
- docs/guides/manage-cost.mdx
> Add link to permissions information
